### ISSUE TITLE
Conform default code generation to specific style

### ISSUE THREAD

**Issue by thejameskyle** [6to5/6to5#216]
There are several popular javascript style guides out there, the most popular one I see (and use) is the [Airbnb Javascript Style Guide](https://github.com/airbnb/javascript). There's also the slightly less popular [Idiomatic.js](https://github.com/rwaldron/idiomatic.js), or the really old [Google Javascript Style Guide](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml).

I can grab this if you want @sebmck.

**Comment by sebmck** [comment]
Closing due to previous discussion in this issue. See also #467 which alleviates some of this issues original concerns.
