### ISSUE TITLE
commonInterop export * handling

### ISSUE THREAD

**Issue by guybedford** [6to5/6to5#224]
This is actually another edge case unfortunately.

If my CommonJS module looks like:

cjs-module.js
```javascript
module.exports = 'hello world';
```

Then `export * from 'cjs-module'` should export a `default` property containing the module value itself, but won't be able to provide this behaviour.

The reason for this is that the CommonJS module exports `default` property which won't be picked up by the `export *` statement as it has no __esModule flag to know if it should be seen as the CommonJS wrapper module.

It's an edge case certainly, probably fine to ignore, just trying to be aware of them all.

**Comment by guybedford** [comment]
@sebmck https://github.com/6to5/6to5/commit/2558a5e12eaa40895d539789b3cf116cdaa89af2 doesn't seem quite right to me, wildcards should never collapse to the default export?

**Comment by sebmck** [comment]
@guybedford It does exactly what was discussed in this issue? Since current module interop will set `module.exports` and `import *` should be returning an object with a `default` unless I'm mistaken?

**Comment by guybedford** [comment]
@sebmck my apologies I skimmed the commit and thought this was for the System.register exports * handling not the CommonJS interop format.

Ok, this is great then!

The only exception I can see here is that `export default { some: 'value' }` would be interpreted as `{some: 'value'}` if it was the only export?

**Comment by sebmck** [comment]
@guybedford Yeah, that's right. Not quite sure how to get around that though.

**Comment by guybedford** [comment]
I guess this is why I was pushing for a flag. Perhaps you'd only need to add the flag in this exception case?

**Comment by sebmck** [comment]
@guybedford Yeah, I can definently see justification for it now.
