### ISSUE TITLE
commonInterop hasOwnProperty

### ISSUE THREAD

**Issue by guybedford** [6to5/6to5#225]
When doing `import {name} from 'cjs-module'`, we should probably add a hasOwnProperty to the check:

```javascript
var _ref = require('cjs-module');
var name = _ref && _ref.hasOwnProperty('name') && _ref.name;
```

So we don't have prototype method conflicts. Similarly for `export *`. As per usual, shut me up if these edge cases are too detailed to worry about.

**Comment by sebmck** [comment]
Closing this for now. Feel free to open if you think it's a major issue though.
