### ISSUE TITLE
Template literal with curly braces

### ISSUE THREAD

**Issue by Attamusc** [6to5/6to5#237]
Hello!

I'm not 100% sure if this actually belongs here or in the acorn fork, but I noticed the following code throwing an "Unexpected token" error when compiling 

```
var x = "foo";
var y = `{${x}}`;
```

while this does not

```
var x = "foo";
var y = `{ ${x} }`;
```

It seems due to the immediate presence of a closing curly brace after the interpolated variable's closing curly brace. Let me know if this is the wrong spot for this and I'd be more than happy to shift this issue there.

**Comment by thejameskyle** [comment]
Assuming this was fixed in https://github.com/6to5/6to5/commit/31fff092b68e7d445266df1366b1c40ad827fb27.

**Comment by sebmck** [comment]
@thejameskyle This was fixed ages ago. I forgot to close the issue though.

**Comment by thejameskyle** [comment]
Derp, missed the dates.
