### ISSUE TITLE
await/yield in list comprehension generates invalid ES5 code

### ISSUE THREAD

**Issue by michaelstephendavies** [6to5/6to5#252]
`to5.transform("function* f(xs) {return [for (x of xs) yield x] }", {experimental: true})` generates code involving:

    _toArray(xs).map(function (x) {
          return yield x;
    })

which is not valid ES5 since the `yield` is still there. The same is true of `await`. Using `[for (x of xs) for (y of ys) yield (x+y)]` no longer uses `map`, but still leaves the `yield` in there.

I don't know if `await`/`yield` in list comprehensions is allowed. If it isn't, it should give a compile error rather than generating invalid code.

**Comment by zloirock** [comment]
IIFE still breaks this case.

**Comment by sebmck** [comment]
@zloirock Nope?

```sh
$ 6to5 --experimental --blacklist generators
```

```javascript
function* f(xs) {return [for (x of xs) yield x] }
```

```javascript
"use strict";

function* f(xs) {
  return yield* (function () {
    var _arr = [];

    for (var _iterator = xs[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {
      var x = _step.value;
      _arr.push((yield x));
    }

    return _arr;
  })();
}

**Comment by zloirock** [comment]
@sebmck http://goo.gl/w2wAFP

**Comment by sebmck** [comment]
@zloirock Likely a regenerator bug, investigating.

**Comment by sebmck** [comment]
@zloirock Thanks. I was setting `generator = true;` on the call instead of the function node.
