### ISSUE TITLE
Support for tail call optimization

### ISSUE THREAD

**Issue by kobezzza** [6to5/6to5#256]
http://www.2ality.com/2014/04/call-stack-size.html
*ECMAScript 6 will have tail call optimization: If a function call is the last action in a function, it is handled via a “jump”, not via a “subroutine call”. That means that, if you slightly rewrote computeMaxCallStackSize(), it would run forever under ECMAScript 6 (in strict mode)*

**Tail call recursion**
```js
function fac_times(n, acc) {
	return (n == 0) ? acc : fac_times(n - 1, acc * n);
}

function factorial(n) {
	return fac_times(n, 1);
}
```

**After optimization**
```js
function fac_times(n, acc) {
	while (true) {
		if (n == 0) {
			return acc;
		}
	
		var old_n = n,
			old_acc = acc;
	
		n = old_n - 1;
		acc = old_acc * old_n;
	}
}

function factorial(n) {
	return fac_times(n, 1);
}
```

**Comment by whmountains** [comment]
I would like to see this feature as an option.  It would allow you to iterate over nested trees without worrying about exceeding your call stack limit.

**Comment by impinball** [comment]
@whmountains, If you're talking about iterating nested trees, then I can assure TCO won't help here. I know this is not something that qualifies as a tail call:

```js
function foo(node) {
  for (let key of Object.keys(node)) {
    foo(node[key]);
  }
}
```

And, IIRC, most call stacks top out at 2^32 - 1, so if you reach that ever, even in recursively called functions, it may be time for a refactor.

**Comment by whmountains** [comment]
Sorry, my bad.  I guess that means that I'm accidentally getting an infinite loop, not having a overly large dataset.

On Jan 12, 2015, at 07:08 PM, impinball <notifications@github.com> wrote:

@whmountains, If you're talking about iterating nested trees, then I can assure TCO won't help here. I know this is not something that qualifies as a tail call:
function foo(node) {
  for (let key of Object.keys(node)) {
    foo(node[key]);
  }
}
And, IIRC, most call stacks top out at 2^32 - 1, so if you reach that ever, even in recursively called functions, it may be time for a refactor.
—
Reply to this email directly or view it on GitHub.

=

**Comment by impinball** [comment]
@all Here's another good candidate of tail call elimination. AFAICT, it is a tail call according to the draft.

```js
function reduce(xs, f) {
  switch (xs.length) {
  case 0: return null;
  case 1: return xs[0];
  case 2: return f(xs[0], xs[1]);
  default:
    let [first, second, ...rest] = xs;
    return reduceRight([f(first, second), ...rest], f);
  }
}
```

**Comment by bmeck** [comment]
@impinball unfortunately dynamic tail calls are not able to be optimized safely via a transpiler. in the case of your example `6to5` would need to know what the source code of `f` is and inline it (destroying the closure).

**Comment by sebmck** [comment]
The only way tail calls can be implemented safely is if the tail call is referencing it's parent function or another function in the same file so we can track parameters and arguments correctly.

**Comment by RReverser** [comment]
> The only way tail calls can be implemented safely is if the tail call is referencing it's parent function or another function in the same file so we can track parameters and arguments correctly.

Dunno how I missed this issue before starting work on PR, but looks like thought in the same manner (PR attached).

**Comment by sebmck** [comment]
Closed via #701

**Comment by RReverser** [comment]
@sebmck I'd rather leave this opened as tracking issue until complete TCO can be done. Thoughts?

**Comment by sebmck** [comment]
@RReverser Ah yeah, good point.

**Comment by naomik** [comment]
Why is this closed again? It's been in "temporarily removed, going to be reimplemented" status for over a year. Will TCO ever see the light of day in Babel?

**Comment by isiahmeadows** [comment]
@naomik I believe the reason it was pulled was due to complexity concerns. but also pending [this proposal](https://github.com/tc39/proposal-ptc-syntax). The main issue is implementor reluctance (it breaks a lot of their previous assumptions about JS returning).

**Comment by naomik** [comment]
@isiahmeadows what a shame. Thanks for the link. I found it informative. I guess PureScript gets this right and will compile PTC to `while` loops – even in complex scenarios. Maybe all hope isn't lost for JavaScript after all...

**Comment by loganfsmyth** [comment]
I think part of the issue too is that Babel was only ever able to compile _some_ cases of TCO, which could also be confusing.
