### ISSUE TITLE
Clean up copytext

### ISSUE THREAD

**Issue by sebmck** [6to5/6to5#269]
- [ ] Add descriptions to module formatters
 - [ ] Make the docs more beginner friendly
 - [ ] Better transformer documentation - blacklist `useStrict` etc

**Comment by cvrebert** [comment]
It would also be helpful to actually define in brief prose somewhere what a "module formatter" and a "transformer" are.

**Comment by sebmck** [comment]
@cvrebert Done, sorry for the delay.

This issue is basically resolved with the new site.
