### ISSUE TITLE
Custom Class definition formatters

### ISSUE THREAD

**Issue by thejameskyle** [6to5/6to5#274]
While libraries migrate to ES6, many have implemented their own Classes that require some magic to work (especially with `Class.extend` methods).

It would be nice if there could be custom formatters for the class syntax, so you can author in the existing ES6 syntax, and compile to a library/framework compatible version.

```js
class MyModel extends Backbone.Model {
  initialize() {
    // ...
  }

  static method() {
    // ...
  }
}
```

```js
var MyModel = Backbone.Model.extend({
  initialize: function() {
    // ...
  }
}, {
  method: function() {
    // ...
  }
});
```

Obviously this doesn't match the spec, but might help people migrate without waiting for their libraries to be updated.

**Comment by sebmck** [comment]
Closing this. I've added optional transformers and if you'd like to request a specific class formatter then feel free to open an issue.
