### ISSUE TITLE
6to5/register caching?

### ISSUE THREAD

**Issue by drewhamlett** [6to5/6to5#300]
Is there some sort of caching that could be done on larger projects?  I'm using this 6to5 with Koa on Node 0.10.  I know I could use 0.11 but I was just seeing if this would work out a little better.  Right now the compile times are pretty low by using this.

```js
require('6to5/polyfill');
require('6to5/register')({
    ignore: false,
    whitelist: ['generators'],
    only: [
        /koa/,
        /koa-logger/,
        /koa-static/,
        /koa-compress/,
        /koa-ejs/,
        /koa-session/,
        /koa-csrf/,
        /koa-mount/,
        /koa-router/,
        /server/
    ]
});

var koa = require('koa');
```

But still restarting the server takes a decent amount of time(around 5 seconds).  I was wondering if there was  way to cache all the Koa modules that are not changing every time the server restarts?

**Comment by drewhamlett** [comment]
Hi thanks so much for this library.  In the newest version the require caching doesn't seem to be working anymore.

The ``` "6to5": {},``` in .roadrunner.json is not populated anymore.  Same project.  Just updated 6to5.

Version "6to5": "^3.3.4",

**Comment by sebmck** [comment]
Require caching is enabled by default and the file is saved to `path.join(os.tmpdir(), "6to5.json")`.

**Comment by Kagami** [comment]
@sebmck seems like there are some quirks in https://github.com/6to5/6to5/commit/e85c9b633a72afdc58c6ce3a483f8fcfe50caeca:
* Cache won't be saved at all unless I create file with `{}` at `/tmp/6to5.json`. Is it intentional?
* Is it ok to dump cache of all projects using 6to5 into single file? Increased time to read and parse, etc.

**Comment by sebmck** [comment]
@Kagami 

> Cache won't be saved at all unless I create file with {} at /tmp/6to5.json. Is it intentional?

Yeah, I actually just noticed that. I'll push out a fix.

> Is it ok to dump cache of all projects using 6to5 into single file? Increased time to read and parse, etc.

It should be. Overhead should be minimal. I was planning on making it so the cache only contained X files to avoid it growing in size but it hasn't been an issue so far. I'll get around to it when I can (pull requests appreciated!)

**Comment by sebmck** [comment]
Pushed out 3.3.11

**Comment by Kagami** [comment]
Cool!
