### ISSUE TITLE
Method syntax defines function with `name` property

### ISSUE THREAD

**Issue by hgl** [6to5/6to5#308]
This is very trivia, I'm not sure if you are interested in supporting:
```
let a = { next() {} };
a.next.name === "next" //true
```
So
```
let a = { next() {} };
```
should compiled to something like:
```
var _next = function() {};
_next.name = "next";
var  a = { next: _next };
```
P.S. can't use `function next() {}`, that would shadow outer `next`, unless there is no `next` in the body.

**Comment by eventualbuddha** [comment]
Given this input:

```js
var foo = 42;
var bar = {
  foo() { console.log(foo); }
};
foo = 21;
bar.foo() // would log 42 if we just renamed
```

[This is what esnext produces:](https://esnext.github.io/esnext/#var%20foo%20%3D%2042%3B%0Avar%20bar%20%3D%20%7B%0A%20%20foo()%20%7B%20console.log(foo)%3B%20%7D%0A%7D%3B%0Afoo%20%3D%2021%3B%0Abar.foo()%20%2F%2F%20would%20log%2042%20if%20we%20just%20renamed)

```js
var foo = 42;
var bar = {
  foo: function($__foo) {
    var $__wrapper = function foo() {
      return $__foo.apply(this, arguments);
    };

    $__wrapper.toString = function() {
      return $__foo.toString();
    };

    return $__wrapper;
  }(function() { console.log(foo); })
};
foo = 21;
bar.foo() // would log 42 if we just renamed
```

That satisfies the condition of `.name` being correct and `foo` inside the function referring to the correct scope. See the [implementation](https://github.com/vslinko/es6-object-concise/blob/94f9dbe0088c5f3ac3de90f82418fcac1f8eef7f/lib/visitor.js#L21). Note that it only creates this verbose code if you have a reference to an identifier with the same name as the enclosing concise function.

**Comment by hgl** [comment]
This is pretty clever.

I originally thought named function having a `.name` property was a new es6 feature, but look like browsers [have supported it for a while](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name). Only IE lacks it.
