### ISSUE TITLE
Add bower.json to point to 6to5/polyfill

### ISSUE THREAD

**Issue by DylanPiercey** [6to5/6to5#315]
The title says it all.

All of my client-side dependencies are currently in bower and it would be nice to have access to the polyfill as well.

**Comment by sebmck** [comment]
@thejameskyle Willing to support this without the use of a grunt task. Any suggestions?

**Comment by sebmck** [comment]
Not quite sure if this is something I'm willing to support and maintain. Closing this for now, feel free to hassle me if this is a compelling issue.

**Comment by simonzack** [comment]
+1 to this, it's rather strange to have my require.js reference `node_modules` for 6to5 and bower paths for everything else. For traceur there is a [traceur-runtime](https://github.com/jmcriffey/bower-traceur-runtime) package but I don't think it's official, so maybe 6to5 could take the same route and have someone else take up maintenance.

**Comment by sebmck** [comment]
@simonzack I push out releases too often for another person to maintain a separate package as it'd get outdated really quickly. The problem with distributing bower packages is that you need a separate repo unless you want to check in builds into your main repo which is gross. It'd complicate the publishing process significantly.

**Comment by simonzack** [comment]
Thanks for the explanation, that's annoying indeed. I'll just stick to `node_modules` then.

**Comment by dcunited08** [comment]
So we should copy browser-polyfill.js out to our scripts dir so we can use it?  A bower package would be nice.

**Comment by sebmck** [comment]
@dcunited08 Unfortunately. Bower package isn't practical for the reasons listed above.

**Comment by just-boris** [comment]
Since you hide `browser.js` into babel-core, this makes sense for me.
I am trying to use babel with [es6-module-loader](https://github.com/ModuleLoader/es6-module-loader), so I have to include browser version of babel from very long path `node_modules/babel/node_modules/babel-core/browser.js` and it is confusing me

**Comment by MetaMemoryT** [comment]
>  It'd also complicate the publishing process significantly.

I think it could be fully automated.

how about linking in a git submodule, to orchestrate the bower release, from the main repo?

Now that babel has its own github organization, 1 more repo shouldn't make things that much more complex, their is already multiple repos that must have separate releases.

**Comment by sebmck** [comment]
Yeah, it can be fully automated. The main reason is that I don't want to support it.

**Comment by MikeMcElroy** [comment]
Can we just find someone who does?

**Comment by kentongray** [comment]
some kind soul did this: https://github.com/grammarly/babel-polyfill

**Comment by sebmck** [comment]
Hasn't been updated since April and a lot of critical bugs have been fixed. Probably not the safest to use.

**Comment by alexking** [comment]
+1 for figuring out a way to make this work

**Comment by stefan-schweiger** [comment]
+1

**Comment by sebmck** [comment]
This is never going to happen, at least not officially.
