### ISSUE TITLE
Array comprehension and transducers

### ISSUE THREAD

**Issue by Kl0tl** [6to5/6to5#325]
Have you thought about using transducers to transpile array comprehension to es5 ?

It would require an external dependency (like https://github.com/jlongster/transducers.js, or https://github.com/cognitect-labs/transducers-js) but transducers are a more efficient way of composing transformations while retaining readability.

The difference is negligible for small arrays, but increase dramatically with the size of the array (http://jlongster.com/Transducers.js-Round-2-with-Benchmarks).

Taking your example:

```js
var seattlers = [for (c of customers) if (c.city == "Seattle") { name: c.name, age: c.age }];
```

With transducers it would become:

```js
var seattlers = into([], compose(filter(function (c) {
  return c.city === "Seattle";
}), map(function (c) {
  return { name: c.name, age: c.age };
})), customers);
```

Instead of:

```js
var seattlers = _toArray(customers).filter(function (c) {
  return c.city == "Seattle";
}).map(function (c) {
  return { name: c.name, age: c.age };
});
```

**Comment by sebmck** [comment]
I'm open to adding an optional transformer to 6to5 that turns array comprehensions into transducers. Which library is the best/most used?

**Comment by zloirock** [comment]
I don't think this a good idea. Transducers === lazy evaluation, it's good for map -> filter, but comprehensions are filter -> map. Be better revert to simple loop, it will be faster and fix [this issue](https://github.com/6to5/6to5/issues/252).

**Comment by sebmck** [comment]
@zloirock This would be an optional transformer.

**Comment by zloirock** [comment]
@sebmck Yes, but I do not see the benefits.

**Comment by sebmck** [comment]
@zloirock Yeah I guess you're right. I'm more inclined to just revert to a simple loop since right now they're only used if you use array comprehensions with more than one block.

**Comment by Kl0tl** [comment]
I didn’t knew about yielding inside array comprehension, simpler to revert to a loop in this case. The only advantage of transducers over native loops is the improved readability but the latter will always perform better. Native loops seem the best fit.

@zloirock Transducers are eager and they are particularly good in the `filter -> map` scenario.
