### ISSUE TITLE
Playground enhancements

### ISSUE THREAD

**Issue by zloirock** [6to5/6to5#353]
**[Object getter memoization](https://6to5.org/playground.html#object-getter-memoization)**
I think, something like this be better than current:
```javascript
var foo = {
  memo bar(){
    var a = Math.random()
      , b = 42;
    return a + b;
  }
}
// =>
var foo = Object.defineProperties({}, {
  bar: {
    enumerable: true,
    configurable: true,
    get: function(){
      var a = Math.random()
        , b = 42;
      return Object.defineProperty(this, 'bar', {
        enumerable: true,
        configurable: true,
        writable: true,
        value: a + b
      }).bar;
    }
  }
});
```
**[`this` shorthand](https://6to5.org/playground.html#this-shorthand) & [method binding](https://6to5.org/playground.html#method-binding)**
```javascript
// Standalone @ 
function f(){return @} // now throwing error
// be better:
function f(){return @}
// =>
function f(){return this}

// method binding from @
fn(@#method) // now invalid code
// be better:
fn(@#method)
// =>
fn(this.method.bind(this))
```

**Comment by GabrielRatener** [comment]
Sorry to interject, but I am a big fan of the `@` feature, how do I enable this in Babel as it currently stands? I cannot find any documentation on it.

**Comment by sebmck** [comment]
@GabrielRatener Why did you ask in an unrelated issue?

In the future please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">slack channel</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Relevant docs are [here](http://babeljs.io/docs/usage/experimental/). Thanks!

**Comment by GabrielRatener** [comment]
@sebmck The `@` feature not working seems to me highly related to this issue. I am not in the position to determine whether the lack of usability of this feature is a bug, I would hope you would know. Should I open a new issue?

**Comment by sebmck** [comment]
No. It is indeed supported and is not enabled by default. See the linked documentation on how to enable it.
