### ISSUE TITLE
Computed properties should use Object.defineProperty

### ISSUE THREAD

**Issue by DmitrySoshnikov** [6to5/6to5#357]
As described in [this issue](https://github.com/DmitrySoshnikov/es6-computed-properties/issues/3), computed properties should compile to `Object.defineProperty` instead of simple assignment expressions -- in order to correctly support ES5 inherited accessor properties.

**Comment by chicoxyzzy** [comment]
:+1: 
this needs to be fixed

**Comment by sebmck** [comment]
I'm going to add an edgecase for computed `Symbol` member expressions due to the limitations of symbol polyfills, otherwise properties will use `Object.defineProperty`.

**Comment by sebmck** [comment]
Thanks! Fixed as of 2.3.1
