### ISSUE TITLE
class extends null throwing error

### ISSUE THREAD

**Issue by thejameskyle** [6to5/6to5#361]
[Unsupported](https://6to5.org/repl.html#?code=class%20Foo%20extends%20null%20%7B%7D%0Avar%20foo%20%3D%20new%20Foo()%3B%0A%0Aconsole.log(%0A%20%20!(foo%20instanceof%20Object)%0A%20%20%26%26%20Function.prototype.isPrototypeOf(Foo)%0A%20%20%26%26%20Object.getPrototypeOf(Foo.prototype)%20%3D%3D%3D%20null%0A)%3B&experimental=true&playground=true&evaluate=true) - [Supported](https://6to5.org/repl.html#?code=var%20Bar%20%3D%20null%3B%0Aclass%20Foo%20extends%20Bar%20%7B%7D%0Avar%20foo%20%3D%20new%20Foo()%3B%0A%0Aconsole.log(%0A%20%20!(foo%20instanceof%20Object)%0A%20%20%26%26%20Function.prototype.isPrototypeOf(Foo)%0A%20%20%26%26%20Object.getPrototypeOf(Foo.prototype)%20%3D%3D%3D%20null%0A)%3B&experimental=true&playground=true&evaluate=true)

```js
class Foo extends null {}
```
```js
SyntaxError: repl: Assigning to rvalue (1:18)
> 1  | class Foo extends null {}
     |                  ^
```

Broke somewhere in between 2.2 and 2.4 I believe.

**Comment by sebmck** [comment]
marijnh/acorn#185
