### ISSUE TITLE
Missing regeneratorRuntime in REPL

### ISSUE THREAD

**Issue by UltCombo** [6to5/6to5#363]
Test case: try to run an async function in the [REPL](https://6to5.org/repl.html#?code=(async%20function()%20%7B%0A%20%20await%201%3B%0A%7D)()%3B%0A&experimental=true&playground=true&evaluate=true)

Throws:

> Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by sebmck** [comment]
Forgot to include the polyfill in the REPL. Good catch, thanks!
