### ISSUE TITLE
Use of Object.assign() breaks in most browsers

### ISSUE THREAD

**Issue by davidtheclark** [6to5/6to5#368]
It looks like this commit https://github.com/6to5/6to5/commit/52e23473ed98c47a2c9c4f1b87d7ad0c311fb740 added `Object.assign()` to the code --- but almost no browsers support that: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility. Updating to the latest version therefore broke things for me.

**Comment by frankcash** [comment]
Object.assign() is an ES6 "experimental" feature 

>This is an experimental technology, part of the Harmony (ECMAScript 6) proposal.
Because this technology's specification has not stabilized, check the compatibility table for usage in various browsers. Also note that the syntax and behavior of an experimental technology is subject to change in future version of browsers as the spec changes.

**Comment by zloirock** [comment]
[Caveats](https://6to5.org/caveats.html).

**Comment by davidtheclark** [comment]
Yes @zloirock , but I think the problem is that the use of `Object.assign()` in the commit that broke things for me is being used by modules, which is not experimental.

Unless of course I'm missing something -- did this update not break modules for other people?

**Comment by zloirock** [comment]
@davidtheclark Most of the 6to5 features required standard library polyfill. I do not see a problem here. My acquaintance with 6to5 began with the reading of it. What did you expect? :) In a pinch, you can write a stub for `Object.assign` in pair of lines.

**Comment by davidtheclark** [comment]
@zloirock My strong impression was that the polyfill is totally optional, required for certain features only which are mentioned in the caveats. If that's not the case, documentation could be clarified. I have not included the polyfill so far and this is the first problem I have run into.

**Comment by sebmck** [comment]
@davidtheclark You're right, I forgot to add it to the documentation. 6to5 uses ES5 syntax with various ES6 methods for usability reasons. There's no other way to do a non-function default export that has another export without using `Object.assign`. See #356, which is what introduced this behaviour.

As of 2.4.6 you can use the optional transformer `coreAliasing` to alias ES6 methods to their `core-js` equivalent. All this requires is that you:

```sh
$ npm install core-js --save
```

and to add the following option to your 6to5 command:

```javascript
to5.transform("code", { optional: ["coreAliasing"] });
```

```sh
$ 6to5 --optional coreAliasing script.js
```

Apologies for the incorrect documentation, we're currently in the process of launching a new site which has made things a bit difficult.

**Comment by davidtheclark** [comment]
Thanks! That sorts out why the latest update broke my build.

**Comment by davidtheclark** [comment]
Should't this be classified as a semver **breaking change** -- since it broke code that previously worked?

**Comment by sebmck** [comment]
@davidtheclark What code did you have before that was working? AFAIK, before exporting a non-function default with additional exports wouldn't work at all.

**Comment by sebmck** [comment]
As of 2.7.2, `Object.assign` is no longer used and instead a simple inline helper.
