### ISSUE TITLE
Make polyfill optional in 6to5/register

### ISSUE THREAD

**Issue by vdemedes** [6to5/6to5#371]
I am using latest unstable Node.js (v0.11.14), which has a native WeakMap implementation, (and some other ES6 features built-in) but polyfill that is included automatically (core.js) replaces that implementation with its own. It would be very good to make polyfill optional.

**Comment by sebmck** [comment]
What do you mean? The polyfill is optional?

**Comment by timoxley** [comment]
I don't believe there's a way to run `6to5-node` without also loading the polyfill.

`6to5-node` should probably accept the same arguments as `6to5` itself.
```
6to5-node --whitelist arrowFunctions
```

**Comment by timoxley** [comment]
though my above suggestion does pollute the "it's just node" flags on `6to5-node`. Reading config from .6to5rc file ala https://github.com/6to5/6to5/issues/351 would get around that

**Comment by sebmck** [comment]
There's no way to do this without breaking backwards compatibility unless I add an environment variable or some other way to tell `6to5/register` to not include the polyfill.

**Comment by vdemedes** [comment]
@sebmck I mean, it would be *awesome* to have an option, whether to include a polyfill or not. I opened this issue, because of that - https://github.com/zloirock/core-js/issues/8. 

P.S. @timoxley has also suggested a great improvement.

**Comment by sebmck** [comment]
Except the polyfill is required in order for everything to work. 6to5 uses `Array.from` for example in [quite a few transformers](https://6to5.org/caveats.html) and it's not supported in even the latest unstable node.

```sh
$ node -v
v0.11.14
$ node --harmony
> Array.from
undefined
```

This will cause many things to fall flat on their face and you'd have to use some sort of polyfill one way or another.

**Comment by sebmck** [comment]
`6to5/register` is supposed to replicate an entire ES6 environment which is why the polyfill is required in the first place. I'm open to adding an option to make it optional but with the current implementation there's no way to without breaking backwards compatibility. To me it seems like the real solution is for core-js to not override defaults.

/cc @zloirock

**Comment by vdemedes** [comment]
`To me it seems like the real solution is for core-js to not override defaults.` exactly, I opened an issue on core-js repository mentioning that. But until then, a simple option (like `polyfill: false`) would solve this problem. And as for functions that 6to5 needs, I think the right thing would be to copy implementations of functions you need, like `Array.from` and not force loading a polyfill, which **replaces** native implementation (no idea why would some library do that, I assume it's just a bug).

**Comment by sebmck** [comment]
The polyfill is required on `require("6to5/register");` which makes it impossible to disable by invoking the exported config function.

**Comment by vdemedes** [comment]
Alright, we'll wait for core-js to fix this issue then.

**Comment by sebmck** [comment]
`core-js` actually tests the current environment for full spec-compliance of a feature as it's existence doesn't guarantee it's correctness.

```javascript
$ node --harmony
> require("core-js");
...
> WeakMap.prototype.get + ""
'function get() { [native code] }'
```

Looks like it just overrides the `WeakMap` constructor and retains it's `prototype`.

**Comment by vdemedes** [comment]
Try:

```javascript
var map = new WeakMap;
map.set('invalid_key', 123);
```

Error will be thrown and in the stack trace you'll see that it points to core-js/shim.

**Comment by sebmck** [comment]
```javascript
$ node --harmony
> require("core-js");
> WeakMap.prototype.set + ""
'function (a, b){\r\n        var result = method.call(this, a === 0 ? 0 : a, b);\r\n        return chain ? this : result;\r\n      }'
> var map = new WeakMap;
undefined
> map.set('invalid_key', 123);
TypeError: Invalid value used as weak map key
    at WeakMap.set (native)
```

It wraps the native method for correctness.

**Comment by vdemedes** [comment]
Oooh damn, it's my fault, sorry Sebastian. What a shame. Thank you for explaining this and thank you for 6to5!

**Comment by sebmck** [comment]
@vdemedes It's all good! Better to be safe then sorry. I didn't realise how intricately `core-js` checks were, awesome work @zloirock.

**Comment by zloirock** [comment]
Core.js uses native `WeakMap`, if it exists, just fixes constructor for init from iterable and `.set` for chaining.

```javascript
var a = {}, b = {};

new WeakMap([[a, 1], [b, 2]]).has(a);     // => false
new WeakMap().set(a, 1).set(b, 2).has(a); // TypeError: Cannot call method 'set' of undefined

require('core-js'); // WeakMap still returns native weakmap

new WeakMap([[a, 1], [b, 2]]).has(a);     // => true
new WeakMap().set(a, 1).set(b, 2).has(a); // => true
```

About "intricately `core-js` checks" - this wrap uses also for fix converting negative-zero-key to positive zero for `Map` and `Set`.

I can add the option to not fix buggy implementations, but don't think it is necessary.
