### ISSUE TITLE
Defaults not handled properly in UMD result?

### ISSUE THREAD

**Issue by trusktr** [6to5/6to5#374]
When I compile an ES6 module that has a default export to CJS, I see this at the bottom:

```js
exports.Plane = Plane;
exports["default"] = Plane;
module.exports = Object.assign(exports["default"], exports);
```

But when I compile the same ES6 module to UMD, that last line is missing:

```js
exports.Plane = Plane;
exports["default"] = Plane;
```

Is this per design?

**Comment by sebmck** [comment]
Yeah it is. Only the default `common` module formatter supports module export interopability.

**Comment by trusktr** [comment]
So basically we can't use ES6 default exports when building to UMD?

**Comment by sebmck** [comment]
@trusktr Well you can, you'll just have to use `.default` outside of 6to5. Coincidently @kentcdoods just opened 6to5/6to5#375 with the exact same issue and I can hopefully implement.

**Comment by trusktr** [comment]
@sebmck Oh ok. If somehow it could be required without `.default` in UMD, that'd be awesome.
