### ISSUE TITLE
Comment between expressions triggers parentheses insertion

### ISSUE THREAD

**Issue by brycehanscomb** [6to5/6to5#376]
If I call 6to5 on this code:

    $q
        .when().
        //
        then();

The transpiler outputs this:

    "use strict";
    $q.when().(
      //
      then
    )();

Which is equivalent to this:

    "use strict";
    $q.when().(then)();

Which is invalid JS, and throws a ParseError.

**Comment by sebmck** [comment]
Looks like a regression in the #349 fix.
