### ISSUE TITLE
Object.assign is undefined.

### ISSUE THREAD

**Issue by trusktr** [6to5/6to5#377]
In the line

```js
module.exports = Object.assign(exports["default"], exports);
```

of a module converted to CJS, `Object.assign` causes an error. Most browsers (f.e. Chrome) don't support this yet. Can you guys please replace this with something that works? Thanks!

**Comment by sebmck** [comment]
It's a documented [caveat](https://6to5.org/caveats.html). You can setup `core-js` aliasing that'll alias these kind of methods,

#### Install core-js

```sh
$ npm install --save core-js
```

#### Configure the optional transformer.

Via the CLI:

```sh
$ 6to5 --optional coreAliasing script.js
```

Via the Node API:

```javascript
require("6to5").transform("code", { optional: ["coreAliasing"] });
```

**Comment by trusktr** [comment]
Why make it optional? Why not make it a dependency of 6to5?

**Comment by sebmck** [comment]
@trusktr Because then I'm forcing users into a polyfill and the aliasing isn't solidified behaviour yet. Not currently planning on having it default in 2.x but 3.x is a possibility.

**Comment by trusktr** [comment]
Why not just use something other than Object.assign so it just works out of the box? Maybe use [extend](https://www.npmjs.com/package/extend) or something?

**Comment by sebmck** [comment]
@trusktr How would something like [extend](https://www.npmjs.com/package/extend) be incorporated? Adding it as an import and then using it is functionally equivalent to the `coreAliasing` behaviour.

**Comment by trusktr** [comment]
Well the thing is that if it's a dependency of 6to5, then users of 6to5 don't have to worry about it. :)

**Comment by trusktr** [comment]
For example, I'm here simply because Object.assign threw an error. But if `extend` or something was used, then it would have just worked, and it's not a polyfill.

**Comment by sebmck** [comment]
@trusktr I assume you're referring to adding `extend` as a dependency to the 6to5 `package.json`?

**Comment by trusktr** [comment]
Yeah, exactly. And replacing Object.assign with it, or something similar.

**Comment by kentcdodds** [comment]
Sorry to interrupt, but I'm trying to use the 6to5-loader for webpack and I'm not sure of the easiest way to resolve this issue. Looks like 6to5-loader allows you to pass options to 6to5, however, `coreAliasing` is not one of [them](https://6to5.org/usage.html#options). What would you recommend I do in this case?

Note, I'm mostly doing this because #375 is not yet supported.

**Comment by sebmck** [comment]
@trusktr That's never going to work because **none** of the dependencies inside of `package.json` are ever going to be resolved outside of the folder that `package.json` is in.

**Comment by trusktr** [comment]
@sebmck Well, then just copy/paste the code into 6to5? It's MIT.

**Comment by sebmck** [comment]
@kentcdodds Optional transformers currently aren't documented because we're currently in the process of developing a new site and thus new documentation. You'd just pass add the option `{ optional: ["coreAliasing"] }` to your webpack 6to5 config.

**Comment by sebmck** [comment]
@trusktr It'd have to be inlined and that's a significant amount of inline code which is exactly what 6to5 doesn't want.

**Comment by kentcdodds** [comment]
Thanks :D

Back on subject. As a new user, I think this issue is a bit of a barrier to entry and would make getting started with 6to5 much simpler. However it's resolved, I think it would be nice if it were :-)

**Comment by trusktr** [comment]
@sebmck Agree with @kentcdodds, some extra code would be better if it just works. Most of our computer can handle the extra file size. :D

**Comment by trusktr** [comment]
`extend` is only 80 sparse lines, unminified.

**Comment by sebmck** [comment]
@trusktr 80 lines is extremely significant since none of the current inline helpers go over 10. Adding an extra 2KB to someones codebase isn't great, especially since it adds up. 6to5 has a clearly dictated [philosophy](https://6to5.org/differences.html), key part here is:

> Sometimes there are little inline functions that 6to5 needs. These are placed at the top of your file much like coffee-script does. If these bother you then you can use the optional runtime. **We promise that these inline functions will never be significant and will always be used as little as possible.**

I've provided ways to get around this. You can either use the [polyfill](https://6to5.org/polyfill.html) or the optional [coreAliasing](https://github.com/6to5/6to5/issues/377#issuecomment-68622287) transformer.

**Comment by trusktr** [comment]
@sebmck Ok, I can dig it. Regardless, thanks for giving us the awesome 6to5! :)

**Comment by timoxley** [comment]
IMO, when it's stable, `coreAliasing` should be on by default. i.e. lean towards "it works for beginners by default". Opt-out if you want to use a different polyfill or native methods.

**Comment by sebmck** [comment]
@timoxley Yeah definently. I need to do some more testing of it and document the behaviour extensively which is why I haven't been pushing it a lot. It removes the issue of a global polluting polyfill which is **massive** for library authors who want to write in ES6.

**Comment by trusktr** [comment]
Plus, it's only needed for default exports anyways, right? Some people might not use default exports.

**Comment by sebmck** [comment]
@trusktr Is what specifically needed for default exports?

**Comment by trusktr** [comment]
Object.assign? It seems like the line

```js
module.exports = Object.assign(exports["default"], exports);
```

is handling the default export of an ES6 module.

Also, I just tried the coreAliasing, but I'm still getting the undefined error. The line looks like this:

```js
module.exports = _core.Object.assign(exports["default"], exports);
                                                            ^ undefined
```

**Comment by sebmck** [comment]
@trusktr `Object.assign` is only needed for non-function default exports, yeah. But there are other ES6 methods used in 6to5 that are documented on the [caveats](https://6to5.org/caveats.html) page. Can you provide the output that you're trying to compile? Makes it more clear what's going on.

**Comment by trusktr** [comment]
Sure. I have this ES6 module:

```js
/*
 * LICENSE
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

import Surface from 'famous/core/Surface';

import Molecule from './Molecule';

export class Plane extends Molecule {
    constructor(initialOptions) {
        super(initialOptions);

        this.surface = new Surface(this.options);
        this.add(this.surface);
        this.surface.pipe(this._.handler);
    }

    // Surface interface
    getContent() {
        var args = Array.prototype.splice.call(arguments, 0);
        return this.surface.getContent.apply(this.surface, args);
    }
    setContent() {
        var args = Array.prototype.splice.call(arguments, 0);
        return this.surface.setContent.apply(this.surface, args);
    }
}
export default Plane;
```

which compiles to this:

```js
"use strict";

var _inherits = function (child, parent) {
  child.prototype = Object.create(parent && parent.prototype, {
    constructor: {
      value: child,
      enumerable: false,
      writable: true,
      configurable: true
    }
  });
  if (parent) child.__proto__ = parent;
};

var _interopRequire = function (obj) {
  return obj && (obj["default"] || obj);
};

var _core = _interopRequire(require("core-js/library"));

/*
 * LICENSE
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

var Surface = _interopRequire(require("famous/core/Surface"));

var Molecule = _interopRequire(require("./Molecule"));

var Plane = (function () {
  var _Molecule = Molecule;
  var Plane = function Plane(initialOptions) {
    _Molecule.call(this, initialOptions);

    this.surface = new Surface(this.options);
    this.add(this.surface);
    this.surface.pipe(this._.handler);
  };

  _inherits(Plane, _Molecule);

  // Surface interface
  Plane.prototype.getContent = function () {
    var args = Array.prototype.splice.call(arguments, 0);
    return this.surface.getContent.apply(this.surface, args);
  };

  Plane.prototype.setContent = function () {
    var args = Array.prototype.splice.call(arguments, 0);
    return this.surface.setContent.apply(this.surface, args);
  };

  return Plane;
})();

exports.Plane = Plane;
exports["default"] = Plane;
module.exports = _core.Object.assign(exports["default"], exports);
```

**Comment by trusktr** [comment]
The error is in that last line.

**Comment by sebmck** [comment]
@trusktr Any reason you just aren't using `export default class Plane extends Molecule { ... }`? It'd output to exactly what you want without using `Object.assign`. I'm not sure why that's throwing a `ReferenceError` anyway since all of the variables used should be defined, can you post the stacktrace?

**Comment by trusktr** [comment]
The trace looks like this:

![](http://i.imgur.com/7GvH0iH.png)

**Comment by trusktr** [comment]
My entry point looks like this

```js
var style = require('famous/core/famous.css') // needed by famous

var Plane = require('infamous/Plane')
console.log(Plane)
var contextWithPerspective = require('infamous/utils').contextWithPerspective

var ctx = contextWithPerspective(1000)

var square = new Plane({
    size: [200,200],
    content: 'Hello.',
    properties: {
        backfaceVisibility: 'visible',
        background: 'pink',
        padding: '5px'
    }
})

ctx.add(square)

square.transform.setRotate([0,2*Math.PI,0], {duration: 5000, curve: 'easeInOut'})
```

It depends on infamous, which depends on famous. Infamous is gets compiled with 6to5 when you npm install it. Then the entry point above is requiring those compiled files.

I'm running 

```
browserify src/app.js -o public/app.js
```

which results in this: http://hastebin.com/ahopufuwac.js

**Comment by trusktr** [comment]
The reason I decided to use both a named and default export is because the user can use the library whichever way he chooses, and it'll just work. F.e., both imports work:

```js
import Plane from 'infamous/Plane'
import {Plane} from 'infamous/Plane'
```

**Comment by trusktr** [comment]
I'm using 6to5 just to compile my package for people who use browserify, etc, but in my own dev environment I just use `es6-module-loader`.

**Comment by sebmck** [comment]
@trusktr Looks like an issue with `core-js` incorrectly detecting the current environment and so it doesn't export it. @zloirock You should probably be checking the existence of `module` instead of `process`.

**Comment by kentcdodds** [comment]
Just throwing this out there as a thought and a decision I'm making for my own project. Maybe it's helpful. I'm writing a small, simple library. I don't want to have to include a polyfill for `Object.assign` for something so small, partially because it'll likely be included into a project that has a polyfill for `Object.assign` already which would lead to my included polyfill being unnecessary. So I've decided to simply include in the readme that a polyfill is required for this library to work. I don't think that is unreasonable.

**Comment by trusktr** [comment]
Beautiful, it all works with Object.assign now. Thanks @sebmck @zloirock.

**Comment by sebmck** [comment]
As of 2.7.2, `Object.assign` is no longer used and instead a simple inline helper is.

**Comment by trusktr** [comment]
Weird, how did my comment end up above yours? It was in reply.

**Comment by chicoxyzzy** [comment]
How can I add { optional: ["coreAliasing"] } option to webpack config? As I see [here](https://github.com/6to5/6to5-loader/blob/master/index.js#L11) it can be passed via query but I still don't understand how to do that.
my webpack config:
```javascript
var webpack = require('webpack');

module.exports = {
  entry: [
    './src/index'
  ],
  output: {
    path: __dirname + '/dist',
    filename: 'bundle.js'
  },
  resolve: {
    extensions: ['', '.js']
  },
  module: {
    loaders: [
      { test: /\.js$/, exclude: '/node-modules/', loaders: ['6to5-loader'] }
    ]
  }
};
```

**Comment by sebmck** [comment]
@chicoxyzzy Just realised that it's not currently possible, I've pushed out a new version (2.11.3) that you can use with:

```javascript
var webpack = require('webpack');

module.exports = {
  entry: [
    './src/index'
  ],
  output: {
    path: __dirname + '/dist',
    filename: 'bundle.js'
  },
  resolve: {
    extensions: ['', '.js']
  },
  module: {
    loaders: [
      { test: /\.js$/, exclude: '/node-modules/', loaders: '6to5-loader?optional=coreAliasing' }
    ]
  }
};
```

You'll need to reinstall `6to5-loader` to get this behaviour though.

**Comment by chicoxyzzy** [comment]
Now I have another issue. Building [my project](https://github.com/chicoxyzzy/real-world-react) with webpack causes 
```
ERROR in ./~/core-js/library.js
Module parse failed: /PATH_TO_MY_TEST_APP/node_modules/6to5-loader/index.js?optional=coreAliasing!/PATH_TO_MY_TEST_APP/node_modules/core-js/library.js Line 1149: Unexpected token .
You may need an appropriate loader to handle this file type.
|   // ES6 promises shim
|   // Based on https://github.com/getify/native-promise-only/
|   !(function (_core.Promise, test) {
|     isFunction(_core.Promise) && isFunction(_core.Promise.resolve) && _core.Promise.resolve(test = new _core.Promise(function () {})) == test || (function (asap, DEF) {
|       function isThenable(o) {
 @ ./src/index.js 7:28-54
```
don't sure if it `6to5-loader`'s or `core-js`'s issue

**Comment by sebmck** [comment]
@chicoxyzzy Looks like webpack uses a bad parser or something since that should parse.

**Comment by roman01la** [comment]
I'm using `6to5-loader` with `coreAliasing` and getting the following error in browser's console:
```
Uncaught TypeError: Cannot read property 'TypeError' of undefined
```

It's referencing to `TypeError = _core.global.TypeError` inside of `core-js` module. `_core` object appears to be empty.

**Comment by sebmck** [comment]
@roman01la Can you provide that code that is actually erroring?

**Comment by roman01la** [comment]
@sebmck I've also tried @chicoxyzzy's [setup](https://github.com/chicoxyzzy/real-world-react/tree/webpack), which is identical to mine — same error after compilation.

**Comment by sebmck** [comment]
@roman01la I can't debug without the original code.

**Comment by roman01la** [comment]
@sebmck Take [this branch](https://github.com/chicoxyzzy/real-world-react/tree/webpack)

**Comment by sebmck** [comment]
@roman01la I'm not familiar with webpack. I need either the specific code that's being transformed incorrectly or some instructions.

**Comment by roman01la** [comment]
@sebmck Checked something, looks like 6to5 output is ok, probably the issue is on webpack's side.

**Comment by sebmck** [comment]
@roman01la Try reinstalling `6to5-loader`, there was a recent change were only [these](https://github.com/6to5/6to5/blob/master/lib/6to5/transformation/transformers/optional-core-aliasing.js#L11) constructor are aliased which is most likely related.

**Comment by roman01la** [comment]
@sebmck Didn't help.

**Comment by chicoxyzzy** [comment]
Yep also get this issue. 

`Uncaught TypeError: Cannot read property 'TypeError' of undefined`
in 
```
	  // Aliases global objects and prototypes
	  ,
	      Function = global[FUNCTION],
	      Object = global[OBJECT],
	      Array = global[ARRAY],
	      String = global[STRING],
	      Number = global[NUMBER],
	      RegExp = global[REGEXP],
	      Date = global[DATE],
	      Map = global[MAP],
	      Set = global[SET],
	      WeakMap = global[WEAKMAP],
	      WeakSet = global[WEAKSET],
	      Symbol = global[SYMBOL],
	      Math = global[MATH],
	      TypeError = _core.global.TypeError,
	      setTimeout = _core.global.setTimeout,
	      setImmediate = _core.global.setImmediate,
	      clearImmediate = _core.global.clearImmediate,
	      process = global[PROCESS],
	      nextTick = process && process.nextTick,
	      document = global.document,
	      html = document && document.documentElement,
	      navigator = global.navigator,
	      define = global.define,
	      ArrayProto = Array[PROTOTYPE],
	      ObjectProto = Object[PROTOTYPE],
	      FunctionProto = Function[PROTOTYPE],
	      Infinity = 1 / 0,
	      DOT = ".";
```

source code (common.js from `core-js`):
```
  // Aliases global objects and prototypes
  , Function        = global[FUNCTION]
  , Object          = global[OBJECT]
  , Array           = global[ARRAY]
  , String          = global[STRING]
  , Number          = global[NUMBER]
  , RegExp          = global[REGEXP]
  , Date            = global[DATE]
  , Map             = global[MAP]
  , Set             = global[SET]
  , WeakMap         = global[WEAKMAP]
  , WeakSet         = global[WEAKSET]
  , Symbol          = global[SYMBOL]
  , Math            = global[MATH]
  , TypeError       = global.TypeError
  , setTimeout      = global.setTimeout
  , setImmediate    = global.setImmediate
  , clearImmediate  = global.clearImmediate
  , process         = global[PROCESS]
  , nextTick        = process && process.nextTick
  , document        = global.document
  , html            = document && document.documentElement
  , navigator       = global.navigator
  , define          = global.define
  , ArrayProto      = Array[PROTOTYPE]
  , ObjectProto     = Object[PROTOTYPE]
  , FunctionProto   = Function[PROTOTYPE]
  , Infinity        = 1 / 0
  , DOT             = '.';
```

**Comment by chicoxyzzy** [comment]
oh I see [there was bug](https://github.com/6to5/6to5-loader/issues/15#issuecomment-70343657) in webpack's config file

**Comment by fatso83** [comment]
For anyone else ending up here, the transform has been renamed to `runtime`. [Example config](http://stackoverflow.com/a/28947180/200987)

**Comment by mciparelli** [comment]
How are you supposed to use such transform with `babel-node`?

**Comment by sebmck** [comment]
@mciparelli You already can.

**Comment by mciparelli** [comment]
For some reason, this works for me:
```
babel-node --experimental server/index.js
```

but this one does not

```
babel-node --optional runtime --experimental server/index.js
```

**Comment by sebmck** [comment]
@mciparelli You aren't meant to be using the `runtime` transformer with `babel-node`.

**Comment by mciparelli** [comment]
So if I want `Object.assign` I need to use `babel` alone instead of `babel-node`?

**Comment by sebmck** [comment]
@mciparelli No, if you want to use `Object.assign` you can just use `babel-node` as demonstrated in my comment [here](https://github.com/babel/babel/issues/377#issuecomment-79128223).

**Comment by chrisberragan** [comment]
Note to anyone coming to this thread using babel-core ~5.0 (and babel-loader ~5.0): It looks like polyfill can now be added with optional: ["runtime"] instead of coreAliasing, so webpack loader config now looks like:

            {
                test: /\.es6.js$/,
                exclude: /node_modules/,
                loader: "babel-loader?optional=runtime"
            }

Note that this also requires installing babel-runtime

Reference: http://babeljs.io/docs/usage/runtime/

**Comment by sebmck** [comment]
Also as of Babel 5.0.0 there's a plugin framework so you can also use [bable-plugin-object-assign](https://github.com/JedWatson/babel-plugin-object-assign).

**Comment by chrisberragan** [comment]
@sebmck Thanks for the tip!

**Comment by gniquil** [comment]
For working with Webpack, it seems to work if require from babel-core

```javascript
require('babel-core/polyfill');
```

**Comment by bucaran** [comment]
How does `package.json` should look like for this to work? I actually want everything to work so here is my setup, which is unfortunately not working well (`Object.assing` is not found).
```json
  "browserify": {
    "transform": [["babelify", { "optional": ["runtime"] }]]
  },
```

**Comment by sebmck** [comment]
That should work. I noticed you misspelt `Object.assign` so make sure that spelling mistake isn't also in your code.

**Comment by bucaran** [comment]
@sebmck Nice catch. That was not the problem though. I was not requiring

```js
require("babel-core/polyfill")
```

**Comment by bucaran** [comment]
@sebmck 

Is there anyway I can avoid 

```js
require("babel-core/polyfill")
```

The only reason I am doing this is because I want to use `Object.assign` so that I can ditch `underscore`.

**Comment by sebmck** [comment]
Yes, by using the optional `runtime` transformer that was discussed in this issue.

**Comment by bucaran** [comment]
I read the whole issue, but it is extremely confusing, unless you are @sebmck yourself of course :smile:

**Comment by sebmck** [comment]
Docs on using the runtime are [here](http://babeljs.io/docs/usage/runtime/). If you run into any issues then the <a href="https://gitter.im/babel/babel">gitter room</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a> should be able to help.

**Comment by bucaran** [comment]
@sebmck I am already used to `--optional runtime ...` when using babel directly, but in this case I am using `babelify` and the `--optional runtime ...` part is not working. :disappointed:

**Comment by sebmck** [comment]
@bucaran Try the gitter room then, there's no reason the `package.json` snippet shouldn't work so it's likely a browserify config issue.

> BTW, how should I translate `require("babel-core/polyfill")` to using `imports`?

```javascript
import "babel-core/polyfill";
```

**Comment by bucaran** [comment]
What is the difference between these two modules and which ones do I need?

Setting up Babel to basically work is simple enough and that is probably all you need in more cases. I have already published a few ES6 only libraries to npm, but when I tried to do something a little bit more complicated I find myself with a very hard to understand documentation:

Polyfill
Require Hook
Runtime

**Comment by sebmck** [comment]
@bucaran As I've said, please use the gitter room or StackOverflow. I've been reinforcing this a lot lately since I just do not have the time to provide support and maintain Babel core. I understand the more advanced docs are poor and I wish I had more time to work on them but providing support also cuts into my available time significantly which means I have less time to work on docs and core.

**Comment by bucaran** [comment]
@sebmck Fair enough. I should try to help instead. Thanks for letting me know the situation more clearly.
