### ISSUE TITLE
Non-top-level imports incorrectly allowed

### ISSUE THREAD

**Issue by cvrebert** [6to5/6to5#380]
6to5@2.4.10 happily translates the following input without any error/warning/compliant:
```js
try {
    import foo from "foo";
}
catch (importErr) {
    alert("Oh noes!");
}
```
However, FWICT, the ES6 spec (very annoyingly!) only allows `import` as a top-level statement in a module, which means that 6to5 isn't being spec-compliant here.

**Comment by sebmck** [comment]
See marijnh/acorn#174 and 6to5/acorn-6to5#8. This is likely going to change in 3.x but it can't be now since it's a breaking change.
