### ISSUE TITLE
Some strange transformations occur

### ISSUE THREAD

**Issue by yuchi** [6to5/6to5#383]
```es
x = {}
[ 1, 2, 3 ]
```

becomes

```js
x = {}[(1, 2, 3)];
```

**Comment by yuchi** [comment]
But

```es
x = {}; // <------ semicolon here
[ 1, 2, 3 ]
```

correctly becomes

```js
x = {};
[1, 2, 3];
```

**Comment by sebmck** [comment]
This is correct behaviour. You aren't using semicolons. `[1, 2, 3]` is being interpreted as a member expression of `{}`.

**Comment by yuchi** [comment]
I feel so silly sometimes.

**Comment by timoxley** [comment]
@yuchi remember: only times you need semicolons is when you start a line with `(` or `[` and in `for` loops. Remember these rules and your code will happily run without adding thousands of unnecessary characters.

**Comment by yuchi** [comment]
Thanks @timoxley! I'll better implement some rule of thumb in my head before I do something silly again :P
