### ISSUE TITLE
request for consideration: Transpile only package

### ISSUE THREAD

**Issue by stefanpenner** [6to5/6to5#387]
When including `6to5` in other build systems, 6to5 pulling extra deps (like chokidar) is unfortunate.   
Especially when some of these have inherently brittle native extensions.

**Comment by timoxley** [comment]
chokidar/fsevents is the leading cause of slow builds for me, and not just when using 6to5.

**Comment by stefanpenner** [comment]
`kexec` is another module of concern.

**Comment by thejameskyle** [comment]
Probably wouldn't be too difficult to add to `make publish`. Are you envisioning just a `6to5-dist` package that only contains the files in the `dist/` folder after `make build`?

**Comment by sebmck** [comment]
I'm not familiar with publishing multiple packages with the same codebase since that would essentially be the only solution that I'm comfortable with. An additional package with a different `package.json` with `devDependencies`, `optionalDependencies`, `scripts` and `bin` removed and the `bin` dependencies taken out. I guess you could hotswap them out during `make publish` but it feels pretty dirty.

**Comment by stefanpenner** [comment]
@sebmck also unsure about the correct solution, what you suggest seems very reasonable.

**Comment by sindresorhus** [comment]
You could also split the CLI and the API into separate modules.

`6to5-cli` (cli) and `6to5` (api), or `6to5` (cli) and `6to5-core` (api).

**Comment by thejameskyle** [comment]
> You could also split the CLI and the API into separate modules.

I'd be a fan of that more than a separate module that duplicates most of the codebase.

**Comment by stefanpenner** [comment]
> or 6to5 (cli) and 6to5-core (api).

:+1:

**Comment by sindresorhus** [comment]
> or 6to5 (cli) and 6to5-core (api).

This is btw how Autoprefixer does it:
https://github.com/postcss/autoprefixer
https://github.com/postcss/autoprefixer-core

**Comment by sebmck** [comment]
It's too late to split it up into `6to5` and `6to5-cli`.

**Comment by thejameskyle** [comment]
@sebmck Why's that?

**Comment by thejameskyle** [comment]
@sebmck I think it makes more sense for `6to5` to continue being what it is now by depending on a new  `6to5-core` module.

**Comment by sebmck** [comment]
Except what it is now includes a CLI. It's currently expected that running `npm install -g 6to5` will let you run `6to5`. It's a backwards compat issue and even on a major I wouldn't feel comfortable because it's changing already established user expectations.

**Comment by timoxley** [comment]
I don't think @thejameskyle or @stefanpenner is suggesting that `npm install 6to5` change behaviour, rather if you don't need the CLI and its dependencies you could install `6to5-core` instead and just get a requirable, programmatic API.

**Comment by sebmck** [comment]
@timoxley I was referring to a possible `6to5` and `6to5-cli`. I misread @thejameskyle response to my "It's too late to split it up into 6to5 and 6to5-cli." comment.

**Comment by sebmck** [comment]
Added a `6to5-core` package. Currently does some hacky stuff with the `make publish` process but it works. @6to5/owners Feel free to migrate any/all of the plugins over, ping me if you want npm ownership over any/all of them.

**Comment by AluisioASG** [comment]
Hm, just got the “no templates directory” error trying to use the new package.  Also, the error message links to githu**t**.com.

**Comment by sebmck** [comment]
@AluisioASG Woops, ran the wrong `make` task. Pushed out a new release.

**Comment by AluisioASG** [comment]
Thanks!

**Comment by thejameskyle** [comment]
:eyes: :heart: :point_right: @sebmck

**Comment by stefanpenner** [comment]
:+1:
