### ISSUE TITLE
request: ability to disable `use strict`

### ISSUE THREAD

**Issue by stefanpenner** [6to5/6to5#388]
Yes this is bad-practice, but I believe I have two valid scenarios.

* iOS 8 armv7 devices have a fatal bug when code paths hitting `Object.create` become hot, and are in a `use strict` context. https://bugs.webkit.org/show_bug.cgi?id=138038
* when combining with another tool that provides module transpile functionality, we end up with two `use strict` statements, and I believe the module transpiler should be responsible for the `use strict`

**Comment by sebmck** [comment]
```javascript
require("6to5").transform("code", { blacklist: ["useStrict"] });
```

```sh
$ 6to5 --blacklist useStrict
```

**Comment by stefanpenner** [comment]
awesome thanks!

**Comment by oveddan** [comment]
Thanks for doing this!  

I'm taking over a legacy project where unfortunately there were a lot of uses of variables without declaring them first.  With 'use strict', the code gets an error when this code is run.  I plan on fixing all of the variable declarations, but until then, being able to turn this off temporarily is helpful.

**Comment by OmJan** [comment]
Many Thanks!

**Comment by laggingreflex** [comment]
doesn't work in gulp-babel?

    .pipe(babel({
        blacklist: ['useStrict'],



    Unknown option: base.blacklist
