### ISSUE TITLE
Turn runtime cache on by default?

### ISSUE THREAD

**Issue by lightsofapollo** [6to5/6to5#395]
For me (on a moderate sized project) turning cache on saves somewhere between 700ms-1s seems like this should be on by default?

**Comment by sebmck** [comment]
Not sure what you're referring to specifically? `6to5/register`?

**Comment by lightsofapollo** [comment]
correct

**Comment by sebmck** [comment]
It has some pretty big gotchas that I feel would bite people in the ass.

 - It'll produce a `.roadrunner.json` file in the cwd.
 - If files locations change then the cache is invalid. ie. you rename `foo.js` to `foo/index.js`. It extends to `node_modules` too.

**Comment by sebmck** [comment]
Closing this due to the previously mentioned issues associated.
