### ISSUE TITLE
ES6 syntax not valid inside new Function() body

### ISSUE THREAD

**Issue by timoxley** [6to5/6to5#399]
e.g.

```
new Function('item', 'return `${item}`')('hello')
```
evaluates to
```
Uncaught SyntaxError: Unexpected token ILLEGAL
```

**Comment by sebmck** [comment]
It's not valid inside of `eval` either for the same reasons. It's impossible to do anything about this kind of stuff because 6to5 has no runtime context.

**Comment by timoxley** [comment]
understood.

**Comment by zloirock** [comment]
@timoxley you can use in you code something like [this](http://goo.gl/tp18xV)
