### ISSUE TITLE
Destructuring assignment of function arguments default _ref to {}

### ISSUE THREAD

**Issue by kentcdodds** [6to5/6to5#400]
If I were to write this kind of api:

```js
foo({a: 'b'});
```

Sometimes, I would also allow:

```js
foo();
```

and default like so:

```js
function foo(options) {
  options = options || {};
  options.a = options.a || 'b';
  // ...
}
```

This is not possible with destructuring assignment in 6to5 currently:

```js
function foo({a}) {
  a = a || 'b'; // when #230 is closed, this line will not be necessary and the default will be in the destructuring
}
```

6to5 creates `_ref` in place of the destructuring, but doesn't check for whether it's provided. Is there room for adding this somehow? What does the spec say about this situation?

**Comment by fkling** [comment]
6to5's behavior os correct. See this discussion: https://esdiscuss.org/topic/default-values-of-destructured-arguments

Basically you'd have to write

    function foo({a='b'} = {a: 'b'}) { ... }

Or alternatively:

```
function foo(options) {
    var {a} = Object.assign({a: 'b'}, options);
}
```

**Comment by kentcdodds** [comment]
Once #230 is supported, I imagine that _ref would be initialized in that case as well if defaults are provided, correct?

**Comment by sebmck** [comment]
Once destructuring is supported you'll be able to do:

```javascript
function foo({ bar = "foob" } = {}) {

}
```

**Comment by kentcdodds** [comment]
Ok, great. Question, is this really how we're supposed to do defaults on objects? Here's the problem I see with that:

```js
function foo({ bar = 'bar', foobar = 'foobar', barfoo = 'barfoo' } = { bar:'bar', foobar: 'foobar', barfoo: 'barfoo' }) {
  // that's just insane
}
```

I would much rather do this:

```js
function foo({ bar = 'bar', foobar = 'foobar', barfoo = 'barfoo' }) {
  // DRY
}
```

Does the spec allow for this?

**Comment by fkling** [comment]
As @sebmck said,  `function foo({ bar = 'bar', foobar = 'foobar', barfoo = 'barfoo' } = {})` will work as well.

**Comment by sebmck** [comment]
@kentcdodds You just have to set the default to an object and it'll work fine.

**Comment by kentcdodds** [comment]
I don't see how that could work as I expect. Perhaps I misunderstand...

```js
function foo({ bar = 'bar', foobar = 'foobar', barfoo = 'barfoo' } = {}) {
  console.log(bar);
}
// I would expect
foo({bar: 'foo'}); // logs 'foo'
foo({}); // logs bar
foo(); // logs undefined
```

I must be misunderstanding the order of operations. After writing this out, I think I understand. The default assignment from undefined to `{}` occurs before the destructuring assignment of the object occurs. Is that right? If so, awesome. Looking forward to #230 support :D

**Comment by sebmck** [comment]
@kentcdodds Yeah, the default initialisation happens before the destructuring. See my comment [here](https://github.com/6to5/6to5/issues/400#issuecomment-68817910) for example code.

**Comment by sebmck** [comment]
Also just an FYI but the next version of 6to5 is going to have destructuring defaults support. However default destructuring on shorthand properties aren't supported so `{ a = 1 }` **wont** work but `{ a: a = 1 }` **will**.

**Comment by kentcdodds** [comment]
Thanks for letting me know that @sebmck! That's not a limitation of the spec is it? It's just not fully supported yet correct? Thanks for all your work on this!

**Comment by sebmck** [comment]
@kentcdodds It's not a spec limitation, it's just a limitation of the current parser implementation. No problem! Love to be of assistance. Check out our [gitter room](https://gitter.im/6to5/6to5) for support etc.

**Comment by sebmck** [comment]
Aforementioned destructuring defaults support is added as of 2.6.0
