### ISSUE TITLE
Strange bug with comments

### ISSUE THREAD

**Issue by kobezzza** [6to5/6to5#407]
```js
var res = true &&
	// Foo
	true;
```

->

```js
var res = true &&
// Foo
true; // all fine
```

BUT

```js
var res = true &&
	// Foo
	(true);
```

->

```js
var res = true && true;
// Foo
```

It's possible bug.

I use gulp-wrap for my code, something like this:

```js
'(function (root) {' +
	'<%= contents %>' +
'})(this);'
```

And it's render to

```js
(function (root) {var res = true && true;
// Foo})(this); // Error
```

---

**More examples:**

```js
function foo(
  /// 121
) {
  
}
```

->

```js
function foo() {}
/// 121
```

---

```js
function foo(
  /// 121
  ...foo
) {
  
}
```

->

```js
function foo() {
  var foo = [];

  for (var _key = 0; _key < arguments.length; _key++) {
    foo[_key] = arguments[_key];
  }
}
// 121
```

**Comment by sebmck** [comment]
All the examples provided are due to the comments not having a node to attach to.

For example:

```javascript
function foo(
  /// 121
) {

}
```

can't be retained because it's not attached to any node, ie. no expression appears near to it that it can attach itself to in order to print itself.

**Comment by kobezzza** [comment]
Ok, but why

```js
var res = true &&
    // Foo
    (true);
```

?

Example from real code:

```js
function isLikeArray(obj) {
	var res = isArray(obj) ||
		(obj &&

			// PhantomJS hack:
			// HTMLCollection and NodeList
			// typeof 'function' && instanceof Function = false
			obj instanceof Object && !isFuncRgxp.test(toString.call(obj)) &&

			// If object is like an array
			((obj.length > 0 && 0 in obj) || obj.length === 0)
		);

	return Boolean(res);
}
```

-> 

```js
function isLikeArray(obj) {
  var res = isArray(obj) || obj &&

  // PhantomJS hack:
  // HTMLCollection and NodeList
  // typeof 'function' && instanceof Function = false
  obj instanceof Object && !isFuncRgxp.test(toString.call(obj)) && (obj.length > 0 && 0 in obj || obj.length === 0);

  return Boolean(res);
}


// If object is like an array
```

**Comment by sebmck** [comment]
Comment attachment is currently delegated to [estraverse](https://github.com/estools/estraverse). It might be a limitation in their implementation and most likely has to do with the parentheses.

**Comment by phpnode** [comment]
it's because there is no AST node type which represents the parentheses, they are "lost" in the parse process (because they're not semantically meaningful) and there's no way to preserve them currently. Suggest closing this as "wontfix" (or "cantfix") as it's a bit out of scope for 6to5.

**Comment by sebmck** [comment]
@phpnode Previously 6to5 used the `preserveParens` option with acorn that produced `ParethesizedExpression` nodes. It caused a variety of issues and edge cases though and it has since been removed. You're right in that there's nothing much we can do about it due to location issues etc. I'm open to other comment attachment algorithms/libraries that may handle this edgecase although I'm not sure how extensive that selection is.
