### ISSUE TITLE
option to control tab size in output

### ISSUE THREAD

**Issue by kevinb7** [6to5/6to5#414]
Is there anyway to control the tab size in the output.  I'm working on project with 4 space tabs but the output uses 2 space tabs.

**Comment by monsanto** [comment]
if you're using the API, pass in `{..., format: {indent: {style: "    "}}, ...}` as options. It's currently undocumented, unavailable from the CLI, and I assume there is no guarantee it will remain stable. You can see the other options for `format` [here](https://github.com/6to5/6to5/blob/90437d262bc63a1482ce122a3ba0062b3ce2c118/lib/6to5/generation/generator.js#L38).

**Comment by thejameskyle** [comment]
> apparently GitHub doesn't preserve whitespace in inline code

That's just HTML.

> It's currently undocumented

It was documented previously, I probably just missed it when rewriting the documentation. @sebmck Are there any other undocumented options right now?

**Comment by sebmck** [comment]
@thejameskyle Not sure, you can go through [file.js](https://github.com/6to5/6to5/blob/master/lib/6to5/file.js#L50-65) and [generator.js](https://github.com/6to5/6to5/blob/master/lib/6to5/generation/generator.js#L39-46) for all the options.

**Comment by kevinb7** [comment]
@monsanto Thanks.  I updated my gulpfile and that did the trick.
