### ISSUE TITLE
JSX whitespace issue

### ISSUE THREAD

**Issue by arnihermann** [6to5/6to5#419]
I have a reproducible case where whitspace isn't preserved correctly:

```
var Foo = React.createClass({
  render() {
    return (
      <span>foo</span>
    );
  }
});

var Bar = React.createClass({
  render() {
    return (
      <div>
        <Foo/> bar
      </div>
    );
  }
});
```

When we render `<Bar/>` the text `foobar` is rendered in browser without a space character between `foo` and `bar`.

React's jsx tranformer outputs something like `<span> bar</span>` while 6to5 outputs `<span>bar</span>`.

**Comment by gaearon** [comment]
+1 to this.

I already merged 6to5 support to our master, but looks like I'll need to revert soon because we can't deploy with this bug.

It subtly breaks UI in a lot of places.

![screen shot 2015-01-09 at 22 25 17](https://cloud.githubusercontent.com/assets/810438/5685749/867ce25c-984e-11e4-8708-0ae471393516.png)

**Comment by sebmck** [comment]
Looks like an `acorn-jsx` bug since the space isn't present in the string literals. @RReverser, any ideas?

```
> require("acorn-jsx").parse("<div>\n<Foo/> bar\n</div>").body[0].expression.children
[ { type: 'Literal',
    start: 5,
    end: 6,
    value: '\n',
    raw: '\n' },
  { type: 'XJSElement',
    start: 6,
    end: 12,
    openingElement:
     { type: 'XJSOpeningElement',
       start: 6,
       end: 12,
       attributes: [],
       name: [Object],
       selfClosing: true },
    closingElement: null,
    children: [] },
  { type: 'Literal',
    start: 13,
    end: 17,
    value: 'bar\n',
    raw: 'bar\n' } ]
```

**Comment by RReverser** [comment]
I think I'll rewrite that part to the same technique that is now used for ES6 templates in upstream `acorn` so all the whitespace and issues like #398 will be fixed altogether (however it might take a bit of time for me to get to this).

**Comment by sebmck** [comment]
@RReverser No problem, thanks for your awesome work!

**Comment by gaearon** [comment]
Filed as https://github.com/RReverser/acorn-jsx/issues/13

**Comment by sebmck** [comment]
Fixed in the 3.0.0 branch

**Comment by sebmck** [comment]
Released as of 3.0.0

**Comment by RReverser** [comment]
@sebmck Duplicate :P

**Comment by gaearon** [comment]
It's just officially out now :-)

**Comment by RReverser** [comment]
Ah, I see.
