### ISSUE TITLE
Make removal of extension in default formatter optional/configurable

### ISSUE THREAD

**Issue by alexlawrence** [6to5/6to5#420]
Hi,

I have (mocha) specs which have the same filename as the subject under test and only another extension. Example: subject.js and subject.spec.js. Since the AMD and the System formatter inherit from the Default formatter all file extensions are removed. This results in duplicate module ids. How about making the removal of the file extension or configurable? So that either I have module ids matching the filenames or that just the last "extension" is removed.

Thanks

**Comment by sebmck** [comment]
Added as of 2.11.0. Usage:

```sh
6to5 --keep-module-id-extensions script.js
```

```javascirpt
require("6to5").transform("code", { keepModuleIdExtensions: true });
```

**Comment by alexlawrence** [comment]
:+1:
