### ISSUE TITLE
Destructuring & defaults dont work

### ISSUE THREAD

**Issue by Wenqer** [6to5/6to5#422]
https://twitter.com/jaffathecake/status/553159821135200256 this work in Traceur,
but dont work in 6to5 https://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&code=function%20func(%7Bfoo%20%3D%20'test'%2C%20bar%20%3D%20'test2'%7D%3D%7B%7D)%20%7B%0A%20%20return%20%5Bfoo%2C%20bar%5D%0A%7D

**Comment by fkling** [comment]
Duplicate https://github.com/6to5/6to5/issues/230

**Comment by sebmck** [comment]
Currently available as of 2.9.0
