### ISSUE TITLE
FR: URL shortener in web REPL

### ISSUE THREAD

**Issue by hemanth** [6to5/6to5#423]
@sebmck Would be useful if we had a URL shortener in the [REPL](http://6to5.org/repl/) that would shortern the `window.location.href` so that it will be easy to share the code?

Would be happy to work on a PR if so ;)

**Comment by sebmck** [comment]
@hemanth Sure, what did you have in mind?

**Comment by hemanth** [comment]
@sebmck Not sure about the serve capabilities of where the site is hosted or is it just gh-pages (need to check) if possible we could do something like what jsfiddle/jsbin does or use a shortening service like [http://is.gd/apishorteningreference.php](is.gd), please let me know if there are any other plans.

**Comment by sebmck** [comment]
On second thought I'm not sure if this is even necessary. You aren't really meant to be using the REPL for code hosting (which is basically what this is) and for those scenarios were they code is quite lengthy you can already use an existing URL shortener.

**Comment by hemanth** [comment]
@sebmck Agree, was just for the connivence of the users.

**Comment by sebmck** [comment]
It's also an issue because there's currently no backend server hosting the 6to5 site, it's just static. Thanks for the suggestion though! Will definently reevaluate if we end up switching to a dynamic site, although unlikely.

**Comment by hemanth** [comment]
:+1:

**Comment by thejameskyle** [comment]
It probably wouldn't be too hard to add a button for creating a bit.ly link for the current url. I'd have to look though.

**Comment by hemanth** [comment]
@thejameskyle It's not a hard task, but is it required was the question :)

**Comment by thejameskyle** [comment]
Maybe not required, but I'd certainly like it.

**Comment by hemanth** [comment]
Me too!
