### ISSUE TITLE
to5Runtime.interopRequireWildcard is undefined

### ISSUE THREAD

**Issue by fkling** [6to5/6to5#429]
Am I missing something?

![screen shot 2015-01-09 at 12 26 36 am](https://cloud.githubusercontent.com/assets/179026/5677093/3488bc04-9796-11e4-84e0-3e5d0cd05cc4.png)

I got the runtime through `6to5-runtime`.

[Code search](https://github.com/6to5/6to5/search?q=interopRequireWildcard&type=Code&utf8=%E2%9C%93) doesn't find it either?

**Comment by sebmck** [comment]
How are you including the runtime?

**Comment by fkling** [comment]
I simply export the runtime in one of my npm scripts via `6to5-runtime > runtime.js` and include in my HTML page... but I guess you already found the issue ;)

**Comment by sebmck** [comment]
Thanks, fixed as of 2.9.1. The runtime generator was breaking on excluded runtime helpers which caused all subsequent helpers that should be included not to be.

**Comment by fkling** [comment]
Thanks!
