### ISSUE TITLE
let transformation produces collisions

### ISSUE THREAD

**Issue by ooflorent** [6to5/6to5#434]
The following example duplicates `i` declaration.

```js
for (let i = 0; i < 5; i++);
for (let i = 0; i < 5; i++);
```

But the following doesn't:

```js
for (let i = 0; i < 5; i++);
for (let i = 0; i < 5; i++);
i;
```

I would expect both snippets to produce the same result.

**Comment by fkling** [comment]
One could argue that it is not necessary to rename the variables in the first case.

**Comment by thejameskyle** [comment]
For reference:

```js
for (var i = 0; i < 5; i++) {
  ;
}for (var i = 0; i < 5; i++) {
  ;
}
```

```js
for (var _i = 0; _i < 5; _i++) {
  ;
}for (var _i2 = 0; _i2 < 5; _i2++) {
  ;
}i;
```

**Comment by sebmck** [comment]
First case we can be sure that `i` leaking doesn't matter since it's not referenced anywhere in the current file. Second case we have to remap the variables so the last `i` reference throws a `ReferenceError`.

**Comment by sebmck** [comment]
To address the issue title, how does this produce collisions?

**Comment by sebmck** [comment]
Closing due to it being a non-issue and inactivity. Feel free to reopen if it's still an issue.
