### ISSUE TITLE
Broken class scope?

### ISSUE THREAD

**Issue by fkling** [6to5/6to5#435]
If I read the [spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-classdefinitionevaluation) correctly, then a class definition creates a new scope.

So

```js
class Foo {
  bar() {
    console.log(Foo);
  }
}

var foo = new Foo();
var Foo = 'asd';
foo.bar();
```

should log the constructor function, but since it's compiled to

```js
var Foo = function Foo() {};

Foo.prototype.bar = function () {
  console.log(Foo);
};

var foo = new Foo();
var Foo = "asd";
foo.bar();
```

it won't.

I know you [used an IIFE before](https://github.com/6to5/6to5/issues/288) and only use it now when [inheritance is present](https://github.com/6to5/6to5/issues/339), but it seems it's not "good enough". Should we switch back to using an IIFE every time? (technically we only need it if the class name is written to, but I don't know how easy it would be to track that).

**Comment by thejameskyle** [comment]
Chrome Canary:

<img width="274" src="https://cloud.githubusercontent.com/assets/952783/5690620/f06bab48-984a-11e4-983d-79913cd206e0.png">

**Comment by sebmck** [comment]
Looks like it's best to always have the IIFE.

**Comment by sebmck** [comment]
Thanks @fkling!
