### ISSUE TITLE
optimization: Generating a traditional for loop from for-of if flag in comment is present

### ISSUE THREAD

**Issue by monsanto** [6to5/6to5#436]
I propose that we add the following translation, where the first comment is significant:

```
// 6to5: always array
for (let x of arr) {
   ...
}

-->

for (let i = 0; i < arr.length; i++) {
  let x = arr[i]
  ...
}
```

Rationale:  I'm finding in hot portions of my code that traditional for loops give a measurable performance difference over for-of + array-iterator translation. I don't think this is surprising since the traditional for-loop is probably *the* most common JavaScript pattern and accordingly all of the VMs generate tight code in this case.

It's true that I could just write traditional for-loops instead of using for-of in such cases. But,

1. for-of loops are much easier to read and write. 
2. Rewriting a for-of loop to a traditional for loop is a pain in the ass. It's especially frustrating to perform one of these rewrites and find out that it didn't make as much of a performance difference as you expected. Adding a comment is easy, and in most editors can be automated with a keyboard macro.
3. Related to point 2, if it turns out later that you need the loop to work on a general purpose iterator, you can just remove the comment.
4. When VMs get good support for ES6, for-of on arrays will probably be as fast as traditional for loops. 6to5 would then give you a smooth transition, by simply disabling the transformer.

If you all think this is a good idea then I can provide a PR.

**Comment by thejameskyle** [comment]
I'm not sure we should go down the path of using comments to modify the output. We've discussed it before in relation to the UMD with globals. @6to5/owners thoughts?

**Comment by timoxley** [comment]
While I would be interested in using a tool for magical rewriting of loops for perf, but magical comments really doesn't sound like it should be a 6to5 responsibility.

**Comment by fkling** [comment]
> but magical comments really doesn't sound like it should be a 6to5 responsibility.

That's what I thought as well. I like the idea a lot(!), but not sure if it should be integrated into 6to5. Maybe 6to5 can open up its transformation pipeline to allow custom extensions?

**Comment by monsanto** [comment]
@timoxley whose responsibility is it, then? 6to5 is the one generating the code for the for-of. It isn't preordained that 6to5 has to compile a for-of loop like it currently does. I think if we can do a better job with the code generation we should.

For-of loops are SLOW. A quick test of iterating over a million elements and calculating a sum on my machine w/ node 11.14:

- for-of: 157ms
- arr.forEach: 42ms
- traditional: 5ms

but don't take my word for it that this optimization matters in the real world, there is a PR right now that went over 6to5 itself converting a bunch of slow looping constructs, and got a 29% improvement: https://github.com/6to5/6to5/pull/432

@fkling opening up the transformation pipeline is a bunch of extra work. If playground transformers are allowed to be in core, why not something that would actually make a difference in performance sensitive code?

**Comment by thejameskyle** [comment]
@monsanto If you could find an implementation that respects the spec and improves speed then that would easily be accepted.

**Comment by timoxley** [comment]
6to5 is really just a stopgap until ES6 is supported in more runtimes. You shouldn't be planning on using any uniquely 6to5 feature because ideally 6to5 will soon be no longer needed.

Are you going to keep using 6to5 once your target platform supports ES6 so you can continue having this optimisation applied?

**Comment by Dashed** [comment]
It'll be quite a while until more runtimes support ES6. Plus, experimental features like those ES7+ will still make 6to5 relevant.

**Comment by thejameskyle** [comment]
> 6to5 is really just a stopgap until ES6 is supported in more runtimes. You shouldn't be planning on using any uniquely 6to5 feature because ideally 6to5 will soon be no longer needed.

To be clear we plan on tracking standards past ES6, see `--experimental`.

> Are you going to keep using 6to5 once your target platform supports ES6 so you can continue having this optimisation applied?

Yes, for..of will still not be as optimized once implemented by browsers (although hopefully faster than what 6to5 can provide) simply because they haven't had as much time to optimize them. Even once implemented natively and optimized, they still might not be as fast because they have to implement a larger spec (seen in 6to5).

The solution here is to write the optimized version yourself I'm afraid.

**Comment by fkling** [comment]
I understand your point, but following the separation of concerns, it's not necessarily 6to5's job to create the most performant code. Spec compliancy is much more important IMO.

I don't see a problem in having a dedicated tool that does that. There are other transpiler you can built upon (such as [recast](https://github.com/benjamn/recast)).

**Comment by Dashed** [comment]
Why not make this a transformer: `forOfOptimization`? Then you can enable/disable via whitelist/blacklist. It'll probably won't be part of the standard set of transformers; but probably go into *experimental* or another category.

**Comment by thejameskyle** [comment]
@Dashed it would be an [optional transformer](http://6to5.org/docs/usage/transformers/#optional-transformers) if anything.

**Comment by monsanto** [comment]
There is no reason to believe that a for-of-aware JIT would generate slower code if it can deduce the type is array (optionally backing out of the optimization if the Array prototype has been modified). The proposed optimization here is a stopgap until we get to that point. And honestly, I'm here to stay, so "stopgap" doesn't mean much to me. When ES6 is fully supported, I'll be using ES8 features with a transpiler.

@fkling composing tools that extend JavaScript syntax is a nightmare. There is a reason 6to5 implements JSX in core instead of requiring the user to compose with the official `jsx` transform.

@Dashed @thejameskyle currently I have this implemented as a simple if statement in the for-of transformer, but I could split it out into another transformer I guess. (see the related PR)

**Comment by monsanto** [comment]
OK, how about this. It's really long and nasty, but it has the performance characteristics of a traditional for-loop when it's an array, but yet also works on iterators. Again, this would be an optional transform for people who need the (significant) performance boost. For people like me, all the ES6 syntax sugar in the world doesn't mean anything if performance goals are not met.

I imagine most people would use this optional transform only in production builds.

```javascript
for (let ID of EXPR) {
  BODY
}

```

-->

```javascript

let loopyThing = EXPR
let isArray = Array.isArray(loopyThing)
let i = 0
if (!isArray) {
    loopyThing = loopyThing[Symbol.loopyThing]()
}
while (true) {
    let ID
    if (isArray) {
        if (i >= loopyThing.length)
            break
        ID = loopyThing[i]
        i++
    } else {
        let step = loopyThing.next()
        if (step.done)
            break
        ID = step.value
    }
    BODY
}
```

**Comment by sebmck** [comment]
@timoxley 

> 6to5 is really just a stopgap until ES6 is supported in more runtimes. You shouldn't be planning on using any uniquely 6to5 feature because ideally 6to5 will soon be no longer needed.

6to5 is going to support all future ES standards. ES7 is going to be here far quicker than the transition from ES5 to ES6 was. 6to5 will obviously have to be renamed so the name is actually relevant but that's a long way away.

@monsanto  As for the specific request, I really don't think it's needed. It adds a lot of complexity where you can just write a `for...in`.

**Comment by monsanto** [comment]
closing this issue as I am no longer interested in the comment-to-optimize solution, see #441
