### ISSUE TITLE
arrow function as module.exports leads to wrong generation

### ISSUE THREAD

**Issue by dieppe** [6to5/6to5#437]
(I don't know if it's really a bug or if we're not supposed to do this, but it works fine when using jsx)

When using the arrow function as a module exports, the generated code is wrong. 
The following (useless but minimal) example
```js
module.exports = () => arguments;
```
will lead to the generated code
```js
var _arguments = arguments;
module.exports = function () {
  return _arguments;
};
```
while 
```js
module.exports = function () { return arguments; };
```
leads to the correct version.

**Comment by dieppe** [comment]
Also, note that it duplicates the "use strict" statement like so:
```js
"use strict";

var _arguments = arguments;
"use strict";

module.exports = function () {
  return _arguments;
};
````

**Comment by fkling** [comment]
What exactly is incorrect about the generated code?

**Comment by monsanto** [comment]
@dieppe `arguments` doesn't make sense in a top-level arrow function, it works like `this`. see https://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrow-function-definitions-runtime-semantics-evaluation

**Comment by thejameskyle** [comment]
This is part of the spec. 

> Any reference to `arguments`, `super`, or `this` within an _ArrowFunction_ are resolved to their bindings in the lexically enclosing function.

See: https://github.com/6to5/6to5/issues/236#issuecomment-65302855

**Comment by dieppe** [comment]
All right, thanks for the quick and insightful answer. Seems I need to
learn a bit more about arrow functions ;)

2015-01-09 20:25 GMT+01:00 James Kyle <notifications@github.com>:
