### ISSUE TITLE
propertyMethodAssignment transformer too greedy

### ISSUE THREAD

**Issue by WebReflection** [6to5/6to5#444]
If I'm not mistaken this kind of literal object is available in IE9 and ES5 too, down to legacy browsers beside IE <= 8:
```js
var obj = {
  get length() {
    return 0;
  }
};
```

However, the result after `6to5 --whitelist=propertyMethodAssignment obj.js` is:
```js
var obj = Object.defineProperties({}, {
  length: {
    get: function () {
      return 0;
    },
    enumerable: true
  }
});
```

I believe the `propertyMethodAssignment` flag should only normalize these cases without changing getters at all:
```js
// before 6to5
var obj = {
  method() {},
  get length() {
    return 0;
  }
};

// after 6to5 --whitelist=propertyMethodAssignment
var obj = {
  method: function method() {},
  get length() {
    return 0;
  }
};

```

Is ther any plan to fix this or to add a new flag that will only actually transform non ES5 compatible parts?

Thanks for any sort of outcome.

**Comment by sebmck** [comment]
They should probably be split up into a separate transformers.

**Comment by WebReflection** [comment]
Thanks, also please note that in ES5 getters are configurable too so it's double greedy as it is now.

```js
Object.getOwnPropertyDescriptor({get length(){}}, 'length');

// procudes
Object { configurable: true, enumerable: true, get: .length(), set: undefined }

```

So either way there's something to fix in there :-)

**Comment by sebmck** [comment]
Queued for 3.0.0 as it'll be a breaking change. @WebReflection Ah, of course.

**Comment by WebReflection** [comment]
I can file a new bug for the missing `configurable` behavior if you want, otherwise please add [this note](https://github.com/6to5/6to5/issues/444#issuecomment-69459533) on that closed ticket too, thanks.

**Comment by sebmck** [comment]
@WebReflection New issue would be great.

**Comment by sebmck** [comment]
Actually, already done with 286d2f84bd4505fb0a612e8c812948a62e2506cd.

**Comment by WebReflection** [comment]
:+1:

**Comment by sebmck** [comment]
This has been split into an `es5.mutators` transformer that you can blacklist as of 3.0.0
