### ISSUE TITLE
Clarification about coreAliasing

### ISSUE THREAD

**Issue by fkling** [6to5/6to5#446]
Will coreAliasing only apply to the shims used by 6to5 itself or to *all* core-js shims (in the developers code (I know it works for `Array.from` at least))?

The website says:

> This means that you can use every single 6to5 feature without a globally polluting polyfill, minus [caveats](http://6to5.org/docs/caveats/) and all.

However, this doesn't seem to apply to the regenerator runtime, so it's not possible to use every single feature without a polyfill. While the regenerator runtime is listed in the caveats section, it's not clear whether it applies to it, since `Array.from` is listed there as well.

This all leads to my actual question: Can we do this for all core-js shims, the regenrator runtime, and the 6to5 runtime, so that libraries are truly self contained and don't pollute the global namespace?

Right now I'm concatenating the 6to5 runtime before my actual code. Would be great if I could avoid that.

**Comment by sebmck** [comment]
Ah yeah, the docs is definently ambiguous/wrong. All the `coreAliasing` transformer does is transform `arr[Symbol.iterator]()` and ES6 methods such as `Array.from` to their `core-js` equivalent. It's definently possible to add a way to use the `to5Runtime` in the same way. There's currently no way to include the `regeneratorRuntime` without polluting the global scope, perhaps @benjamn can help here?

**Comment by sebmck** [comment]
Closed with the introduction of `selfContained` in 3.0.0

**Comment by fkling** [comment]
:+1:
