### ISSUE TITLE
6to5-node usage typo

### ISSUE THREAD

**Issue by Dashed** [6to5/6to5#448]
As of `v2.4.8`, typing `6to5-node --help` outputs:

```sh
$ 6to5-node --help

  Usage: _6to5-node [options] [ -e script | script.js ] [arguments]
```

`_6to5-node` should be `6to5-node`. 

I'm not intimate on how `commander` works to correct this.

**Comment by monsanto** [comment]
attached PR should do it

**Comment by Dashed** [comment]
@monsanto I think https://github.com/6to5/6to5/pull/450 is better though.
