### ISSUE TITLE
Broken `super` keyword

### ISSUE THREAD

**Issue by zloirock** [6to5/6to5#451]
#408 transform make 6to5 unusable for working projects, only as a ES6 playground. It's better for spec compliancy, but the differences are only in exotic cases. [Simple inheritance test](http://jsperf.com/6to5-inherit):
```javascript
class P {
  constructor(){
    this.x = 0;
  }
  fn(){
    this.x++;
  }
}
class C extends P {
  constructor(){
    super();
  }
  fn(){
    super.fn();
  }
}
```
![v8](http://habrastorage.org/files/43a/4b1/93a/43a4b193ae01405e9c3a660fd0855fae.png)
![ff](http://habrastorage.org/files/c4d/e77/ac2/c4de77ac242a4844bb0736a18bb73803.png)
I suggested make it optional transform.

**Comment by sebmck** [comment]
Can you please stop referring to it as broken. The way you're suggesting actually makes it broken.

I'm open to having an optional transformer that uses the old non-spec compliant way but I'm not willing to make it a default as all the defaults should be spec compliant.

**Comment by zloirock** [comment]
@sebmck I think, the specification should be followed only when it does not interfere with use.

**Comment by sebmck** [comment]
@zloirock We aren't on the same page then. Deviating from the spec will almost certainly lead to migration hazards. 6to5 transforms ES6 to ES5, not an ES6 variant.

**Comment by zloirock** [comment]
@sebmck You can implement, for example, the `@@toPrimitive` logic. That's just how it will look the work of the addition operator in this code and how quickly will it work?

**Comment by benjamingr** [comment]
Anything deviating from the ES6 spec will be a deal-breaker since people will want to swap 6to5 out when they run in ES6 environments.

**Comment by sebmck** [comment]
@zloirock Not too sure what you're trying to get at.
@benjamingr Absolutely agree.

**Comment by nktpro** [comment]
@sebmck I strongly suggest making the old transformer a config option. The performance impact of this is too significant for it to be a default with no way to opt-out. It's currently a blocker for us to use latest 6to5 for production code base.

**Comment by sebmck** [comment]
As of 2.10.0 there's a `classesFastSuper` optional transformer that'll use the old and subjectively better behaviour.

**Comment by nktpro** [comment]
Thanks @sebmck you rock!

**Comment by zloirock** [comment]
:thumbsup:

**Comment by nin-jin** [comment]
You can improve dynamic performance: http://jsperf.com/6to5-inherit/2

**Comment by nin-jin** [comment]
How about this realization? http://jsperf.com/6to5-inherit/3

**Comment by sebmck** [comment]
@nin-jin I'm not sure what those benchmarks are trying to show.

**Comment by nin-jin** [comment]
@sebmck faster realization of new logic (support of dynamyc [[Prototype]] changing)
