### ISSUE TITLE
Superconstructor call is not properly dynamic

### ISSUE THREAD

**Issue by domenic** [6to5/6to5#456]
Given this example:

```js
class Foo {
  constructor() { console.log("Foo"); }
}
class Bar extends Foo {}

Bar.__proto__ = function NewSuper() { console.log("NewSuper"); };

console.clear();
new Bar();
```

Traceur and any ES6 implementation will output `"NewSuper"`. 6to5 will output `"Foo"`.

**Comment by zloirock** [comment]
@domenic After 2.9.1 - "NewSuper". Update 6to5.

**Comment by domenic** [comment]
Ah, I'm just using the repl, I guess that isn't updated on deploy?

**Comment by sebmck** [comment]
Yeah, we currently haven't got it setup to automatically update the website on deploy. See 6to5/6to5.github.io#33

**Comment by sebmck** [comment]
@domenic I just want to assure you that spec compliancy is absolutely a priority. See issues such as #451

**Comment by sebmck** [comment]
@domenic After a discussion with @jeffmo on irc it actually seems like the `[[HomeObject]]` is set when the method is defined. Can you confirm?

##### [9.2.11 MakeMethod ( F, homeObject) Abstract Operation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-makemethod)

> The abstract operation MakeMethod with arguments F and homeObject configures F as a method by performing the following steps:
>
> 1. Assert: F is an ECMAScript function object.
> 2. Assert: Type(homeObject ) is either Undefined or Object.
> 3. Set the [[NeedsSuper]] internal slot of F to true.
> 4. **Set the [[HomeObject]] internal slot of F to homeObject.**
> 5. Return NormalCompletion(undefined).

**Comment by domenic** [comment]
Yes, but you look up [[HomeObject]]'s [[Prototype]] to actually do the work.

**Comment by jeffmo** [comment]
Yep, my bad -- after re-reading things it seems @domenic's correct.

For posterity/proof from the spec:

[14.5.14 Runtime Semantics: ClassDefinitionEvaluation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-classdefinitionevaluation)

Step 7: Let proto be ObjectCreate(protoParent).
Step 11: Let constructorInfo be the result of performing DefineMethod for constructor with arguments proto and constructorParent as the optional functionPrototype argument.
Step 12: Let F be constructorInfo.[[closure]]
Step 20.b.i: Let status be the result of performing PropertyDefinitionEvaluation for m with arguments F and false.

So the [[HomeObject]] is the class itself, not the defined class' parent. So lookups of super against [[HomeObject]] do have to do this lookup each time `super` is evaluated.

**Comment by sebmck** [comment]
@domenic Oh right, duh. Thanks!
