### ISSUE TITLE
AMD target - wildcard malfunction

### ISSUE THREAD

**Issue by cmichaelgraham** [6to5/6to5#457]
[6to5 source file](https://github.com/aurelia/framework/blob/master/src/index.js#L2) compiles to [generated AMD](https://github.com/aurelia/framework/blob/master/dist/amd/index.js#L12) 

it seems to me like _exportsWildcard's check is backwards. 

It only assigns the export if it isn't undefined. I would think it would assign it if it IS undefined.

If I change the line to === (from !==), it seems to work properly.

**Comment by sebmck** [comment]
Already been fixed in the latest 6to5.

**Comment by cmichaelgraham** [comment]
sorry for the dup.  6to5 is awesome. :)

**Comment by thejameskyle** [comment]
@cmichaelgraham No worries, thanks anyways!
