### ISSUE TITLE
Preserve JSX attribute comments

### ISSUE THREAD

**Issue by Dashed** [6to5/6to5#459]
Taking example from: http://facebook.github.io/react/docs/jsx-in-depth.html#comments

**source**
```js
var content = (
  <Nav>
    {/* child comment, put {} around */}
    <Person
      /* multi
         line
         comment */
      name={window.isLoggedIn ? window.name : ''} // end of line comment
    />
  </Nav>
);
```

**react v0.12 JSX** http://facebook.github.io/react/jsx-compiler.html
```js
var content = (
  React.createElement(Nav, null, 
    /* child comment, put {} around */
    React.createElement(Person, {
      /* multi
         line
         comment */
      name: window.isLoggedIn ? window.name : ''}// end of line comment
    )
  )
);
```

**6to5 v2.10.0**
```js
"use strict";

var content = React.createElement(
  Nav,
  null,
  React.createElement(Person, {
    name: window.isLoggedIn ? window.name : "" })
);
/* child comment, put {} around */
/* multi
   line
   comment */ // end of line comment


```

**Comment by Dashed** [comment]
Traditional comment placement are preserved, for example:

```js
var Nav, Profile;
// Input (JSX):
var app = <Nav color="blue"><Profile>click</Profile></Nav>;
// Output (JS):
var app = React.createElement(
  Nav,
  {color:"blue"},
  React.createElement(Profile, null, "click")
);
```

**Comment by sebmck** [comment]
The comment inside the expression container (`{/* child comment, put {} around */}`) is impossible to output because there are no nodes for it to attach itself to. Not too sure about why the attributes aren't getting comments attached to them. Either it's an issue with attributes not properly inheriting comments or a comment attachment issue.

**Comment by Dashed** [comment]
Is this impossible because of https://github.com/6to5/6to5/issues/407?

**Comment by sebmck** [comment]
@Dashed Yeah. Without a sibling node to attach to there's no way the code generator can retain them.

**Comment by sebmck** [comment]
Just investigated this and the comments aren't even being attached to the correct nodes which means we'd need to switch to a different comment attachment algorithm. I'll open a new issue. Thanks!
