### ISSUE TITLE
The "readable ES6 class" conversion could be better

### ISSUE THREAD

**Issue by srcspider** [6to5/6to5#460]
The following example is on the main site's frontpage:

```js
class User extends Model {
  constructor() {
    super();
    this.sayHello();
  }

  sayHello() {
    alert("Hello World!");
  }
}
```

It's said to convert to this "readable" version:
```js
var User = function User() {
  Model.call(this);
  this.sayHello();
};

_inherits(User, Model);

User.prototype.sayHello = function () {
  alert("Hello World!");
};
```

This is how it should actually look like:

```js
var User = function User() {
  Model.call(this);
  this.sayHello();
};

User.prototype = _assign_prototype(Model.prototype, {
  sayHello: function () {
    alert("Hello World!");
  }
};
```

Assuming there was actually 2 methods there to highlight the difference better,

```js
var User = function User() {
  Model.call(this);
  this.sayHello();
};

User.prototype = _assign_prototype(Model.prototype, {
  
  sayHello: function () {
    alert("Hello World!");
  },

  sayGoodbye: function () {
    alert("Good Bye World!");
  }
};
```

Where assign prototype would be something along the lines of just `Object.create` on the first parameter followed by `Object.assign` or equivalent of all others.

*Honestly though who needs ES6 classes when they can't even do traits or elegant multi-inheritance patterns or just about everything else you can do with regular javascript. Probably not the best example to sell ES6.*

Incidentally assuming ES6 actually eventually grows up and realizes that what everyone actually needs is traits way more then pointless "programming-sci-fi dreams of the 80s" generated code should look something like this:

```js
var User = function User() {
  Model.call(this);
  this.sayHello();
};

User.prototype = _assign_prototype(Model.prototype, Trait1, Trait2, {
  sayHello: function () {
    alert("Hello World!");
  }
};
```

Preferably simplified where for example extending other objects is not present.

```js
var User = function User() {
  this.sayHello();
};

User.prototype = _assign_new(Trait1, Trait2, {
  sayHello: function () {
    alert("Hello World!");
  }
};
```

**Comment by sebmck** [comment]
Yeah, for sure. Classes have gone through a lot of changes recently and the example on the frontpage and their corresponding output really needs to be cleaned up as it goes completely against the philosophy of 6to5.

**Comment by sebmck** [comment]
One thing that your proposed changes don't include is getters/setters. How would that fit into this?

**Comment by srcspider** [comment]
@sebmck 

Getter setters don't work in IE8, because `Object.create` only really understand the first parameter, as far as I'm aware. Even if it did I would happily give up some features for the sake of just getting very easy to read output.

As in the examples if the case is simpler, the generated code should just use the simpler approach.

A lot of the time, if we're talking models, it's much more convenient to have the private data wrapped in an inner structure since you can then iterate over it to validate, merge into it, etc. When you do that you only really need to create some trivial `get(key)` and `set(key, value)` methods, with the exception of data morphing/inspection/whatever methods (but you wouldn't be using getter/setters for those either).

Just to illustrate further, if there's no class extension of any kind, code should look like this:

```js
var User = function User() {
  this.sayHello();
};

User.prototype = {
  sayHello: function () {
    alert("Hello World!");
  }
};
```

Also on the topic of improving the example, I don't ever recall in practice ever calling a method that's not for initialization or setter/getter in my constructor functions, and using named anonymous functions also doesn't work quite right in IE8 (it creates two different objects; though its probably okey the way its used there... *probably*). A more realistic version of that "class-like" construct would be something like this:

```js
var User = function (name) {
  this._name = name;
};

User.prototype = {
  sayHello: function () {
    alert("hello " + this._name);
  }
};
```

Or, if we want to keep the "constructor" semantics,

```js
var User = function (name) {
  this.construct(name);
};

User.prototype = {
  construct: function (name) {
    this._name = name;
  },
  sayHello: function () {
    alert("hello " + this._name);
  }
};
```
(personally I prefer the previous one since it's closer to how I actually write it)

**Comment by sebmck** [comment]
@srcspider Getters and setters aren't a simple feature to drop. Just because old IE doesn't support them doesn't mean they shouldn't be supported, see the [caveats](https://6to5.org/docs/caveats/#getters-setters-8-and-below-).

**Comment by fkling** [comment]
One of the major goals of 6to5 is to be spec compliant. If you search the issues for "class", you can find the reasoning behind some of the recent changes.

**Comment by srcspider** [comment]
@sebmck then don't drop them, just make sure either the "clean path" is preferred when applicable, or there's an option to enforce that strategy. Personally I would never write it any more complex then it needs to be.

@fkling I've looked at issues that come up when searching for "class" and not quite sure I understand what the problem is. 

Are you suggesting that somehow it's impossible to translate `super` with out going to `Object.create` ? Just emulate it at the parsing level.

```js
class ExampleModel extends Model {
  constructor(data) {
    super(data);
    this._sid = uuid();
  }
  id() {
     return super.id() + this._sid;
  }
}
```

```js
var ExampleModel = function (data) {
  Model.call(this, data);
  this._sid = uuid();
};

var _super = Model.prototype;
ExampleModel.prototype = _assign_prototype(_super, {
  id: function () {
     return _super.id.call(this) + this._sid;
  }
});
```
I guess there's a difference in opinion here on how resulting code should look. Personally I would hugely favor code that is closer to "code I would write it if I wrote it by hand from scratch" over syntactic sugar style code. 

Of course I don't mean that everything should be verbose but whatever the resulting code is it should be equivalent to how you would translate it by hand, so like in the example in practice you would never declare some `_assign_prototype` function every time you write it, you would just write it once and use it everywhere, similarly you probably wouldn't hardcode `Model.prototype` everywhere.

*Think about it, if you were to translate manually from one to the other would you go to the trouble of emulating super? a technique you even know is not compatible with IE8? I wouldn't. If it's not equivalent to handwritten port of code then it's very machine-like and hence "less readable" by humans.*

**Comment by sebmck** [comment]
@srcspider `super` has to reflect the current prototype, meaning that instance prototypes can be changed and it has to be reflected in the use of `super`. I've recently implemented [loose mode](https://github.com/6to5/6to5/issues/465) for various transformers that outputs code that's much faster and nicer to read but is less spec compliant (it doesn't handle the extremely small nuisance edgecases). You can enable this run now via `6to5 --loose classes`. With your original example of:

```javascript
class User extends Model {
  constructor() {
    super();
    this.sayHello();
  }

  sayHello() {
    alert("Hello World!");
  }
}
```

it's transformed into

```javascript
var User = (function (Model) {
  function User() {
    Model.call(this);
    this.sayHello();
  }

  _inherits(User, Model);

  User.prototype.sayHello = function () {
    alert("Hello World!");
  };

  return User;
})(Model);
```

with `classes` loose mode.

**Comment by sebmck** [comment]
This shouldn't be an issue now that there's loose mode.
