### ISSUE TITLE
Unable to parse object spread

### ISSUE THREAD

**Issue by ooflorent** [6to5/6to5#461]
When 6to5 is run using `--whitelist`, spread parsing fails.

```js
let y = {c: 3, d: 4}
let x = {a: 1, b: 2, ...y}
```

```sh
$ 6to5 -l classes test.js
SyntaxError: xx.js: Unexpected token (2:21)
  1  | let y = {c: 3, d: 4}
> 2  | let x = {a: 1, b: 2, ...y}
     |                     ^
```

I was expecting the output to be the same as input.

**Comment by sebmck** [comment]
Object spread is an [experimental](http://6to5.org/docs/usage/experimental/) ES7 feature with the transformer `objectSpread`.

**Comment by ooflorent** [comment]
But why the following works:

```js
let x = {}
let y = {}
```

```sh
$ 6to5 -l classes test.js
```

```js
// as expected
let x = {}
let y = {}
```

`objectSpread` should be treated like other transformers: if not specified, parsing should be ok, but the transformation not applied.

**Comment by ooflorent** [comment]
Moreover:

```js
let y = {c: 3, d: 4}
let x = {a: 1, b: 2, ...y}
```

Produces an error:

```sh
$ ./node_modules/.bin/6to5 -l objectSpread xx.js
SyntaxError: xx.js: Unexpected token (2:21)
  1  | let y = {c: 3, d: 4}
> 2  | let x = {a: 1, b: 2, ...y}
     |                     ^
```

**Comment by sebmck** [comment]
Yeah, you need to enable [experimental support](http://6to5.org/docs/usage/experimental/).

```sh
$ 6to5 -l objectSpread --experimental xx.js
```

**Comment by ooflorent** [comment]
Thanks it works as expected.

**Comment by gsklee** [comment]
I'm unable to parse object spread as well. Setting is given as:

```
        {
               loose: 'all',
               blacklist: ['es6.modules'],
               optional: ['es7.objectSpread'],
               experimental:true
        }
```

with `gulp-6to5`, but it's not working:

```
ERROR in ./source/scripts/main.js
Module build failed: SyntaxError: /srv/home/gsklee/projects/dashboard/source/scripts/main.js: Unexpected token (336:18)
  334    |     }).done(function(data) {
  335    |       console.log(data);
> 336    |       let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
         |                   ^
  337    | 
  338    | console.log(z);
  339    |     });
```

**Comment by gsklee** [comment]
Is extra package/runtime required for this experimental feature?

**Comment by sebmck** [comment]
@gsklee It's a bit confusing by the `es7.objectSpread` actually also requires the `es6.destructuring` transformer to be enabled. This issue comes up quite a bit so in the next patch I'm going to force `es6.destructuring` to be enabled when you have `es7.objectSpread` whitelisted.

**Comment by gsklee** [comment]
@sebmck I did have destructuring enabled, I only disabled `es6.modules`.

**Comment by gsklee** [comment]
Hmmmm, I've imported `'6to5/polyfill'` in my project and am doing this within my gulp task:

```
             .pipe($['6to5']({
                 loose: 'all',
                 blacklist: ['es6.modules'],
                 optional: ['es6.destructuring','es7.objectSpread'],
                 experimental: true
              }))
```

But still get the warning:

```
ERROR in ./source/scripts/main.js
Module build failed: SyntaxError: /srv/home/gsklee/projects/dashboard/source/scripts/main.js: Unexpected token (18:12)
  16   | const ENDPOINT_SERVER = '';
  17   | 
> 18   | let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
       |             ^
  19   | console.log(z);
  20   | 
  21   | class Header extends React.Component {
```

What gives?

**Comment by sebmck** [comment]
@gsklee Not sure if it'd make a difference but the option you're looking for is `whitelist`, not `optional`.

I can't seem to replicate this

**script.js**

```javascript
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
```

```javascript
$ 6to5 --blacklist es6.modules --whitelist es6.destructuring,es7.objectRestSpread --experimental script.js
var _objectWithoutProperties = function (obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; };

var _ref = { x: 1, y: 2, a: 3, b: 4 };

let x = _ref.x;
let y = _ref.y;
let z = _objectWithoutProperties(_ref, ["x", "y"]);
```

Does it work if you remove the blacklist/whitelist/optional options?

**Comment by gsklee** [comment]
Found the source of the issue but it's a little bit cryptic.

This is my `gulpfile.js`:

```
             .pipe($['6to5']({
               loose: 'all',
               blacklist: ['es6.modules'],
               optional: ['es7.objectRestSpread'],
               experimental: true
              }))
             .pipe($.webpack(require('./webpack.config.js')))
```

And my `webpack.config.js`:

```
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loader: '6to5'
    }]
  },
```

I fixed the problem by changing the webpack config to `loader: '6to5?experimental'`. I thought when the file stream enters the second pipe, all ES6 syntax (save `import`/`export`) would already be replaced? So this is kinda beyond me.

**Comment by sebmck** [comment]
@gsklee The `es7.objectRestSpread` transformer isn't optional, it's automatically enabled when you use `experimental` so you can safely drop that option. Why are files being parsed by 6to5 twice anyway?

**Comment by gsklee** [comment]
@sebmck I'm using webpack for and only for modularization, I personally find gulp's imperative manner easier to handle than config-based building tools.

**Comment by ivan-kleshnin** [comment]
Am I right and the only way to use spread object destructuring inside `if` statement is `var`?

```js
if (true) {
  var {x, ...y} = {x: "X", a: "A", b: "B"};
} else {
  var x, y;
}

console.log(y);
```

OMG, it seems the only way to remove prop in React is spread destructuring (*) and the only way to do this is to run Babel in experimental mode with `var` statements inside if which are planned to removal at least in SaneScript. We are going on a very thin cracking ice.

* – props can't be deep cloned because they contain links to some very heavy objects and with shallow cloning mutable props can be... mutated.

**Comment by sebmck** [comment]
@ivan-kleshnin Not sure I understand the question, you've skipped too far ahead. What are you trying to do and why do you think you can't do it?

**Comment by ivan-kleshnin** [comment]
Ok, sorry. I want to remove one exact property from object by object spread destructuring. See my code example. But this should be inside one of the branch of `if` statement. And the result is going to be used after this statement. Is there other way to do this without `var` statement?

**Comment by sebmck** [comment]
```javascript
var x, y;

if (true) {
  ({x, ...y} = {x: "X", a: "A", b: "B"});
}

console.log(y);
```

**Comment by ivan-kleshnin** [comment]
Thanks! Note to readers: It works only with the latest Babel `5.3.*`. 
Syntax is... :unamused:  whatever.

**Comment by sebmck** [comment]
No that has worked since object spread/rest was implemented in Babel.

**Comment by ivan-kleshnin** [comment]
Well, if you care, I just had this error with Babel `5.2`. Update to `5.3` solved this. 
Had no other problems with that `5.2` install.

```
/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
TypeError: /Users/ivankleshnin/JavaScript/test.js: Cannot read property 'start' of undefined
    at Parser.pp.toAssignable (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/lval.js:29:56)
    at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:111:44)
    at Parser.pp.parseParenAndDistinguishExpression (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:419:28)
    at Parser.pp.parseExprAtom (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:338:19)
    at Parser.parseExprAtom (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:593:162)
    at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
    at Parser.pp.parseExprOps (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:155:19)
    at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:138:19)
    at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
```

**Comment by gsklee** [comment]
You can do it with `let` as well:

```javascript
let x, y;

if (true) {
  ({x, ...y} = {x: "X", a: "A", b: "B"});
}

console.log(y);
```

I think it's not a `let` vs. `var` issue; it's always a good practice to collect your variable declaration whenever possible.

**Comment by ivan-kleshnin** [comment]
@gsklee yes, I just never met `({x, ...y} = {x: "X", a: "A", b: "B"});` syntax before.
