### ISSUE TITLE
Idea: Group transformations according to engine support

### ISSUE THREAD

**Issue by ooflorent** [6to5/6to5#462]
Adding new flags to apply special sets of transformations would be really handy while using the CLI.
This idea is be able to transform only unship ES6 features.

```sh
# Only transform staged features (classes, template strings, ...).
# Don't transform `for of` since it is shipped.
$ 6to5 --v8_es_staging test.js
```

**Comment by sebmck** [comment]
See #272 for previous discussion. Basically it's hard/impossible to restrict these in scope, especially when these engines are forever updating.
