### ISSUE TITLE
bug(6to5@~2.10.1): no super call for inheritance of functions ?

### ISSUE THREAD

**Issue by douglasduteil** [6to5/6to5#463]
Hi 

I just noticed that since the 6to5@2.10.0 ( in 2.10.0 and 2.10.1 ) my tests fail in Isparta around the inheritance. It seems like when inheriting from a function (a class ES5 made) the super call doesn't do the thing...

Like I don't know how to explain it, I made a plunker with some dummy tests to concretely display it !
[Check that out](http://plnkr.co/6PSson)

**Comment by sebmck** [comment]
It's because you're reassigning `prototype` on `A5`. #408 relies on `constructor` being set on the prototype (which it should be, reassigning `prototype` destroys it).

**Comment by douglasduteil** [comment]
So we can't extend this kind of thing now ?
https://github.com/gotwarlost/istanbul/blob/master/lib/instrumenter.js#L336-L379

**Comment by eventualbuddha** [comment]
@douglasduteil You can work around it by calling the super constructor yourself. Instead of this:

```js
class B5 extends A5 {
  constructor() {
    super();
  }

  bar() {
    expect(this).to.have.property('theA5Options');
  }
}
```

You can do this:

```js
class B5 extends A5 {
  constructor() {
    A5.call(this);
  }

  bar() {
    expect(this).to.have.property('theA5Options');
  }
}
```

Ideally, though, Istanbul should fix its broken class setup by adding a `constructor` key to the object being assigned to the prototype.

**Comment by douglasduteil** [comment]
@eventualbuddha Right. Thanks :+1:
