### ISSUE TITLE
Playground flag is renamed?

### ISSUE THREAD

**Issue by ivan-kleshnin** [6to5/6to5#464]
Page at http://6to5.org/docs/usage/playground/ states that **playground** mode is enabled by 
`--playground` flag. However, it seems the real flag name is `--experimental`

```
$ 6to5-node --playground
> [for (x of [1, 2, 3]) x] 
... // syntax error

$ 6to5-node --experimental
> [for (x of [1, 2, 3]) x] 
[ 1, 2, 3 ]
```

**Comment by sebmck** [comment]
Nope. The playground consists only of the features documented on that page. Comprehensions are an experimental ES7 feature.

**Comment by ivan-kleshnin** [comment]
I quote that page:
> Enables experimental
Enabling playground also enables experimental support.

**Comment by sebmck** [comment]
And it indeed does.

```sh
$ 6to5-node --playground
> [for (x of [1, 2, 3]) x]
```

**Comment by ivan-kleshnin** [comment]
I've got it. My version of 6to5 is outdated. Sorry for that.

**Comment by sebmck** [comment]
All good! Better to be safe than sorry.
