### ISSUE TITLE
Add autoindentation

### ISSUE THREAD

**Issue by sebmck** [6to5/6to5#467]
Detect indentation character/size.

**Comment by sebmck** [comment]
I'm open to techniques to do this. Not willing to use a regex for obvious reasons. Could possibly done by scanning tokens.

**Comment by monsanto** [comment]
The strategy taken by [detect-indent](https://github.com/sindresorhus/detect-indent/blob/master/index.js) seems robust--for each adjacent pair of lines (skipping empty lines), record the difference in indent. Pick the most used indent type.
