### ISSUE TITLE
Request: resolve relative imports

### ISSUE THREAD

**Issue by stefanpenner** [6to5/6to5#471]
```js
// foo/bar/baz.js
import foo from '../bar'`
```

produces:

```js
var foo = _interopRequire(require("../bar"));
```

would be nice/interesting to optionally pre-resolve at build-time (maybe conditionally):

```js
var foo = _interopRequire(require("foo/bar/bar"));
```

this prevents the client from having to do the relatively costly relative resolve if it does not need to.

thoughts?

**Comment by benjamingr** [comment]
Just wondering - what is relatively costly in a relative resolve?

**Comment by stefanpenner** [comment]
@benjamingr just a bunch of string manipulation waling '../../../bar' and then piecing together 'foo/bar/bar'.  It adds up when you have large number of requires. It really isn't a big deal, but it is nice if the client doesn't need to bother with it. As it is already known at build time.

**Comment by phpnode** [comment]
How often does `require()` really get invoked? I'd guess for bigger apps it's at most a few hundred times, at the start of the application lifecycle. We're talking about a tiny one off gain, way less than a ms, it'd be totally imperceptible.

Also it sounds like this would lead to hard to track down bugs, a module should not need to depend on its ability to require itself under a certain name. 

<sub>(It probably took me longer to write this comment than all the collective CPU time such an optimisation would save, in all the apps in the world)</sub>

**Comment by phpnode** [comment]
@stefanpenner doesn't e.g. browserify do this anyway?

**Comment by thejameskyle** [comment]
@stefanpenner I'd be afraid to start manipulating import paths, there's no way we can accommodate all the crazy things people do.

**Comment by sebmck** [comment]
Yeah, I think this is really something up to the module loader. I've rejected requests in the past that have effected the import/export source as it's not really a good road to go down since as @thejameskyle said, they are so many possibilities and requirements.

**Comment by stefanpenner** [comment]
> at the start of the application lifecycle.  We're talking about a tiny one off gain, way less than a ms, it'd be totally imperceptible.

Please remember, app boot is already a precarious and time precious phase of an apps life-cycle. Although it may only be 1 -> 20 ms, these paper-cuts compound with other issues. 

> How often does require() really get invoked? I'd guess for bigger apps it's at most a few hundred times

With larger, well factored apps this number can grow quite large. Individuals should not be penalized for well factored code. The closer modules can become to a zero cost abstraction the better.

> @stefanpenner doesn't e.g. browserify do this anyway?

for people not using browserify, module transpilation time is the ideal oppertunity.

> @stefanpenner I'd be afraid to start manipulating import paths, there's no way we can accommodate all the crazy things people do.

Yes I absolutely agree, let me propose a pluggable hook that would enable optional compile-time resolution of these paths.

```js
options.resolveRequirePath = function(relativeSourcePath, requirePath) {
   return requirePath; // default implementation.
};
```

**Comment by monsanto** [comment]
@stefanpenner can you do this with a [custom module formatter](https://6to5.org/docs/usage/modules/#custom)? you could inherit from CommonJSFormatter.

**Comment by sebmck** [comment]
@monsanto Probably more effort than it's worth, especially since the module formatters aren't exposed via a public API.

**Comment by sebmck** [comment]
@stefanpenner Can you give a description for what each of the parameters would be in your `options.resolveRequirePath` proposal?

**Comment by guybedford** [comment]
From #635 a suggested option is:

```javascript
options.normalize = function(depName) {
  return 'normalized/dep/name';
}
```

**Comment by sebmck** [comment]
`normalize` is a potentially iffy name and I'd like for it to include a reference to module sources in it somewhere. How's:

```javascript
options.resolveModuleSource = function (originalSource) {
  return "normalized/dep/name";
};
```

**Comment by guybedford** [comment]
@sebmck did you mean to include the original dep name as an argument? `normalize` is the name used in the ES6 spec, but resolve works just as well.

**Comment by sebmck** [comment]
@guybedford That would be the `originalSource` argument.

**Comment by guybedford** [comment]
Ah ok great, sorry mistook that for an ast or string source.

**Comment by sebmck** [comment]
Just need a :+1: and I'll push out a new release.

```javascript
exports.resolveModuleSource = function (originalSource) {
  return "resolved/" + originalSource;
};
```

**In**

```javascript
export { foo } from "foo-export-named";
import foo from "foo-import-default";
import "foo-import-bare";
```

**Out**

```javascript
export { foo } from "resolved/foo-export-named";
import foo from "resolved/foo-import-default";
import "resolved/foo-import-bare";
```

**Comment by guybedford** [comment]
Nice!! Would be good to hear from @stefanpenner, but may need to wait a few hours for the timezone.

**Comment by sebmck** [comment]
Available as of 3.2.0

**Comment by stefanpenner** [comment]
> @stefanpenner Can you give a description for what each of the parameters would be in your options.resolveRequirePath proposal?

given:

```js
// bar/foo.js

import a from '../a';
```
relativeSourcePath: `bar/foo`
requirePath: `./a`

**Comment by guybedford** [comment]
@sebmck I'm trying out `resolveModuleSource` in https://github.com/systemjs/builder/blob/master/compilers/es6.js#L50, but it doesn't seem to be getting called for me?

**Comment by sebmck** [comment]
@guybedford Seems to be working for me?

```
require("6to5").transform("import 'foo';", { resolveModuleSource: function () { return "bar"; } }).code;
> '"use strict";\n\nrequire("bar");'
```

Do you have some example input that it's not working on?

**Comment by guybedford** [comment]
Thanks for the quick response, this may well be something silly my side, looking into it and will provide a test case otherwise.

**Comment by guybedford** [comment]
@sebmck ok amazing it is working perfectly :)

**Comment by sebmck** [comment]
Great!
