### ISSUE TITLE
Comment placement not preserved in `function name(/* comment */)`

### ISSUE THREAD

**Issue by Dashed** [6to5/6to5#483]
Comment placement not preserved in the following:

**source**
```js
// no args
function foo(/* some comment */) {
}
```

**6to5 v2.12.0**
```js
"use strict";

function foo() {}
/* some comment */

```

----

This works though:

```js
// have args
function foo( arg /* some comment */) {
}
function foo( /* some comment */ arg) {
}
```

**Comment by sebmck** [comment]
Duplicate of #407

**Comment by Dashed** [comment]
Hmm that's unfortunate.

**Comment by thejameskyle** [comment]
@Dashed Why exactly are you placing comments inside your function params? These issues keep coming up and I can't tell why people are doing it...

**Comment by Dashed** [comment]
@thejameskyle I'm guessing brief annotations. 

I don't do it at the function definition, but when I'm using it, I use comments as brief annotations:

```js
customReactcomponent({}, /* alwaysRender */ true);
```
