### ISSUE TITLE
`let` keyword in for loop semantics differs from Firefox implementation

### ISSUE THREAD

**Issue by coreh** [6to5/6to5#485]
Hi there, first of all kudos for such a great project. I'm really enjoying using it so far. :smile: 

I'd like to report the following inconsistency I stumbled upon: When you use the `let` keyword to declare the iteration variable in a for loop, for example in the following code:

```js
for (let x of [1,2,3]) {
  setTimeout(function() { console.log(x); }, 0);
}
```

6to5 produces the following result:

```js
"use strict";

var _interopRequire = function (obj) {
  return obj && (obj["default"] || obj);
};

var _core = _interopRequire(require("core-js/library"));

for (var _iterator = _core.$for.getIterator([1, 2, 3]), _step; !(_step = _iterator.next()).done;) {
  (function () {
    var x = _step.value;
    setTimeout(function () {
      console.log(x);
    }, 0);
  })();
}
```

When you run this code you get the following output:

```
1
2
3
```

However if you run the original code in Firefox, you get instead:
```
3
3
3
```

The code generated by 6to5 seems to be placing the `x` variable inside the loop block's scope, while Firefox seems to be placing it on the outermost scope. I tried digging through the spec, [this seems to be the relevant section](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-bindinginstantiation). However I'm not familiar with the exact semantics of `CreateMutableBinding`, so I'm not entirely sure if this is a 6to5 bug or a Firefox bug. (Since Firefox has had the `let` keyword for a while, it could possibly be using outdated, pre-ES6 semantics)

Is the current behavior by design or a bug? Thanks in advance for the response.

**Comment by monsanto** [comment]
Firefox is wrong in this case

**Comment by sebmck** [comment]
Thanks! This looks like a bug in Firefox. Let variables as loop initialisers are one of the major use-cases for let variables and you can see [various](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#let_in_loops) [reference](http://es6rocks.com/2014/08/what-you-need-to-know-about-block-scope-let/) where this is documented. The spec section that you linked appears to be the right one.

**Comment by coreh** [comment]
Cool, thanks! Will open a Firefox issue.
