### ISSUE TITLE
Trivial docs formatting issue

### ISSUE THREAD

**Issue by cvrebert** [6to5/6to5#487]
On https://6to5.org/docs/setup/#webpack , it literally says:
> `For additional information on how to troubleshoot **6to5-loader** please see`

The text should presumably get rendered as bolded instead of as surrounded by literal asterisk characters.

**Comment by sebmck** [comment]
Fixed via 2ea0f2c10d27b4440b8021593d066e5faa03db7f. Thanks!

**Comment by cvrebert** [comment]
@sebmck You might want to include a link to that repo somewhere on the site. That way docs bugs can get filed in the correct place.

**Comment by thejameskyle** [comment]
@cvrebert it's on the top right of every page

**Comment by fkling** [comment]
I think @cvrebert means a link to the website repo.

**Comment by thejameskyle** [comment]
Ah, I'm not sure where to put that. Sorry @cvrebert
