### ISSUE TITLE
"readable" example output differs considerably from what's on 6to5.org when using "browser.js"

### ISSUE THREAD

**Issue by kevinb7** [6to5/6to5#488]
I'm working on an ES6 playground similar to the TypeScript playground where people can experiment and see what the output will look like for different code.  I tried using this code from 6to5.org:
```
class User extends Model {
  constructor() {
    super();
    this.sayHello();
  }

  sayHello() {
    alert("Hello World!");
  }
}
```
The output using "browser.js" is this:
```
function User() {
  _get(Object.getPrototypeOf(User.prototype), "constructor", this).call(this);
  this.sayHello();
}

_inherits(User, Model);

_prototypeProperties(User, null, {
  sayHello: {
    value: function () {
      alert("Hello World!");
    },
    writable: true,
    enumerable: true,
    configurable: true
  }
});
```
When I use 6to5 from the command line I get what's on 6to5.org which is:
```
var User = function User() {
  Model.call(this);
  this.sayHello();
};

_inherits(User, Model);

User.prototype.sayHello = function () {
  alert("Hello World!");
};
```
Is this expected behaviour for browser.js?  If so, how do I go about making it produce the same output as the command line version?

Here's a link to a live version of the project I'm working on: http://kevinb7.github.io/es6-playground/

**Comment by sebmck** [comment]
You're using an outdated version of 6to5. There have been a lot of recent changes to the current classes output to make it more spec compliant. Also we currently have a [REPL](http://6to5.org/repl/) which looks like what you're trying to do?

**Comment by kevinb7** [comment]
Yes the REPL is pretty much what I'm looking for, but I'd like to have my own examples that I can go through.  Also, I planning on adding a way to show console output so that I could run the programs.  I'm giving a talk about ES6 next week and I thought it would be better than showing examples on slides.

The version of browser.js that I'm was obtained using "npm install 6to5" and it's version "^2.12.0" which appears to be current.  Should I clone and build from source instead of using npm?

**Comment by sebmck** [comment]
@kevinb7 Yeah the 6to5 REPL executes the code. Take [this](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&code=alert(%22bar%22)%3B) for example. In previous designs there was actually an example selector, it must have been removed. Ping @thejameskyle

**Comment by thejameskyle** [comment]
@sebmck I never finished implementing it. I'll make an issue for it.

**Comment by thejameskyle** [comment]
https://github.com/6to5/6to5.github.io/issues/59
