### ISSUE TITLE
Compile directory to one file, with --modules "system" needs dynamic format

### ISSUE THREAD

**Issue by pgbross** [6to5/6to5#504]
Compiling a `src` directory and output it to the one concatenated file with modules "system" produces an unusable script,  with the browser raising an error "Multiple anonymous System.register calls in the same module file.": eg.

```sh
$ 6to5 src --modules "system" --out-file script.js
```
According to [the Systemjs register extension source](https://github.com/systemjs/systemjs/blob/master/lib/extension-register.js) there are two variations of System.register supported.

1. System.register for ES6 conversion (2-3 params) - System.register([name, ]deps, declare)
2.  System.register for dynamic modules (3-4 params) - System.register([name, ]deps, executingRequire, execute)

6to5 produces the first variation, anonymous System.register calls, of which you cannot have multiple calls in the same module file.

Either 6to5 should not allow compiling to a single --out-file if modules "system" is being requested, or preferably 6to5 should switch to using variation (2) of System.register so that the multiple input files register themselves dynamically.

As a work around, I can compile with --modules "common" and in a separate build step, use [systemjs-builder](https://github.com/systemjs/builder) to "concatenate" the result to a single script for the browser, but it would be good to avoid the extra step.

thanks,
--philip

**Comment by sebmck** [comment]
You can use `--module-ids` to get named modules.

```javascript
$ 6to5 src --module-ids --modules "system" --out-file script.js
```

Let me know if you run into any other issues!
