### ISSUE TITLE
to5Runtime error in Safari (parameter shadows the name of a strict mode function)

### ISSUE THREAD

**Issue by idflood** [6to5/6to5#508]
I'm using webpack + 6to5 without any compression/mangling but in safari (8.0.2) there is this script error:

    SyntaxError: Cannot declare a parameter named 't' as it shadows the name of a strict mode function.

Which correpond to this (just after the declaration of `e._extends = ...`:

    };e.get = function t(r, t, n) {

For background information, my scripts only use these es6 features: class, import and fat arrows.

If I remove the "use strict" declaration at the top of the to5Runtime the script is working. It also works if i change this declartion to `};e.get = function (r, t, n) {` (unnamed function).

**Comment by sebmck** [comment]
Why is the 6to5 runtime being included with use strict in the first place?

**Comment by sebmck** [comment]
Actually, it looks like the 6to5 runtime is being ran through 6to5 itself. You'll have to add the `exclude: /node_modules/` option to your webpack config as documented in the [6to5-loader README](https://github.com/6to5/6to5-loader#usage).

**Comment by idflood** [comment]
Wow, thank you very much, that was exactly this. :+1:
