### ISSUE TITLE
Faster for of on array only code

### ISSUE THREAD

**Issue by lukescott** [6to5/6to5#511]
I'm looking to replace code like this:
```javascript
for (var i = 0, len = array.length; i < len; i++) {
    var item = array[i];
    // ...
}
```
with this:
```javascript
for (var item of array) {
    // ...
}
```

Especially when I need to nest loops.

Currently I have two options. The default, which wraps it in an iterator:
```javascript
for (var _iterator = array[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {
  var item = _step.value;
  // ...
}
```

Or the `--optional forOfFast` option which does this:
```javascript
for (var _loopObject = array,
    _isArray = Array.isArray(_loopObject),
    _i = 0,
    _loopObject = _isArray ? _loopObject : _loopObject[Symbol.iterator]();;) {
  var item;
  if (_isArray) {
    if (_i >= _loopObject.length) break;
    item = _loopObject[_i++];
  } else {
    _i = _loopObject.next();
    if (_i.done) break;
    item = _i.value;
  }
  // ...
}
```

The above is faster (avoids func calls), and works in cases where both arrays and iterators are used. But what I'm looking for is something that transforms it to a simple for(;;) loop, in cases where the author knows that only arrays are used. Something like `--optional forOfArrayOnly`.

I'd be willing to send a PR for this, I'm just unfamiliar with the fast vs loose logic in the codebase, and where exactly this would fit in. So any guidance/feedback would be appreciated, thanks!

**Comment by sebmck** [comment]
Not willing to have something like that. It effectively breaks `for...of` for everything that's not an array. If you really

**Comment by lukescott** [comment]
That's why it's supposed to be an optional transformer. It's only meant for code that does not use iterators. It's especially useful for nested loops, where `for of` greatly increases the clarity of the code, where in such cases I'm defining an item var on each level anyway.

If performance wasn't an issue forEach would be used instead. But in this case I'm trying to reduce the function calls as much as possible. Which `--optional forOfFast` does, but at the cost of increasing the file size. I'm just asking for a more aggressive option, with warning labels attached.

I would expect that when ES6 lands in browsers, `for of` will be just as fast for arrays as a traditional `for` loop.

**Comment by sebmck** [comment]
@lukescott There's no real way to tell potential users that it'll only work on arrays and I feel like it'll lead to confusion where there'll enable it thinking "oh yeah, I use arrays with for of" and then get confused when it doesn't work. 6to5 generates performance-ready code with things like fast rest parameters (#506 etc) and even more relevantly loose mode (#465). In scenarios like this correctness is more important than performance since the fundamentals behind `for...of` are that you use them it iterate over iterators, it seems counterintuitive to have an option that completely changes their behaviour.

Currently all the optional transformers and loose mode provide behaviour that either makes code more loose (removes the 1% edgecases which improves performance) or makes it more spec compliant (by adding the 0.1% edgecases), this changes that dynamic completely.

**Comment by eventualbuddha** [comment]
I don't really see the problem with using `for(;;)` when you're working with very performance sensitive code. Also, I doubt the native implementation of `for of` will be as fast since there's no way for it to avoid checking the type just like we do.

**Comment by lukescott** [comment]
@sebmck I understand where you're coming from, in that you are targeting strict or loose. What about cases that falls outside of that (not just this issue)? Cases where the author is willing to make the compromise? Would you consider a feature that allowed loading external transformers, either from another repo (plugin) or the local project?

@eventualbuddha The biggest penalty are the function calls, which `forOfFast` option address, but does so by increasing the file size. In my case, I know that I don't use iterators, so it makes sense (for me) to transform my `for of` loops into standard `for` loops. The difference between the browser implementation and `forOfFast` is likely to be very small, although I doubt the browser would need to check for isArray on each iteration.

**Comment by sebmck** [comment]
@lukescott If you don't use `for...of` for anything but iterators and you're concerned about performance then it'll always be faster to iterate over it in a `for`.

**Comment by monsanto** [comment]
@lukescott, since readability is a concern, can you just use `forOfFast` for production builds?

**Comment by lukescott** [comment]
@monsanto Yep, that's what I'll do. I was just looking for a way to cut out the unnecessary iterator logic for a project that only iterates over arrays.
