### ISSUE TITLE
es6 classes: how to call prototype.function of child class in child class

### ISSUE THREAD

**Issue by ms88privat** [6to5/6to5#517]
Hello Guys,

maybe I am a bit confused right now, but how to call a prototype.function inside another prototype.function of the child class?

Normally I would do "childclass.prototype.function.call(this)". In es6 I do "this.function". This is working until i got a parent class with the same function, then this parent.function is called instead.

Is there an other keyword like super available?

Thank you

**Comment by eventualbuddha** [comment]
You can use `super` to call the base class implementation of any method, yes. See https://github.com/lukehoban/es6features/blob/master/README.md#classes.

Also, feel free to stop by the Gitter room to ask these sorts of questions.
