### ISSUE TITLE
Error handling in async functions

### ISSUE THREAD

**Issue by valeriangalliat** [6to5/6to5#520]
I know async functions are an experimental feature, but I didn't found any issue about this, nor "known bugs".

So, errors are muted in async functions:

```js
async function a() {
  foo();
  bar = 42;
}

function b() {
  baz();
}

a();
b();
```

```sh
6to5-node --experimental test.js
```

It will throw `ReferenceError: baz is not defined` while both undefined function and variable errors are present in the async function `a`.

**Comment by sebmck** [comment]
This is expected behaviour of async functions. They return a `Promise` that you have to bind to.

```javascript
async function a() {
  foo();
  bar = 42;
}

function b() {
  baz();
}

a().then(function (result) {

}, function (err) {

});
b();
```

**Comment by valeriangalliat** [comment]
Oh my bad, the actual problem was while I had an error handler, there was also an undefined function error in it and that's why it got muted. :/

Is there a "best practice" to avoid muted errors in promise error handlers? Thank you @sebmck!

**Comment by sebmck** [comment]
No problem! You really only need an error handler for the initial async function call, once you have that all inner `await` errors etc will bubble up to the initial call.
