### ISSUE TITLE
Compile with dependencies?

### ISSUE THREAD

**Issue by trusktr** [6to5/6to5#523]
Hello, I have a bunch of things I want to put into an object and attach it to a global. So what I thought I could do is import all my modules into a single file

```js
// infamous.js
import Calendar         from 'Calendar'
import Cube             from 'Cube'
import DoubleSidedPlane from 'DoubleSidedPlane'
import Grid             from 'Grid'
import Molecule         from 'Molecule'
import Plane            from 'Plane'
import PushMenuLayout   from 'PushMenuLayout'
import * as utils       from 'utils'

export {
    Calendar         as Calendar,
    Cube             as Cube,
    DoubleSidedPlane as DoubleSidedPlane,
    Grid             as Grid,
    Molecule         as Molecule,
    Plane            as Plane,
    PushMenuLayout   as PushMenuLayout,
    utils            as utils
}
```

then compiling it by doing

```js
./node_modules/.bin/6to5 ./infamous.js --source-maps --out-file ./global.js --modules umd
```

I was hoping it would pull all the dependencies into the final output, but that's not the case. Is there a way?

**Comment by sebmck** [comment]
You'll have to use browserify and [6to5ify](https://github.com/6to5/6to5ify). 6to5 will just convert the module syntax to the relevant module loader (by default it's CommonJS). There's currently an issue open (#495) that deals with automatically bundling dependencies together but it's an extremely tough problem.

**Comment by trusktr** [comment]
True, maybe that's better left to browserify, webpack, jspm, etc.

/#!/JoePea

**Comment by djindjic** [comment]
by my little research, jspm doesnt allow bundling to any module format then system.register. @trusktr, do you have some workflow to do this with jspm?

**Comment by trusktr** [comment]
@djindjic I'm not quite sure what you mean. I write in ES6 for example, then jspm allows me to import any module type into my code. Ultimately what I really care about is that it all runs in the browser, regardless of what mix of module formats the libraries are. I'm trusting jspm to bundle and minify everything into an efficient piece of code. :D

**Comment by djindjic** [comment]
Oh sorry, I was reading about that theme and didn't mention that you do not export to amd. I am trying to use jspm as you do, write es6 and import any other format, but at the end want to bundle it as and amd moduls build to use it in an existing app which is pretty hardcoded and I cant put jspm into it side by side because requirejs throws mismatch errror if there is any other module loader exists http://requirejs.org/docs/errors.html#mismatch. Do you have any idea what you will do in this situation @trusktr?

**Comment by trusktr** [comment]
@djindjic I'm using 6to5 (gotta update to babel) to compile my code to AMD if I need to use it in a RequireJS project: https://github.com/infamous/infamous/blob/master/package.json#L15

You want the package management of JSPM, but for it to run in a RequireJS environment?

**Comment by djindjic** [comment]
yes, I want to use jspm's format agnostic imports to develop angular directives library, and bundle/deploy it as amd or global module.

**Comment by trusktr** [comment]
So with my lib I just write in ES6. Then on prepublish it compiles into CommonJS for use with most libraries, and with the build-amd script someone using RequireJS could easily call that script with grunt or similar. I'm leaving it up to the end user to determine what format he wants my lib to be in for his particular project. The end user's project may or may not use jspm. He might use Webpack, Browserify, RequireJS, etc.

In my opinion, it shouldn't be your library's task to pre-bundle all dependencies for the end user.

That being said, you can use Babel (formerly 6to5, now Babel is more general purpose) to compile your libs to AMD format like the build-amd script in my lib's package.json. Then, treat your lib like an application by using something like Grunt or Gulp to compile a bundle. That'll handle your AMD case.

If you want a global, you should rather use CJS or ES6, then require/import everything of your lib into a single file, then make a bundle of that file using browserify, jspm, or webpack. In that bundle file, after you've imported everything, you can set a variable like

```js
import foo from 'myLib/foo'
import bar from 'myLib/bar'
import baz from 'myLib/baz'

window.myLib = {
  foo: foo,
  bar: bar,
  baz: baz
}
```

With jspm you can then make a "self executing bundle". You can also make self executing bundles with webpack or browserify. When your bundle runs in the page, it'll set window.myLib.

Now `myLib` is a global. :)
