### ISSUE TITLE
Flow-style optional parameters throw syntax error

### ISSUE THREAD

**Issue by ianobermiller** [6to5/6to5#524]
```js
function a(b?: Object) {}
```

Since you will often use a default parameter anyway a possible workaround is:

```js
function a(b: Object = {}) {}
```

Flow documentation: http://flowtype.org/docs/functions.html#function-based-type-annotations

**Comment by sebmck** [comment]
Thanks!

**Comment by sebmck** [comment]
Fixed as of [2.13.0](https://github.com/6to5/6to5/blob/master/CHANGELOG.md#2130).
