### ISSUE TITLE
TDZ issues

### ISSUE THREAD

**Issue by UltCombo** [6to5/6to5#527]
So 6to5 v2.13.1 started checking for early TDZ errors regarding block bindings, which is very nice!

However, here are some issues I've found:

Should throw:
```js
let x = x;
```

Should throw:

```js
f();
let x;
function f() {
	x;
}
```

Should **not** throw:
```js
function f() {
	x;
}
let x;
f();
```

All of the above test cases are currently failing in v2.13.1. Naive static analysis comparing line/col numbers such as implemented in [`7c47017`](https://github.com/6to5/6to5/commit/7c4701716c2b228e372a3b8cee7d64322242efc9#diff-990fc5a5174ab68cb2de02790f26a4a9R137) is rather error-prone as seen in the examples above, even to the point of giving false positives which is a huge issue IMO.

To cover all the cases above properly, we'd need runtime assertions. My suggestion would to split TDZ checking from the default block binding transformer, and have an option to enable runtime TDZ assertions.

**Comment by sebmck** [comment]
I kind of shoehorned them in there because it was requested in the gitter chat, probably should have left it out until it was more solid.

**Comment by UltCombo** [comment]
Awesome, thanks!

**Comment by sebmck** [comment]
Woops, referenced the wrong issue with ca41612109883b2bfd3979cc9afa63d372805c03

**Comment by sebmck** [comment]
Released as of 2.13.2, thanks!

**Comment by stefanpenner** [comment]
As this issue is closed, should I expected TDZ semantics in babel today?

in v8:

```js
let x = x;
```

```
Uncaught ReferenceError:  x is not defined
```

via babel transpile:

```js
var x = x; // output, and no TDZ error
```

**Comment by hzoo** [comment]
@stefanpenner sorry this should be better documented but it was a separate transform. In babel 6 it's under an option

```js
{
  "presets": [],
  "plugins": [
    ["transform-es2015-block-scoping", { "tdz": true }]
  ]
}
```

```
  throw new ReferenceError("x is not defined - temporal dead zone");
  ^

ReferenceError: x is not defined - temporal dead zone
```
