### ISSUE TITLE
mangled percent sign in strings

### ISSUE THREAD

**Issue by chocolateboy** [6to5/6to5#528]
6to5: 2.13.1
node.js: v0.11.14
Ubuntu 14.04

###### percent.js

```javascript
sprintf('productivity in %d has increased by 30%%', year);
sprintf("productivity in %d has increased by 30%%", year);
```

###### output (6to5 ./percent.js)

```javascript
"use strict";

sprintf("productivity in %d has increased by 30%", year);
sprintf("productivity in %d has increased by 30%", year);
```

The trailing `%` has gone AWOL (which, in this case, breaks the format string).

It seems to run OK under 6to5-node.

**Comment by sebmck** [comment]
Fixed via ca41612109883b2bfd3979cc9afa63d372805c03 and released as of 2.13.2, thanks!
