### ISSUE TITLE
Can't use version higher than 2.0.4

### ISSUE THREAD

**Issue by terrybleger** [6to5/6to5#531]
Hi,

I'm just wondering,

I'm running 6to5 using this kind of script:

```
#!/usr/bin/env sh

exec /usr/local/bin/n as 0.11.14 --harmony /usr/local/bin/6to5-node --playground "$@"
```
so that I can use it for Phusion Passenger + Nginx.

Now, this simple codes always throws ``` TypeError: undefined is not a function ```
```
"use strict";

let list = [1, 2, 3, 4, 5];

for (let item of list.values()) {
                              ^
}
```

The highest version that I'm able to use it without "any errors for unknown reason" is 2.0.4.
kexec 0.2.0 is always failed to compile. And even if I'm using kexec 1.0.0 which compiled without any error, it didn't make the "unknown reason error" disappear anyway.

Also the latest version 2.13.1 can even worse (which I don't know the reason why),
``` Temporal dead zone - accessing a variable before it's initialized ```
```
for (let item of list.values()) {
  let workspace = workspaces[item.name];
                            ^
}
```

I dont't seem to find people that have the same issue like mine, so please tell me where did I go wrong?
```
Node version: 0.11.14
Node version manager: n
6to5 versions: 2.0.4 (fine), 2.1.0 to 2.13.1 (bad)
OS: Mac OS X 10.10.1
```

OOT:
Anyway for whatever reason or version I'm using it, "Iterators + For..Of"
```
// WORKING
for (let item of list.values()) {
  console.log(item);
}

// NOT WORKING, but using Traceur this code is fine
for (let item of list) {
  console.log(item);
}
```

**Comment by sebmck** [comment]
I added TDZ in 2.13.1 and I'm probably going to remove it because it's extremely naive (see #527). kexec is an optional dependency so you don't need it, it's only to propagate signals nicely with the forked node process.

**Comment by UltCombo** [comment]
IIRC `[].values()` was backed out of ES6 due to web-compat stuff.
You should be able to do `for (let item of list)` though.

**Comment by terrybleger** [comment]
@UltCombo 

Thanks man, I didn't know that. That fix the error.

Wow, I need to refactor a lot then.

OK, I will test my all codes again, if all is well then I will close this issue.

**Comment by sebmck** [comment]
I pushed out a new version that removes the TDZ stuff so be sure to test it on that version (2.13.2)

**Comment by terrybleger** [comment]
@sebmck 

Will test this. Thanks.

**Comment by terrybleger** [comment]
I kinda give up, I can't seem to find the source of the problem. And since I can't debug it, it's really hard.

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Script7CompileENS_6HandleINS_6StringEEEPNS_12ScriptOriginEPNS_10ScriptDataE
  Referenced from: /Users/xXx/.nvm/v0.11.14/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.3/node-v14-darwin-x64/debug.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Script7CompileENS_6HandleINS_6StringEEEPNS_12ScriptOriginEPNS_10ScriptDataE
  Referenced from: /Users/xXx/.nvm/v0.11.14/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.3/node-v14-darwin-x64/debug.node
  Expected in: dynamic lookup
```

I have this kind of codes: (this is really weird)
```
console.log(list[0]) // WILL log the item at index 0
for (let item of list) {
  console.log(item); // WILL log the item as undefined
  let workspace = workspaces[item.name]; // WILL throws exception since item is undefined
  if (workspace) {
    places.push(workspace);
  }
}
```
It's really hard to reproduce, since if I tested it using a simple script it works just fine. But inside my real codes, it's isn't.

I think I will stick with 2.0.4 since it's the only highest version that worked just fine.

**Comment by UltCombo** [comment]
This may sound like a silly question, but did you include the polyfills? What browser/node.js version are you running the code on?

**Comment by zloirock** [comment]
@UltCombo I remember this issue, but [`Array#values`](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-array.prototype.values) currently in ES6.

**Comment by terrybleger** [comment]
@UltCombo 

Actually I already describe it in my first comment.

```
Node version: 0.11.14
6to5 versions: 2.0.4 (fine), 2.1.0 to 2.13.1 (bad)
OS: Mac OS X 10.10.1
```

The way I'm running it is by using this script:
```
#!/usr/bin/env sh

exec /usr/local/bin/n as 0.11.14 --harmony /usr/local/bin/6to5-node --playground "$@"
```

```
6to5-awesome app.js
```

**Comment by terrybleger** [comment]
@UltCombo 

If I'm using v2.1.0 above ``` for (let item of list) ``` fixes error in my first comment. https://github.com/6to5/6to5/issues/531#issue-54711352

But, there's another issue if I'm using that version above, which I describe it in https://github.com/6to5/6to5/issues/531#issuecomment-70436523

**Comment by sebmck** [comment]
You're using 0.11.14 which is an unstable version. A lot of ES6 features are broken on it and it's not very spec compliant so it's best to just use a stable release. The error you're getting is a v8 one so it's not related to 6to5.

**Comment by terrybleger** [comment]
@sebmck 

1. The reason I have to use 0.11.x is because I'm using it for Koa.
2. I don't know if it's 100% v8 problem, but 6to5 v2.0.4 below don't have the problem in my https://github.com/6to5/6to5/issues/531#issuecomment-70436523

**Comment by sebmck** [comment]
@terrybleger 

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Script7CompileENS_6HandleINS_6StringEEEPNS_12ScriptOriginEPNS_10ScriptDataE
  Referenced from: /Users/xXx/.nvm/v0.11.14/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.3/node-v14-darwin-x64/debug.node
  Expected in: dynamic lookup
```

is definently a V8 error.

**Comment by terrybleger** [comment]
@sebmck 

My knowledge about v8 is very little. But that error only raised when using node-inspector.

**Comment by sebmck** [comment]
Current Node unstable includes a v8 that has Symbols. That error message is definently something internal as it doesn't contain a stack trace and it's referencing internals. 6to5 has support for generators but I understand wanting to use the native implementation if it's available, unfortunately there's no real way to patch 6to5 so it doesn't use broken native implementations of certain things.

**Comment by sebmck** [comment]
This may have been fixed in a more recent version of V8 though so it's possible that in io.js this issue doesn't exist.

**Comment by UltCombo** [comment]
@zloirock true that there has not been full consensus in backing it out of ES6 yet, but:

- Chrome/V8 had implemented `Array#values`, but backed it out soon after due to web-compat: https://codereview.chromium.org/455763002/
- Glancing the [ES Discuss thread](https://esdiscuss.org/topic/array-prototype-values-is-not-web-compat-even-with-unscopables) again, looks like the discussion hasn't reached a resolution yet.

TBH, I'm not sure what is the current state of affairs.

**Comment by UltCombo** [comment]
According to these [meeting notes](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-11/nov-18.md#44-arrayprototypecontains-breaks-mootools), looks like `Array#values` is going to stay indeed. (although the V8 shipped with io.js still hides `Array#values`)

IIRC @domenic has made a proposal addressing the general extension of built-ins problem, but I can't seem to find it nor its status at the moment.

**Comment by zloirock** [comment]
@UltCombo Yes, I saw all of this. The main - it's contains in polyfill. About proposals - IIRC, it was before `.contains` -> `.includes`.

**Comment by UltCombo** [comment]
@zloirock  I'm aware `.contains` was dropped and `.includes` is proposed for ES7, but that's not actually the point -- I've linked to the [`.contains` meeting notes](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-11/nov-18.md#44-arrayprototypecontains-breaks-mootools) because it also contains discussion about `.values`, more specifically, it mentions IE is shipping `Array#values` and thus decision to still roll it out in ES6.

Also, the thread you've linked contains just a few quick and dirty hacks -- that's not actually the proposal I mentioned. @domenic has evolved that into an actual proposal to bring up with TC39, containing a far more vast array of actual solutions to this generic problem. This is the proposal that I can't seem to find.

**Comment by sebmck** [comment]
Closing this as I'm pretty confident that this isn't a 6to5 issue. Feel free to reopen or create another issue if you're still having trouble. Sorry I couldn't be of more help!

**Comment by zloirock** [comment]
@UltCombo I can not imagine such a universal solution to this problem. If you will find this proposal - show me, interesting.

**Comment by UltCombo** [comment]
@zloirock I've revived that old [ES Discuss thread](https://esdiscuss.org/topic/array-prototype-contains-solutions) in hopes to find the proposal, but it looks like my memory tricked me -- that thread seems to be the latest discussion on the topic, my bad.

It is still sad that that simply choosing names in hopes that they do not collide with existing code is the "state of the art" for extending built-ins. But anyway, that is going a bit too off-topic for this issue, we can continue that discussion in ES Discuss. :smile_cat:

**Comment by terrybleger** [comment]
Finally I found the problem. It was regenerator. Once I blacklist it, the problem goes away.

Thanks.
