### ISSUE TITLE
Destructuring objects with string literal keys

### ISSUE THREAD

**Issue by msvbg** [6to5/6to5#532]
```js
let { 'foo': bar } = { foo: 99 } // Fails to compile
let { foo: bar } = { foo: 99 } // Works
```

Is this intended behavior?

**Comment by thejameskyle** [comment]
This is currently working in the online REPL. Try updating 6to5.
http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&code=let%20%7B%20'foo'%3A%20bar%20%7D%20%3D%20%7B%20foo%3A%2099%20%7D
