### ISSUE TITLE
REPL: Can't use console.log() in IE 9

### ISSUE THREAD

**Issue by webbedspace** [6to5/6to5#539]
`console.log.apply(console, ...)`, which is apparently called internally by the REPL, causes an error in IE 9.

**Comment by sebmck** [comment]
@webbedspace Can I get a stack trace?

**Comment by thejameskyle** [comment]
I'll take a look at this in a VM when I get home tonight.

**Comment by webbedspace** [comment]
@sebmck It's repl.js, line 89.

**Comment by sebmck** [comment]
@webbedspace I know what line it's on but it's difficult to isolate the issue without an actual error message or stack trace.

**Comment by webbedspace** [comment]
Looked closer - here's a solution you could use:
![](http://i.imgur.com/rINYAtN.png)

**Comment by thejameskyle** [comment]
Thanks @webbedspace for that solution
