### ISSUE TITLE
typeof Object(Symbol()) isn't correct

### ISSUE THREAD

**Issue by webbedspace** [6to5/6to5#540]
I tried compiling the `Object(symbol)` test from the compat table in 2.13.3. It produced this output:
```
"use strict";
var _typeof = function(obj) {
    return obj && obj.constructor === Symbol ? "symbol" : typeof obj;
};
(function() {
    var symbol = Symbol();
    var symbolObject = Object(symbol);
    return (typeof symbolObject === "undefined" ? "undefined" : _typeof(symbolObject)) === "object" && symbolObject == symbol && symbolObject.valueOf() === symbol;
});
```
The provided `_typeof` function is wrong: it returns "symbol" for symbolObject even though it should be "object".

**Comment by sebmck** [comment]
That's an issue with [core-js](https://github.com/zloirock/core-js).

**Comment by zloirock** [comment]
How do you propose to realize the difference between the `Symbol()` and `Object(Symbol())`? [The question has been raised](https://github.com/zloirock/core-js/issues/16), I do not see solutions.

**Comment by sebmck** [comment]
Closing this as it's not a 6to5 core issue. Use zloirock/core-js#16 for further discussion. Thanks!
