### ISSUE TITLE
Closure Compiler annotations

### ISSUE THREAD

**Issue by Naddiseo** [6to5/6to5#546]
Here's an idea for new transformation: adding closure compiler annotations.

**Comment by sebmck** [comment]
Can you give an example?

**Comment by Naddiseo** [comment]
Overview of all annotations: https://developers.google.com/closure/compiler/docs/js-for-compiler
Some cases I can think of:

Classes:
```javascript

class Foo {
    constructor(a: Number) {}
}
class Bar extends Foo {}

// becomes something like:
/** 
@constructor
@param{Number} a
*/
function Foo(a) {}
/**
@constructor
@extends {Foo}
*/
function Bar() {}
```
If type annotations are available:
```javascript
var a : String = 'a';
//becomes
/** @type {string} */
var a = 'a';

function fn(a: Number) :String { return 'num' + a; }
// becomes
/**
@return {string}
@param{Number} a
*/
function fn(a) { return 'num' + a; }
```

Const:
```javascript
const foo = 'FOO';
//becomes
/** @const */
var foo = 'FOO';
```

**Comment by sebmck** [comment]
So JSDoc comment generation with types then, right? Related #220

**Comment by Naddiseo** [comment]
Yeah, similar I suppose. Except that the closure annotations can be inline as well as in the jdoc comment, so there would be less need to parse/merge jdoc comments (which was one of the reasons given for not implementing #220). 

I would give this a go myself, but I don't really understand how comments are handled in the transformations. I attempted to something similar with jshint comments some time ago, but couldn't get comments to show up in the output.

**Comment by sebmck** [comment]
I don't think there's enough of a use-case for this to warrant implementing it. Happy to be proven wrong however, thanks!

**Comment by lennel** [comment]
Closure compiler has tree-shaking, something which is extremely important to a set of people. I would love to use your tool, but given that I can't pass along type information to the closure compiler, which in turn makes the compielr ignorant and not as powerful, the tool sadly will not work for us.

**Comment by sebmck** [comment]
@lennel You can totally pass along type information to the closure compiler. All comments are retained.

**Comment by lennel** [comment]
ah, I misread here someone wanted an automatic plugin. perfect, thanks.

**Comment by underbyte** [comment]
@sebmck I'm trying to get babel and Closure compiler annotations to work together but babel is stripping these parenthesis when using type cast. When type casting the object must be wrap in parenthesis after the comment.

Ex:
```
function test (a,b) {
  /** @type {Object} */ (b);
  new Foo(/** @type {Object} */ (b), this);
 return /** @type {Object} */ (b);
};
```
Output:
```
"use strict";

function test(a, b) {
  /** @type {Object} */b;
  new Foo( /** @type {Object} */b, this);
  return (/** @type {Object} */b
  );
};
```

There seems to be two behaviors here one where the parenthesis are stripped or moved out of order. Any suggestions?
