### ISSUE TITLE
Template string after arrow function gets included in the function

### ISSUE THREAD

**Issue by goatslacker** [6to5/6to5#548]
Template literal gets included in the body of an arrow function

![screen shot 2015-01-20 at 1 09 05 pm](https://cloud.githubusercontent.com/assets/10632/5826179/97379d94-a0a5-11e4-9aeb-9f4924398160.png)

It's fine if you include a semicolon.

![screen shot 2015-01-20 at 1 10 30 pm](https://cloud.githubusercontent.com/assets/10632/5826200/b9e1b7a8-a0a5-11e4-81f0-999c2dfc9664.png)

Is this a fun new ASI issue?

**Comment by goatslacker** [comment]
It's fine if you include a semicolon.

![screen shot 2015-01-20 at 1 10 30 pm](https://cloud.githubusercontent.com/assets/10632/5826200/b9e1b7a8-a0a5-11e4-81f0-999c2dfc9664.png)

**Comment by goatslacker** [comment]
Is this a fun new ASI issue? :)

**Comment by sebmck** [comment]
It's being parsed as a tagged template literal (as you can see) due to ASI. Just use semicolons, it's easier that way.
