### ISSUE TITLE
io.js Support

### ISSUE THREAD

**Issue by corbinu** [6to5/6to5#551]
Looks like kexec needs to be updated to the most recent version which supports io.js

**Comment by sebmck** [comment]
I've upgraded the package to latest (1.1.0). It'll be available in the next release since this isn't urgent as it's only an optional dependency and 6to5 can be installed without it. Thanks!

**Comment by corbinu** [comment]
Thanks

**Comment by sebmck** [comment]
Ended up pushing out a new release due to #550 anyway. Fixed as of 2.13.5
