### ISSUE TITLE
Web Worker support

### ISSUE THREAD

**Issue by guybedford** [6to5/6to5#553]
I just tested 6to5 `browser.js` in a web worker, and it seems there is an error with `cannot read property prototype of undefined`.

**Comment by sebmck** [comment]
Do you have a stacktrace handy?

**Comment by guybedford** [comment]
Unfortunately the stack trace was crashing my inspector for some reason, it may help to test against unminified source though.

**Comment by sebmck** [comment]
Looks like it's due to lodash using either `window` or `this` when it should also be looking for `self`. I've commented [here](https://github.com/lodash/lodash/issues/313#issuecomment-71365917) for assistance.

**Comment by guybedford** [comment]
Thanks so much for tracking this down. I see lodash 3 has just been released.

**Comment by sebmck** [comment]
Should be fixed by #595, thanks!
