### ISSUE TITLE
`this` value in module code

### ISSUE THREAD

**Issue by fkling** [6to5/6to5#562]
[According to the spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-module-environment-records), the value of `this` inside a ModuleEnvironment is supposed to be `undefined`.

However, currently the value of `this` module depends on how the module loader evaluates the module code. For example, `this` refers to `module.exports` in Node.js (which includes `6to5-node`).

A possible solution would be to wrap every module in an IIFE:

```js
(function() {
  "use strict";
  // module code
}());
```

That said, it's not 100% clear to me when a source should be evaluated as "module" and when as "script". But based on the spec it seems that any source containing an `import` or `export` declaration has to be considered as a module.
And I guess logically, CJS modules should be considered "modules" as well.

**Comment by sebmck** [comment]
6to5 assumes that all code given to it is a module since it tranpiles `export` and `import` statements. See my [previous comment](https://github.com/6to5/6to5/issues/560#issuecomment-70910848) for an alternative solution that would be safer for developers:

> An alternate solution would be to just throw an error whenever we see any top level `this` expressions. It'd negate the need for a closure and would be more safe as under no circumstance would you reference `this` while it equaling `undefined`.

**Comment by fkling** [comment]
> An alternate solution would be to just throw an error whenever we see any top level `this` expressions. 

Which however would not help with the case mentioned in the other issue:

```js
module.exports = {
    x: 'X',
    getX: () => {
      return this.x;
    }
};
```

**Comment by sebmck** [comment]
@fkling The `this` within the arrow function would still be defined as "top level". I'd traverse the AST and skip all function declarations and function expressions and throw on any instance of `ThisExpression`. So basically the following verbatim:

```javascript
exports.FunctionDeclaration =
exports.FunctionExpression = function (node, parent, scope, context) {
  context.skip();
};

exports.ThisExpression = function (node, parent, scope, context, file) {
  throw file.errorWithNode(node, "Top level `this` is not allowed");
};
```

**Comment by fkling** [comment]
Thanks for the clarification :+1:

**Comment by sebmck** [comment]
Added in the 3.0.0 branch.

**Comment by sebmck** [comment]
Fixed as of 3.0.0

**Comment by mmocny** [comment]
I'm trying to transpile some browser code, where top-level `this` maps to `window`.  6to5 is now throwing for this case.

Specifically, the use of top-level `this` is being automatically introduced in my code by the `vulcanize --csp` tool.

Its possible they should not be using top-level `this`, but its worked thus far and works in browsers, so I'm inclined to think 6to5 should support this.

wdyt?

**Comment by eventualbuddha** [comment]
Can you give us a more concrete example? It may be that you should simply be running `vulcanize` after transpiling with 6to5.

**Comment by mmocny** [comment]
Thats a good workaround, I'll try it.

I was running 6to5 after vulcanize since vulcanize inlines an unknown subset of my bower_components, and I would prefer not to just blindly transpile all of those first.

**Comment by mmocny** [comment]
Some more info, not sure if it will help past the original explanation:

Error:
```
ReferenceError: /Users/mmocny/dev/v2apps/sensortag/dist/index.js: Line 3193: Top level `this` is not allowed
  3191     |         parse: parse
  3192     |     };
> 3193     | })(this);
           |    ^
  3194     |
  3195     | // Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
  3196     | // This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
    at File.errorWithNode (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/file.js:297:13)
    at Object.exports.ThisExpression [as enter] (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/transformation/transformers/other/use-strict.js:20:14)
    at transformVisitor.enter (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/transformation/transformer-pass.js:50:16)
    at TraversalContext.enterNode (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:65:16)
    at TraversalContext.visitNode (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:117:15)
    at TraversalContext.visit (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:150:26)
    at traverseNode (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:171:17)
    at TraversalContext.visitNode (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:130:5)
    at TraversalContext.visit (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:142:17)
    at traverseNode (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:171:17)
    at TraversalContext.visitNode (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:130:5)
    at TraversalContext.visit (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:150:26)
    at traverseNode (/Users/mmocny/dev/v2apps/sensortag/node_modules/gulp-6to5/node_modules/6to5-core/lib/6to5/traverse/index.js:171:17)
```

Original code after vulcanization:
```
(function (global) {
    'use strict';

   // OMITTED lots of code
})(this);
```

**Comment by mmocny** [comment]
Seems running 6to5 before vulcanize doesn't help, because the use of top-level this is actually part of the polymer implementation.  It wasn't being introduced by vulcanize as I thought, it was just concatenated as-originally-written.

**Comment by eventualbuddha** [comment]
Running 6to5 against 3rd party code is probably not a good idea, unless you know that code is ES6 and followed the expected module semantics. Try running it against only your own code before combining it with the 3rd party code.

**Comment by sebmck** [comment]
@mmocny In ES6 modules `this` is `undefined` and not the global scope. You shouldn't be running 6to5 over code that isn't ES6 in the first place.

**Comment by mmocny** [comment]
Thanks for that clarification!  That makes sense and I'll update my build script to only transpile the filtered set of js.

**Comment by timoxley** [comment]
Yeah I've got a similar problem to @mmocny with the vulcanize transformer, but I'm using  https://www.npmjs.com/package/with before 6to5. `with` tries to pass the current value of `this` along to the function it creates – a totally safe and intended operation even if `this` is undefined: what harm is done if there's never any property access on `this`, or if the code has an explicit handling for `typeof this === undefined`. And even if you do try to access a property on `this`, the error is immediately apparent, I'm not sure how valuable this is.

Sure, I could disable `useStrict` transformer and I will do that for now, but this seems like overly opinionated code policing. 6to5 should probably just stick to the spec and let people shoot themselves in the foot if they want to.

**Comment by timoxley** [comment]
Perhaps a good middle ground would be to reduce this to a warning.

**Comment by eventualbuddha** [comment]
In esperanto we simply change references to `this` to a literal `undefined`. That might be appropriate.

**Comment by fkling** [comment]
> In esperanto we simply change references to `this` to a literal `undefined`. That might be appropriate.

That sounds very reasonable. :+1:

**Comment by sebmck** [comment]
The entire reason that it was changed is because there's no circumstance where you'd use `this` legitimately and expect `undefined`. Many people who would be switching to ES6 would have no idea about the implicit strict mode and that `this` is not the global `window`. I'd rather protect those users than inconvenience those who want to use it for whatever reason.

**Comment by fkling** [comment]
@sebmck: How about replacing top-level `this` with `undefined` **and** show a warning? Something like

> WARNING: Dangerous use of `this`. Module level `this` is `undefined`.

Replacing it with `undefined` would definitely be closer to the spec.

**Comment by sebmck** [comment]
@fkling Outputting warning messages seems like a slippery slope that I'm not sure I want to go down.

**Comment by sebmck** [comment]
If there's a legitimate use-case for wanting to use `this` at the top level then I'll consider it but it's safer to just throw an error.

**Comment by fkling** [comment]
> but it's safer to just throw an error.

Sure, but that's not what environments that support ES6 modules will do either. I think such validation should be done by a linter, not a transformer.

**Comment by sebmck** [comment]
Sure, but if it can be done at compile-time and protects developers then why shouldn't it?

**Comment by jridgewell** [comment]
:+1: to replacing with `undefined`. While it's unlikely to ever be useful, it does match the spec and I think that's way more important.

**Comment by sebmck** [comment]
Unless a more compelling argument can be put forth I'm not willing to change it, sorry. This change has already paid off as it's already caught quite a few people running their vendor code through 6to5 as well as some developers expecting `this` to be `window` or `exports`. I'll possibly move this into another transformer so you can more easily blacklist it (currently it's in the `useStrict` transformer).

**Comment by hughsk** [comment]
@sebmck in this case, 6to5 is producing a compile-time error which won't *always* result in a runtime error. What if we were transpiling a snippet of ES6 and running it within another context? Are we assuming that 6to5 is always transpiling modules?

I'm not sure it's worth the tradeoff in protecting developers when it's causing valid ES5 code to throw at compile-time, that's kind of surprising and not nice for beginners either.

**Comment by sebmck** [comment]
> Are we assuming that 6to5 is always transpiling modules?

Yes, that's where the implicit strict mode comes from. Otherwise it's a script in which case there are some even weirder strict mode rules.

**Comment by sebmck** [comment]
To expand on this, transforming to undefined in the case you bought up
isn't a solution then since this can be whatever.

On Sunday, 1 February 2015, Hugh Kennedy <notifications@github.com> wrote:

> @sebmck <https://github.com/sebmck> in this case, 6to5 is producing a
> compile-time error which won't *always* result in a runtime error. What
> if we were transpiling a snippet of ES6 and running it within another
> context? Are we assuming that 6to5 is always transpiling modules?
>
> I'm not sure it's worth the tradeoff in protecting developers when it's
> causing valid ES5 code to throw at compile-time, that's kind of surprising
> and not nice for beginners either.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/6to5/6to5/issues/562#issuecomment-72349300>.
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment]
After some deliberation and discussion on gitter I've decided to make top level `this` map to `undefined` as of 3.3.3.

**Comment by mmocny** [comment]
Woot.  Glad about the change, but curious what convinced you?

**Comment by sebmck** [comment]
@mmocny Just needed some time to think about it and weigh the pros and cons. I'm happy to listen to any criticism with any of my decisions as it effects the users more than it does me.

**Comment by mmocny** [comment]
This is a great quality to have!

**Comment by jasonkuhrt** [comment]
This issue has been a real blocker when deps do not compile. And the idea that deps should never go through compile is also problematic: https://github.com/6to5/6to5-loader/issues/28.

**Comment by sebmck** [comment]
@jasonkuhrt You should only be passing ES6 code to 6to5.

**Comment by chipironcin** [comment]
Hi guys! I found this problem in my code and I wish babel warns me or have an option to fail like it did if detects that `this` is being transformed to `undefined`.
There is no way for me to notice it was transpiled to `undefined` until I call it and fails.
