### ISSUE TITLE
Block scoping temporal dead zones

### ISSUE THREAD

**Issue by tolmasky** [6to5/6to5#563]
Basically, in ES6 lets *don't* hoist, but with 6to5, they do. This leads to this innocent snippet:

```javascript
    i
    let i;
```

Working fine in 6to5, but actually being a ticking time bomb when you move to a real ES6 environment where it throws a "Reference Error not defined" and takes down the entire script because lets don't hoist. This seems particularly bad because its not a feature not working that then does work, but quite the opposite, a feature working that then crashes.

I haven't thought about it deeply yet, but I *think* its actually syntactically apparent when the variable is in the "temporal dead zone", and could simply be syntactically replaced with a throw:

```javascript
    i
    let i;
```
--->
```javascript
    throw "ReferenceError"
    var i;
```

**Comment by sebmck** [comment]
TDZ is **hard**. You basically have to implement complete runtime evaluation. Consider the following:

```javascript
function foo() {
  x; // this is legal
}

let x;
``` 

```javascirpt
function foo() {
  x; // this is illegal
}

foo();

let x;
```

It's impossible to discern between the two without actually *evaluating* the code.

**Comment by sebmck** [comment]
There's the optional `blockScopingTDZ` transformer but it's extremely naive and overzealous and doesn't take into consideration my above examples, it simply checks whether or not a reference appears before the declaration, which is subsequently why it's optional in the first place.

**Comment by sebmck** [comment]
I'll leave this open as I think this kind of discussion is important to have and I'd like a reference to point people towards if this question come up again.

**Comment by appden** [comment]
Determining a TDZ violation at compile time is probably impossible (like the halting problem), but compiling these cases into something that throws a `ReferenceError` is possible, though would incur a runtime (and code size) cost that probably isn't worth doing, at least by default.

**Comment by tolmasky** [comment]
Yeah I was just looking and it seems that the traceur people have come up with a (possibly non-performant) strategy: https://github.com/google/traceur-compiler/issues/1382

But yeah, given the difficulty of this, perhaps just a mention in caveats would be enough (or perhaps just the failing let test is already enough)

**Comment by appden** [comment]
That's exactly the approach I was thinking of. Fancy seeing you here @tolmasky. :)

**Comment by sebmck** [comment]
@tolmasky If it's disabled by default and non-performant then noone will use it.

**Comment by sebmck** [comment]
I guess I can implement that Traceur solution if users really want it. I'm just not willing to implement and maintain a feature that noone will use when my time can be spent maturing the platform.

**Comment by appden** [comment]
For the record, I'm not asking for it. I think your time is better spent on other issues. However, *if* it were available, then I'd add that optional transform to development builds.

**Comment by sebmck** [comment]
@appden Development builds are actually a good use-case that I hadn't considered. This shouldn't be too hard to implement so I'll try and get around to it sometime today.

**Comment by tolmasky** [comment]
I have kind of two competing feelings on this. On the one hand I agree that if its not default it probably won't get used (especially with an issue that is subtle, as opposed to turning on some crazy cool feature).

My other feeling is that this unfortunately is the intersection of "very easy error to make", and "potentially catastrophic when moving to ES6/iojs/whatever". That is to say, everyone is so used to hoisting that its totally reasonable to use this like a var, so given the promise that this will definitely get you ready to switch to ES6 when its ready, it would be very frustrating to have your node app then crash immediately on launch.

**Comment by sebmck** [comment]
For complete support it'll have to explode

 - `AssignmentExpression`
 - `UnaryExpression`
 - `UpdateExpression`
 - Static references

It'll also need to support all operators, prefixes, as well as evaluate the same way.

**Comment by appden** [comment]
I was thinking every reference to a `let x` variable be transformed to `(x == UNINITIALIZED ? throw new ReferenceError() : x)`. Essentially, that's what a ES6 engine would be doing under the hood (with many optimizations of course). There are *so many* edge cases that I don't think it's worth trying to be smarter than that considering this would be an optional, development-only (for sane people) transform.

**Comment by sebmck** [comment]
Implementation is a little hacky but it works great. References should be supported in all the contexts as mentioned in my previous comment.

**Comment by pigulla** [comment]
Should this be working?

```
// test.js
i;
let i;
```

```
$ node_modules/.bin/babel-node -V
4.6.6

$ node_modules/.bin/babel-node test.js 
undefined
```

Am I missing something?

**Comment by sebmck** [comment]
@pigulla 

```sh
$ babel-node --optional es6.blockScopingTDZ test.js 
```

**Comment by pigulla** [comment]
Ah, so I did miss something. Thanks!
