### ISSUE TITLE
runtime.js vs to5.runtime()

### ISSUE THREAD

**Issue by assaf** [6to5/6to5#566]
If I understand it correctly, I should be able to use these interchangeably:

```js
to5.runtime();
File.readFileSync( require.resolve('6to5/runtime'), 'utf8')
```

But the output they generate is different. While `runtime.js` contains:

```js
to5Runtime.interopRequireWildcard=function(obj){
  return obj&&obj.constructor===Object?obj:{
    "default": obj
  }
};
```

The method `to5.runtime()` returns:

```js
 to5Runtime.interopRequireWildcard = function (obj) {
    return obj && obj.constructor === Object ? obj : {
      default: obj
    };
  };
```

Notice that the property name `default`, which is also a JavaScript reserved word, is not quoted in the output of `runtime()` and so the code fails with a syntax errors on some browsers.

**Comment by sebmck** [comment]
The optional runtime is being removed in 3.0.0 due to the introduction of the `selfContained` transformer.

**Comment by sebmck** [comment]
The global runtime was added back in 3.3.0. Closing this as the original question has been answered. Thanks!
