### ISSUE TITLE
Destructuring variable declarations should have an initializer

### ISSUE THREAD

**Issue by chicoxyzzy** [6to5/6to5#567]
```javascript
let {};
```
transpiles to
```javascript
"use strict";

var {} = undefined;
```
and this is not expected behaviour. this should throw `Unexpected token {`

http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&=&code=let%20%7B%7D%3B

**Comment by sebmck** [comment]
Bug not present in the 3.0.0 branch.
