### ISSUE TITLE
Extends Array

### ISSUE THREAD

**Issue by jacobp100** [6to5/6to5#570]
Not sure this can be fixed, but worth noting somewhere at least. This fails:
```js
var n = new (class Test extends Array {
  constructor() {
    super()
  }
});

n[10] = 1;

alert(n.length);
```

**Comment by sebmck** [comment]
Not being able to extend built-ins properly used to be documented under [caveats](http://6to5.org/docs/usage/caveats/). Not sure what happened to it though.

**Comment by sebmck** [comment]
Added this back to the docs, thanks!

**Comment by xcoderzach** [comment]
This should probably be listed on the "Learn es6" tab as an unsupported feature.  http://6to5.org/docs/learn-es6/#subclassable-built-ins

**Comment by sebmck** [comment]
@xcoderzach It's already listed in the [caveats](http://6to5.org/docs/usage/caveats/#classes).

**Comment by tomjakubowski** [comment]
This is now a supported feature of ES6, isn't it? Hardly an authoritative source but: http://www.2ality.com/2015/02/es6-classes-final.html#subclassing_built-in_constructors

There's also a V8 test case for it: https://github.com/v8/v8-git-mirror/blob/master/test/mjsunit/harmony/classes-experimental.js#L328-L338
