### ISSUE TITLE
Extending Array does not work correctly

### ISSUE THREAD

**Issue by pjako** [6to5/6to5#571]
Hi, I just tried to extend Array in your playground, and tested it then again in an traceur playground

```javascript
class FooArray extends Array {
  constructor(a) {
    super(a);
  }
}
var e = new FooArray();
e.push('bar');
console.log(e);
```
6to5: {"0":"bar","length":1}

tracur: ["bar"]

**Comment by zloirock** [comment]
Try in traceur repl `console.log(Array.isArray(e))` and open console in 6to5 repl. See [caveats](https://6to5.org/docs/usage/caveats/#classes).

**Comment by stefanpenner** [comment]
I don't believe Natives can be subclassed yet, unfortunately this is a platform limitation.

In theory some hacks could exist to pseudo implement 1 level of inheritance by fetching the native from another realm and mutating it, but this really is a slippery slope.

**Comment by pjako** [comment]
```javascript
class FooArray extends Array {
  constructor(a) {
    super(a);
  }
}
var e = new FooArray();
e.push('bar');
console.log(e);
console.log(e.length);
console.log(e instanceof Array);
console.log(Array.isArray(e))
```
result:
["bar"]
1
true
false

**Comment by fkling** [comment]
Duplicate? #570

**Comment by thejameskyle** [comment]
See [Caveats](http://6to5.org/docs/usage/caveats/#classes)

**Comment by chocolateboy** [comment]
Gonna leave this here for anyone Googling this error message:

#### subclass_string.js

```javascript
class MyString extends String {
    constructor (value) {
        super(value)
    }
}

let test = new MyString('foo');

test += 'bar';
console.log(test);
```
#### result

```
$ babel-node subclass_string.js

subclass_string.js:9
test += 'bar';
    ^
TypeError: String.prototype.valueOf is not generic
```
