### ISSUE TITLE
"__moduleName" no longer set in system modules

### ISSUE THREAD

**Issue by msegado** [6to5/6to5#574]
It looks like the system module formatter no longer sets `__moduleName` in generated modules (see https://github.com/6to5/6to5/commit/df66fa0a7fc9bc05e78e79165d0c9a613517fc75#diff-d9b88d539dc546cdc51af0946e0d69c5L276 for the removed code, and further down on the page for the new test results). Was this intentional, or just an accidental side-effect of the refactoring?

**Comment by sebmck** [comment]
It was intentional. I wasn't able to find a source for `__moduleName` anywhere.

**Comment by msegado** [comment]
Fair enough - thanks!

**Comment by andreasgrimm** [comment]
is there anything we can use as an alternative?
