### ISSUE TITLE
Support Flow type aliases

### ISSUE THREAD

**Issue by bolinfest** [6to5/6to5#575]
6to5 supports type annotations, which is awesome, but to be fully tolerant of Flow, there needs to be support for type aliases, as well: http://flowtype.org/docs/type-aliases.html.

My current workaround is to declare type aliases in separate `.js` files that are not transpiled by 6to5, but as shown in the type aliases documentation, they are designed to be able to be declared in the file that uses them.

**Comment by sebmck** [comment]
Parsing type aliases is supported. [this](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&=&code=type%20T%20%3D%20number%3B%0Avar%20x%3A%20T%20%3D%200%3B) parses fine for instance. If you're running into syntax errors then it's definently a bug. Mind providing the line it's occurring on?

**Comment by bolinfest** [comment]
@sebmck Was this a recent update? I admit that it works in the playground, but locally I'm using 6to5 2.12.0 with `--experimental --blacklist=useStrict --react-compat --include-regenerator --source-maps-inline`.

**Comment by bolinfest** [comment]
Ah, it was fixed in 2.12.6: https://github.com/6to5/6to5/issues/513. My bad, thanks!
