### ISSUE TITLE
Rename 6to5 project now that ES6 (name) is "dead".

### ISSUE THREAD

**Issue by MoOx** [6to5/6to5#577]
Now that we now we will never see an official ES6, is 6to5 an accurate name ?

I read the [6to5 + esnext](http://6to5.org/blog/2015/01/12/6to5-esnext/) post.

Maybe we should keep esnext name don't you think ?

Source
https://esdiscuss.org/topic/javascript-2015
https://github.com/tc39/tc39-notes/blob/master/es6/2014-09/sept-25.md#conclusionresolution-1

**Comment by fkling** [comment]
See https://github.com/6to5/6to5/issues/568

**Comment by MoOx** [comment]
Interesting.

(FYI, I do more CSS than JS, and I am working on [cssnext](https://cssnext.github.io/), so `esnext` seems a good choice to me ^^)

**Comment by thejameskyle** [comment]
Discussing in #568
