### ISSUE TITLE
coreAliasing breaks local variables named Map, Symbol, etc

### ISSUE THREAD

**Issue by AgentME** [6to5/6to5#579]
```javascript
var Map = 5;
console.log('should be 6', ++Map);
```

If you compile it with the coreAliasing transform, it becomes this:
```javascript
"use strict";

var _interopRequire = function (obj) {
  return obj && (obj["default"] || obj);
};

var _core = _interopRequire(require("core-js/library"));

var Map = 5;
console.log("should be 6", ++_core.Map);
```

and outputs "should be 6 NaN" instead.

It's a bit esoteric of an example, but turning on coreAliasing in a project of mine caused tons of things to break because I had a function named "Symbol" that differed from ES6's, and my own locally-defined (not a global) Map polyfill which supported using immutable objects as keys, and now 6to5's polyfilled Symbol and Map were used instead of the local variables.

**Comment by sebmck** [comment]
Fixed as of 2.13.7, thanks!
