### ISSUE TITLE
Suggestion: deeper _.cloneDeep() for opts?

### ISSUE THREAD

**Issue by bolinfest** [6to5/6to5#583]
Currently, `file.js` contains the following code:

```
File.normaliseOptions = function (opts) {
  opts = _.cloneDeep(opts || {});
```

Sounds pretty deep, right?

However, what do you expect the following to print out?

```js
var a = { foo: 'bar' };

var b = {}
b.__proto__ = a;
b.bar = 'baz';

var c = _.cloneDeep(b);

console.log(b.foo);
console.log(b.bar);
console.log(JSON.stringify(b));
for (var key in b) console.log('key: ' + key);

console.log('------');

console.log(c.foo);
console.log(c.bar);
console.log(JSON.stringify(c));
for (var key in c) console.log('key: ' + key);
```

The result is:

```
bar
baz
{"bar":"baz"}
key: bar
key: foo
------
undefined
baz
{"bar":"baz"}
key: bar
```

Basically, `_.cloneDeep()` does not iterate the enumerable properties of its argument and copy them. I ran into this because I thought I was clever if I did:

```
var defaultCompilationOptions = {
  experimental: true,
  reactCompat: true,
  blacklist: [
    'useStrict',
  ],
  sourceMap: 'inline',
  includeRegenerator: true,
};

/**
 * @param sourceCode The code to compile.
 * @param pathToSource The file containing the sourceCode.
 */
function compile(sourceCode, pathToSource) {
  var options = {};
  options.__proto__ = defaultCompilationOptions;
  options.filename = pathToSource;
  return to5.transform(sourceCode, options).code;
}
```

Because I thought I would save myself some object creation by assigning the `__proto__` property, but then the values on `defaultCompilationOptions` do not make it into `opts`.

Worth fixing or am I just trying too hard here?

**Comment by sebmck** [comment]
I've been meaning to rip out most lodash methods and just using simple helpers. There's no reason for it to be `cloneDeep` in the first place due to some changes in the way options are handled internally. I've changed this in the 3.0.0 branch as it may be a breaking change. Thanks!
