### ISSUE TITLE
Using custom plugins with 6to5

### ISSUE THREAD

**Issue by jonathanong** [6to5/6to5#584]
is there an API for this? AFAIK, `.transform()` will print the AST, which i don't want to do.

**Comment by jonathanong** [comment]
wait i don't think you guys even use recast... shit...

**Comment by sebmck** [comment]
6to5 previously used recast but now it doesn't due to reasons stated [here](https://github.com/6to5/6to5/issues/484#issuecomment-70789784) :stuck_out_tongue_winking_eye:

**Comment by jonathanong** [comment]
Np is just like to know how to write a plugin :) docs somewhere would be great!

**Comment by sebmck** [comment]
There's currently no public API for writing transformers but it's definently on the roadmap. See 6to5/6to5#568 for where I'd like to take the project.
