### ISSUE TITLE
async functions w/o regenerator

### ISSUE THREAD

**Issue by jonathanong** [6to5/6to5#585]
any way to use async functions without touching generators? this is something more 7to6. https://github.com/benjamn/es7-async-await

**Comment by zloirock** [comment]
[asyncToGenerator](https://6to5.org/docs/usage/transformers/#async-to-generator) and [bluebirdCoroutines](https://6to5.org/docs/usage/transformers/#bluebird-coroutines) optional transformers.

**Comment by jonathanong** [comment]
ohhhhh i didn't see it in the ToC so i assumed it wasn't supported. can we add all the optional transforms to the ToC?

**Comment by sebmck** [comment]
@jonathanong Which table of contents? The sidebar on the right really needs to be open all the time instead of collapsing, I've open an issue 6to5/6to5.github.io#94

**Comment by jonathanong** [comment]
That works too! I was only looking at the two lists at the top of the page.

**Comment by MatAtBread** [comment]
Nodent (https://github.com/MatAtBread/nodent) implements async/await without generators, other ES6 features or platform support.

**Comment by sebmck** [comment]
@MatAtBread [regenerator](https://github.com/facebook/regenerator) has been around for ages and does exactly the same thing.

**Comment by sebmck** [comment]
@MatAtBread I don't really appreciate you plugging your project in a completely unrelated issue. This specific issue was about using async functions **with** generators.

**Comment by MatAtBread** [comment]
Really? I read "w/o" as "without". And I'm not allowed to mention my 18 month old project even tho I honestly thought it was a solution to the original issue "async functions _w/o_ regenerator"?

I'm not getting a nice, fuzzy open-source feeling.

**Comment by sebmck** [comment]
@MatAtBread It says without regenerator, not without generators. Apologies for the initial vibe, definently jumped the gun a bit. I'm not sure what being 18 months old has to do with anything?

**Comment by MatAtBread** [comment]
Only because you said regenerator had done it "for ages". I was simply pointing out I had something similar at the same time. It's not important - if you (or anyone else) want to use it, cool. If not, that's cool too.
