### ISSUE TITLE
Primitive default export causes named exports to be undefined

### ISSUE THREAD

**Issue by UltCombo** [6to5/6to5#587]
## Test case

**src/x.js**
```js
export default 'hey';
export let x = 'x';
```

**src/index.js**
```js
import {x} from './x';
console.log(x); // should log 'x', but logs `undefined` instead
```

To test:
```
6to5 src --out-dir dist && node dist
```

Looks like this is due to the modules interop approach trying to `_extends()` the `exports["default"]`, which is a primitive and trying to assign to its properties fails silently.

**Comment by UltCombo** [comment]
`--modules commonStrict` fixes this. (#418)

**Comment by sebmck** [comment]
I'm removing the strict module formatters in 3.0.0 and replacing it with better interop by default.

**Comment by UltCombo** [comment]
@sebmck oh nice. I'm curious about how the new interop formatter will work, do you have any links (commit or discussion)?

**Comment by sebmck** [comment]
@UltCombo Nothing really aggregated, it's split up over #493 #225 #224 #95

**Comment by UltCombo** [comment]
That's good enough, thanks!
I've seen and took part in quite a few CJS interop threads in Traceur and the usual outcome is that such interop shouldn't have been attempted. Hence I'm curious to see which approach you will implement. `;)`

**Comment by sebmck** [comment]
Interop is hard/impossible so I'm just going to only export to `module.exports` if there's only a single default export and otherwise export to a default property and add an `__esModule` flag.

**Comment by UltCombo** [comment]
@sebmck that sounds like a good plan initially, but, let's consider that some CJS module is *actually* relying on that interop, let's say:

es6module.js:
```js
export default 42;
```


index.js:
```js
var es6module = require('./es6module');
```

Wouldn't the above just break if `es6module.js` adds a named export in the future?

**Comment by sebmck** [comment]
@UltCombo Yes it would but there's no other way to do it. In order to have any type of CommonJS interop you have to make sacrifices or else it's going to bite people in the ass.

**Comment by UltCombo** [comment]
@sebmck IMHO attempting CJS interop is what will actually bite people in the ass. A non-obvious breakage that can happen due a simple dependencies update (as in my example above) will be a pain in the ass to debug.

A better approach would be to have CJS code to explicitly retrieve the `default` property, e.g.:

```js
var es6module = require('./es6module')['default'];
```

Then there's no breakage and no need for `__esModule` flag hacks.

**Comment by guybedford** [comment]
I just checked this output and it looks like:

```javascript
"use strict";

var _extends = function (target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i];
    for (var key in source) {
      target[key] = source[key];
    }
  }

  return target;
};

exports["default"] = "hey";
var x = exports.x = "x";
module.exports = _extends(exports["default"], exports);
```

I never knew this had been added? I'd be interested to know why we aren't using the straightforward output here:

```javascript
exports['default'] = 'hey';
exports['x'] = 'x';
```

**Comment by sebmck** [comment]
@guybedford I added it naively and didn't think it through at all, I'm removing it in 3.0.0 because I have no idea what I was thinking.

**Comment by guybedford** [comment]
@sebmck perhaps something to do with the `import *` use case? If using the `__esModule` flag, I would strongly advise throwing an error or returning undefined for `import *` of a module that does not use the `__esModule` flag, then we cut out that edge case well.

**Comment by sebmck** [comment]
@guybedford So make it impossible to `import *` from non-es6 generated modules?

In 3.0.0

```javascript
import * as foo from "foo";
```

turns into

```javascript
"use strict";

var _interopRequireWildcard = function (obj) {
  return obj && obj.__esModule ? obj["default"] : {
    "default": obj
  };
};

var foo = _interopRequireWildcard(require("foo"));
```

**Comment by guybedford** [comment]
@sebmck that works fine too, I was just thinking since the default access is of no practical use, it could be left out? May be better to provide some functionality though?

While we're on the topic - how's the `export *` looking in these cases?

**Comment by guybedford** [comment]
@sebmck that output you're using is probably best actually.

**Comment by sebmck** [comment]
@guybedford 

```javascript
export * from "foo";
```

```javascript
"use strict";

var _interopRequireWildcard = function (obj) {
  return obj && obj.__esModule ? obj["default"] : {
    "default": obj
  };
};

var _defaults = function (obj, defaults) {
  for (var key in defaults) {
    if (obj[key] === undefined) {
      obj[key] = defaults[key];
    }
  }

  return obj;
};

_defaults(exports, _interopRequireWildcard(require("foo")));

exports.__esModule = true;
```

**Comment by sebmck** [comment]
Just noticed a bug 

```javascript
var _interopRequireWildcard = function (obj) {
  return obj && obj.__esModule ? obj["default"] : {
    "default": obj
  };
};
```

should actually be

```javascript
var _interopRequireWildcard = function (obj) {
  return obj && obj.__esModule ? obj : {
    "default": obj
  };
};
```

Correct?

**Comment by guybedford** [comment]
@sebmck right yes exactly, sorry I missed that.

**Comment by sebmck** [comment]
@guybedford

```javascript
export * from "foo";
```

```javascript
"use strict";

var _interopRequireWildcard = function (obj) {
  return obj && obj.__esModule ? obj : {
    "default": obj
  };
};

var _defaults = function (obj, defaults) {
  for (var key in defaults) {
    if (obj[key] === undefined) {
      obj[key] = defaults[key];
    }
  }

  return obj;
};

_defaults(exports, _interopRequireWildcard(require("foo")));

exports.__esModule = true;
```

**Comment by guybedford** [comment]
That looks perfect to me.

**Comment by sebmck** [comment]
Great! Thanks for your input.

**Comment by guybedford** [comment]
The only possible issue now is that we allow `import {readFile} from 'fs'`, but `export * from 'fs'` will not export `readFile` if fs is CommonJS.

If you wanted to enable this, we could add:

```javascript
var _interopRequireWildcard = function (obj) {
  return obj && obj.__esModule ? obj : _defaults({
    "default": obj
  }, obj);
};
```

**Comment by guybedford** [comment]
Now the natural reason not to use `import *` is that it introduces more syntax rather than failing. So we encourage use that way.

**Comment by sebmck** [comment]
Do you think it's worth it?

**Comment by guybedford** [comment]
I have no idea, it can be added later at any time and is backwards compatible so perhaps wait and see.

**Comment by sebmck** [comment]
Sure, sounds good.

**Comment by UltCombo** [comment]
I just did some quick tests and the new CJS interop transformer is working very nicely so far, congratz @sebmck and everyone involved. `:D`
