### ISSUE TITLE
6to5-node options

### ISSUE THREAD

**Issue by cesarandreu** [6to5/6to5#588]
Looking at `_6to5-node` and `6to5-node`, only some `6to5` options are available. Is there any reason to not include blacklist and whitelist? I want to disable generator compilation so it will use the V8 implementation in iojs and node 0.11.

**Comment by sebmck** [comment]
There used to be an automatic blacklist that detected what features the current environment supported. It didn't catch buggy environments that weren't spec compliant etc and when things broke they blamed me. I should add blacklist/whitelist options to `6to5-node` though.

**Comment by sebmck** [comment]
Added in the 3.0.0 branch. It's going to be released Monday/Tuesday.

**Comment by cesarandreu** [comment]
Oh awesome :D. I was about to write a PR and saw you added it in. Thanks!

**Comment by sebmck** [comment]
Fixed as of 3.0.0
