### ISSUE TITLE
non-yield abrupt in generator generates suboptimal code

### ISSUE THREAD

**Issue by monsanto** [6to5/6to5#590]
By abrupts, I am referring to `break`, `continue`, `throw`, `return`,  etc.

For example, if you compile the following:

```
function *foo() {
  for (;;) {
    bar()
    break
  }
  yield baz()
}
```

you get

```
var foo = regeneratorRuntime.mark(function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        bar();
        return context$1$0.abrupt("break", 4);
      case 2:
        context$1$0.next = 0;
        break;
      case 4:
        context$1$0.next = 6;
        return baz();
      case 6:
      case "end":
        return context$1$0.stop();
    }
  }, foo, this);
});
```

I would expect Regenerator to not chop up the loop like that, unless the loop contained a yield. Instead, it should generate something like this, which is more readable and performant:

```
var foo = regeneratorRuntime.mark(function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        for (;;) {
          bar();
          break;
        }
        context$1$0.next = 3;
        return baz();
      case 3:
      case "end":
        return context$1$0.stop();
    }
  }, foo, this);
});
```

(this is the code Regenerator generates if you don't have the `break`; I manually added it to the final result)

**Comment by sebmck** [comment]
Not really a 6to5 issue. Reporting it on the [regenerator](https://github.com/facebook/regenerator) repo is your best bet.

**Comment by benjamn** [comment]
Yep, please report this over at https://github.com/facebook/regenerator/issues and I'll take a look at it. I think I was just being paranoid, and I agree that the loop should be emitted intact. That'll be better for source maps, too.

**Comment by monsanto** [comment]
@benjamn i assume you got here from the next steps ticket? we are playing a lot of repo tag on this issue, haha. anyway, i made a ticket on regenerator https://github.com/facebook/regenerator/issues/181
