### ISSUE TITLE
React JSX Don't use __spread internal method

### ISSUE THREAD

**Issue by sebmarkbage** [6to5/6to5#594]
Love the JSX support! However, the only reason we added `React.__spread` was because we realized that we couldn't rely on people having an ES6 compatible environment. It's just an alias from `Object.assign` so if you have `Object.assign` you can just use that.

The only reason we put it on the React object is because JSTransform doesn't have a runtime that we could add it to. If you could embed it in your runtime or just use `Object.assign`, that would be great.

That way we can get rid of this ugly hook in React.

**Comment by sebmck** [comment]
Ah right, that makes total sense. I was trying to get the output to match the official React compiler as closely as possible and wasn't sure if there was some internal magic done on `React.__spread`. I'll remove this in v3.0 and use the internal `extends` helper. Thanks!

**Comment by sebmck** [comment]
Fixed as of 3.0.0
