### ISSUE TITLE
async/await on class methods

### ISSUE THREAD

**Issue by aaronshaf** [6to5/6to5#597]
This seems to work:

```javascript
class User {
  static async find() {
    // ...
  }
}
```

But not this:

```javascript
class User {
  async find() {
    // ...
  }
}
```

Any ideas?

**Comment by sebmck** [comment]
Looks to be working for [me](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&=&code=class%20User%20%7B%0A%20%20async%20find()%20%7B%0A%20%20%20%20%2F%2F%20...%0A%20%20%7D%0A%7D). What's not working, are you getting a syntax error or is your actual code not executing correctly?

**Comment by tp** [comment]
@aaronshaf Had the same problem, but now it works with this `.babelrc`:

```
{
  "stage": 2,
  "optional": ["es7.classProperties", "es7.decorators", "es7.functionBind", "utility.inlineEnvironmentVariables", "es7.asyncFunctions"]
}
```

I think it needs both `es7.classProperties` and `es7.asyncFunctions`, which surprised me because I thought those were already part of stage 2.

**Comment by pengliheng** [comment]
while i use in mongoose model 
```
class User{
    static async find(){
        //do sth
    }
}  
```
it told me find is not a funciton
