### ISSUE TITLE
“No runtime”

### ISSUE THREAD

**Issue by rauschma** [6to5/6to5#598]
I’m not completely happy with this expression. It’s too simplistic an argument against Traceur (6to5 is most useful with a polyfill). How about changing this into something slightly longer, making a more nuanced case?

**Comment by sebmck** [comment]
Are you referring to a specific place where that's used?

**Comment by rauschma** [comment]
* http://6to5.org/
* http://6to5.org/docs/faq/ (Do you always want to avoid a library dependency? Or only for libraries?)
* http://6to5.org/docs/compare/ (To me, the main point is not that Traceur uses a library, but that the code you show is ugly)

These pages sometimes give the impression that depending on libraries is bad. I’d flip that around: It is nice to have _the option_ not to depend on them (e.g. for libraries). For a normal app, I’d want to import all helper functions (including `_inherits`) from libraries.

I may be making too much fuss about this, but it is something that felt a bit too simplistic in the otherwise excellent docs.

**Comment by sebmck** [comment]
@thejameskyle thoughts?

**Comment by zloirock** [comment]
@rauschma currently, 6to5 can fully work in FF without polyfill. Also you can take other, not default, polyfill. Traceur runtime is constant, we can't disable or replace it. I think, “no runtime” is  argument.

**Comment by sebmck** [comment]
Yeah, the only features that require a polyfill are listed on the [caveats](http://6to5.org/docs/usage/caveats/) page and that's to properly support iterators.

**Comment by rauschma** [comment]
All good points! I think I was mainly looking for more information what “no runtime” actually meant.

**Comment by chicoxyzzy** [comment]
@rauschma you definitely should say some words about it on Minsk conference :stuck_out_tongue_winking_eye: See you there

**Comment by sebmck** [comment]
@rauschma Ah, good point. I've created an issue on the 6to5.github.io repo 6to5/6to5.github.io#99 to track this.

**Comment by thejameskyle** [comment]
Thanks @rauschma, this is something I felt needed a bit more clarity as well.
