### ISSUE TITLE
Register output has __esModule flag in 3.0.0 branch

### ISSUE THREAD

**Issue by guybedford** [6to5/6to5#599]
I just noticed this when testing out the new branch - 

```javascript
System.register([], function (_export) {
  "use strict";

  var p;
  return {
    setters: [],
    execute: function () {
      p = _export("p", "p");
      exports.__esModule = true;
    }
  };
});
```

This is throwing because `exports` is undefined. I don't think we need the flag for this scenario.

Looking forward to the release, hope to synchronise as closely as possible!

**Comment by sebmck** [comment]
Weird, this should only be inserted when using the CommonJS/AMD/UMD formatter.

**Comment by sebmck** [comment]
No idea how this snuck in there. Thanks!

**Comment by guybedford** [comment]
Amazing, thanks for the quick response!! Note that Lodash hasn't been updated to 3.0.0 on this branch yet too.

**Comment by sebmck** [comment]
Ah, haven't merged from `master` yet.

**Comment by thejameskyle** [comment]
@sebmck I'm assuming all the stuff since the last 2.x release is just going into 3.0?

**Comment by sebmck** [comment]
@thejameskyle Yup.
