### ISSUE TITLE
Supporting custom transform.

### ISSUE THREAD

**Issue by scv119** [6to5/6to5#603]
Any thoughts on supporting custom transforms? 

Specifically, I would like to add to add something like

```
/* @track */
foo(args) {
 // Do foo on args.
}
```

And transpile it to 

```
foo(args) {
  var start = Date.now();
  try {
    doStuff();
  } finally { 
    trackTiming('foo', Date.now() - start);
  }
}
```

In my Node.js project, but I can't find the API to support it so far.

**Comment by sebmck** [comment]
Yeah, it's definently on the roadmap. Check out #568 for the direction that I'm going to take this project.

**Comment by scv119** [comment]
@sebmck  thanks for the help.

**Comment by sebmck** [comment]
Superseded by #607
