### ISSUE TITLE
File not found when running 6to5

### ISSUE THREAD

**Issue by trusktr** [6to5/6to5#604]
I've got this in my package.json, which has worked just fine, until today when I came back and noticed the deprecation warning for 2.x.x:

```
  "dependencies": {
    "6to5": "^2.7.1"
  },
  "scripts": {
    "test": "echo 'TODO: Test script' && exit 1",
    "clean": "rm -rf dist",
    "postinstall": "npm run build-cjs",
    "build-umd": "./node_modules/.bin/6to5 src --source-maps --out-dir . --modules umd",
    "build-cjs": "./node_modules/.bin/6to5 src --source-maps --out-dir . --modules common",
    "build-amd": "./node_modules/.bin/6to5 src --source-maps --out-dir . --modules amd",
    "build-global": "echo 'TODO: Global build' && exit 1"
  },
```

so when installing this package, it runs 6to5. But lately, I'm getting this error (with irrelevant parts removed):

```
❯ npm install git+https://github.com/infamous/infamous.git#master                                                                                                         [22:06:54]
npm WARN deprecated 6to5@2.7.1: 3.0.0 has been released featuring a host of bug fixes and new features

> infamous@0.0.30 postinstall /Users/josephpea/test/blahblah/node_modules/infamous
> npm run build-cjs

> infamous@0.0.30 build-cjs /Users/josephpea/test/blahblah/node_modules/infamous
> 6to5 src --source-maps --out-dir . --modules common

src doesn't exist

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build-cjs"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code ELIFECYCLE
npm ERR! infamous@0.0.30 build-cjs: `6to5 src --source-maps --out-dir . --modules common`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the infamous@0.0.30 build-cjs script '6to5 src --source-maps --out-dir . --modules common'.
npm ERR! This is most likely a problem with the infamous package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     6to5 src --source-maps --out-dir . --modules common
npm ERR! You can get their info via:
npm ERR!     npm owner ls infamous
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/josephpea/test/blahblah/node_modules/infamous/npm-debug.log
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "git+https://github.com/infamous/infamous.git#master"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code ELIFECYCLE
```

Any idea why this was working before, but not now?

**Comment by sebmck** [comment]
3.0.0 was released today so I deprecated 2.x. The deprecation doesn't do anything other than just displaying that message whenever you install a 2.x version.

**Comment by trusktr** [comment]
For sure. THanks. I think I might've published some version of my lib while not in the root folder. e.g. npm publish in a subfolder. Doh.

**Comment by timoxley** [comment]
@trusktr Some probably unrelated problems on your usage of npm scripts:

`node_modules/.bin` should *never* exist in any npm script. The executable you're after is not **guaranteed** to be in that location due to npm's deduplication algorithm. Just call `6to5` directly, when `npm` runs scripts it automatically configures the `PATH` to include `./node_modules/.bin` and various other locations the executable could be located (i.e. a `node_modules/.bin` anywhere the parent hierarchy)

Also you should almost never use `postinstall` for a similar reason, it runs after things are installed into it's `node_modules` but it's possible npm has decided to install a dependency higher in the hierarchy for deduplication purposes. Instead of `postinstall` you should always use `prepublish` (which is, perhaps unintuitively, fired after installation).

**Comment by trusktr** [comment]
@timoxley Interesting. It seems npm is stripping the "./node_modules/.bin" from the call anyway. Thanks for those helpful tidbits! I'm guessing (intuitively) that prepublish runs before `npm publish`.

**Comment by trusktr** [comment]
@timoxley Hmmm, now that I think of it, my postinstall script is only touching files of my own package, nothing in node_modules, so some dependencies being higher up might not be a problem, right? I'll give prepublish a try.
