### ISSUE TITLE
Add kangax compat-table tests

### ISSUE THREAD

**Issue by sebmck** [6to5/6to5#606]
More tests the better, will hopefully help avoid regressions.

**Comment by zloirock** [comment]
From me only `Object.getOwnPropertySymbols` and `Symbol.species`. Also, I think be better remove from build step `typeofSymbol` transformer and enable `Object(symbol)`.

**Comment by sebmck** [comment]
@zloirock I'll probably only add the syntax related tests as all the other stuff doesn't really matter to 6to5.

**Comment by zloirock** [comment]
@sebmck I mean, if somebody will change results of 6to5 tests in table, can add to the results these.
