### ISSUE TITLE
Property initializers

### ISSUE THREAD

**Issue by ooflorent** [6to5/6to5#611]
With React 0.13 coming to town, I would be great if 6to5 would support ES7 property initializers.
Further info: [Property Initializers (React 0.13)](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es7-property-initializers)

**Comment by sebmck** [comment]
> We fully expect a more declarative syntax for property initialization to arrive in future version of JavaScript. It *might* look something like this.

They're purely theoretical at the moment. There's no spec/details anywhere and I'm not 100% sure what the behaviour of them is. I'd be happy to add them if @sebmarkbage can cite some more technical details about their behaviour but there's currently nothing solid.
