### ISSUE TITLE
desugaring default parameters

### ISSUE THREAD

**Issue by WebReflection** [6to5/6to5#612]
I've done some [simple benchmark](http://jsperf.com/6to5-translated-parameters-default) using not only a better minifier friendly output but also an overall faster one.

There is also a little gotcha with the arity of the resulting function.

**original**
```js
function sum(a = 0, b = 0) {
  return a + b;
}

sum.length; // 2 in ES6 compatible world
```

**6to5 translation**
```js
function sum1() {
  var a = arguments[0] === undefined ? 0 : arguments[0];
  var b = arguments[1] === undefined ? 0 : arguments[1];
  return a + b;
}

sum.length; // 0, expected 2
```

**proposal**
```js
function sum2(a, b) {
  a === undefined && (a = 0);
  b === undefined && (b = 0);
  return a + b;
}

sum.length; // 2
```

I understand this is not a priority but maybe some enhancement to consider in the future?

Best Regards

**Comment by sebmck** [comment]
This is actually spec behaviour.

**Comment by sebmck** [comment]
See [here](http://tc39wiki.calculist.org/es6/default-parameter-values/). Unable to find a spec citation at the moment but there are tests for the arity in both Traceur and esnext so I'm extremely confident in it's correctness.

**Comment by WebReflection** [comment]
uhm ... I think you are right, my bad.

**Comment by sebmck** [comment]
All good, thanks for reporting it! I'm eager to get everything as close to the spec as possible.

**Comment by barneycarroll** [comment]
Stupid spec. What has it ever done for us? ;)
