### ISSUE TITLE
regression with modules in v3.0.8

### ISSUE THREAD

**Issue by oriSomething** [6to5/6to5#613]
this would work in 2.13.3 version and stop with the upgrade to 3.x:
`index.js:`
```javascript
import hi from './hi';

hi();
hi.hola();
```
`hi.js:`
```javascript
export default function hi() {
  console.log('hi');
}

export function hola() {
  console.log('hola');
}
```
now node throws:
```
hi.hola();
   ^
TypeError: Object function hi() {
  console.log("hi");
} has no method 'hola'
    at Object.<anonymous> (.../index.js:13:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

the work around for now is:
1. using another import command. example: `import { hola } from './hi'`
2. or adding manually in the lib the hola function to the default function, example:
```javascript
export function hola() {
  console.log('hola');
}

function hi() {
  console.log('hi');
}

hi.hola = hola;

export default hi;
```

both aren't fun solution. can't say if it's align or not with ES2015

**Comment by sebmck** [comment]
The new behaviour is aligned with ES6, previously there was quite a lot of
bad CommonJS interop implemented but luckily I got my head screwed back on
with the awesome help of @guybedford.

On Wednesday, 28 January 2015, ori livni <notifications@github.com> wrote:

> this would work in 2.13.3 version and stop with the upgrade to 3.x:
> index.js:
>
> import hi from './hi';
>
> hi();
> hi.hola();
>
> hi.js:
>
> export default function hi() {
>   console.log('hi');
> }
> export function hola() {
>   console.log('hola');
> }
>
> now node throws:
>
> hi.hola();
>    ^
> TypeError: Object function hi() {
>   console.log("hi");
> } has no method 'hola'
>     at Object.<anonymous> (.../index.js:13:4)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:929:3
>
> the work around for now is:
> 1. using another import command. example: import { hola } from './hi'
> 2. or adding manually in the lib the hola function to the default
> function, example:
>
> export function hola() {
>   console.log('hola');
> }
> function hi() {
>   console.log('hi');
> }
>
> hi.hola = hola;
> export default hi;
>
> both aren't fun solution. can't say if it's align or not with ES2015
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/6to5/6to5/issues/613>.
>


-- 
Sebastian McKenzie

**Comment by oriSomething** [comment]
so what you're saying is that now i need to use two different `import`s?

**Comment by sebmck** [comment]
Yep, that's correct. An alternate version is `import hi, { hola } from './hi';` which is far nicer/cleaner.

**Comment by oriSomething** [comment]
thanks
