### ISSUE TITLE
Arrow functions, needs a fix.

### ISSUE THREAD

**Issue by hemanth** [6to5/6to5#616]
```js
let hello = () => "Yo!";
let greet = new hello();
```

^ must throw `TypeError: hello is not a constructor` but it does not. [Same code](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=let%20hello%20%3D%20()%20%3D%3E%20%22Yo!%22%3B%0A%0Alet%20greet%20%3D%20new%20hello()%3B%0A)

**Comment by sebmck** [comment]
@hemanth Do you have a source?

**Comment by hemanth** [comment]
@sebmck It's in the draft and FF as the same implementation.

**Comment by sebmck** [comment]
@hemanth I meant a section citation in the spec or something.

**Comment by hemanth** [comment]
@sebmck yeah, understood. Link not handy, will dig.

**Comment by sebmck** [comment]
Not sure if there's anything that can be done about this either since this is a runtime check that can't possibly be replicated with transpiled code.

**Comment by hemanth** [comment]
But for sure they don't have `.prototype` and ` [[Construct]]` internal method, so `new (() => {})` will throw an error.

**Comment by sebmck** [comment]
@hemanth You can't transpile that and even if you could it'd be a massive performance hit.

**Comment by hemanth** [comment]
Oh!

**Comment by sebmck** [comment]
Going to close this and mark it as cantfix. Unfortunately there's nothing that can be done.

**Comment by hemanth** [comment]
@sebmck NP, it was a nice learning opportunity!
