### ISSUE TITLE
selfContained and coreAliasing documentation

### ISSUE THREAD

**Issue by AgentME** [6to5/6to5#623]
I'm excited to see the selfContained option appear in 6to5 so I can finally use generators in a library without polluting the global scope, but the documentation is a little behind.

* "coreAliasing" is still referred to in the [transformers page](http://6to5.org/docs/usage/transformers/).
* The documentation says it translates certain things to require "core-js" or "regenerator/runtime-module", but the code example and my own testing shows that it translates calls to require "6to5-runtime/core-js" and "6to5-runtime/regenerator".

**Comment by sebmck** [comment]
Ah damn, you're right. I've cleaned it up a bit. I'll have to dedicate some time to polishing some of the docs as I'm not very happy with how some of it's presented. Thanks!
