### ISSUE TITLE
Support await* delegation

### ISSUE THREAD

**Issue by RReverser** [6to5/6to5#627]
Would be nice to have this feature from [await* and parallelism](https://github.com/lukehoban/ecmascript-asyncawait#await-and-parallelism) section of async/await proposal:

> It has been suggested that the syntax could be reused for different semantics - sugar for Promise.all. This would accept a value that is an array of Promises, and would (asynchronously) return an array of values returned by the promises. This is expected to be one of the most common Promise-related oprerations that would not yet have syntax sugar after the core of this proposal is available.

> This would allow, for example:

> ```javascript
async function getData() {
  var items = await fetchAsync('http://example.com/users');
  return await* items.map(async(item) => {
    return {
      title: item.title, 
      img: (await fetchAsync(item.userDataUrl)).img
    }
  })
}
```

Currently 6to5 simply ignores `*` in `await*`.

**Comment by sebmck** [comment]
6to5 delegates async/generator transformation to [regenerator](https://github.com/facebook/regenerator). Would be a more productive to report this upstream.

**Comment by RReverser** [comment]
Ah, ok. Thought that async/await stuff is on 6to5 side.

**Comment by sebmck** [comment]
Actually, the following *could* be added:

```javascript
exports.AwaitExpression = function (node) {
  if (node.delegate) {
    node.delegate = false;
    node.argument = t.callExpression(t.memberExpression(t.identifier("Promise"), t.identifier("all")), [node.argument]);
  }
};
```

**Comment by sebmck** [comment]
Actually yeah, this is something that can also be solved on our side and will add `await*` usage to the optional async to generator transformers. I'll reopen this.

**Comment by sebmck** [comment]
Spoke too soon, see [here](https://github.com/facebook/regenerator/issues/171#issuecomment-71954888). I'll have to remove `await*` from the parser.

**Comment by sebmck** [comment]
Actually I'm not sure, I feel really conflicted. @RReverser, what do you think?
