### ISSUE TITLE
selfContained transformer promises

### ISSUE THREAD

**Issue by KenPowers** [6to5/6to5#630]
In 6to5 v2 I used to use [Bluebird](https://github.com/petkaantonov/bluebird) from the global scope as such:

```js
var p = new Promise(...); // That's a Bluebird promise
```

Now in v3, however, the Promise constructor is always changed to the following unless `Promise` is found in the local scope:

```js
var p = new _core.Promise(function () {}); // That's not a Bluebird promise
```

Is there a way to avoid this? Basically I want to use `selfContained` (since I was using the runtime in v2) but I want to avoid the automatic `core-js` aliasing (or at least just for Promises).

**Comment by sebmck** [comment]
`core-js` will automatically use the global `Promise` if it's available and spec-compliant.

**Comment by sebmck** [comment]
Oh wait sorry, I misread, you're using `Promise` from the global scope and you've set it to `Bluebird`. I'm actually not sure if there's much that can be done about that unfortunately if you want to use the `selfContained` transformer.

**Comment by sebmck** [comment]
Still, `core-js` should be using the bluebird global if it's spec-compliant which it would be. Are you running into any specific issues?

**Comment by appden** [comment]
I think it would reasonable to be able to build a self-contained library without `core-js` if you know you're going to have a suitably polyfilled browser environment. I don't personally need that option, but it makes sense that someone might.

**Comment by Dashed** [comment]
I haven't updated to 6to5 v3 yet, but I hope `core-js` can still use Bluebird if it's available. Unsure how to "bind" this though.

In 6to5 v2, I'm using webpack's aliasing feature (http://webpack.github.io/docs/list-of-plugins.html#provideplugin) to provide Bluebird to any referencing `Promise` free variable.

**Comment by sebmck** [comment]
@appden If you're using the `selfContained` transformer then odds are you aren't relying on a completely polyfilled environment. Regardless of if you are or not, `core-js` will use the globally provided `Promise` if it's available.

**Comment by KenPowers** [comment]
I did some more investigation. Basically I have code which amounts to the following:

```js
global.Promise = require('bluebird');
//...
var foo = new Promise(function () {});
```

`selfContained` turns that into this:

```js
var _core = require("6to5-runtime/core-js");
global.Promise = require('bluebird');
//...
var p = new _core.Promise(function () {});
```

So the code which sets up `core.js` is getting executed before I register Bluebird as a global. I verified this by changing the compiled code to the following:

```js
global.Promise = require('bluebird');
var _core = require("6to5-runtime/core-js");
//...
var p = new _core.Promise(function () {});
```

`p` was then a Bluebird promise.

So there are a few solutions I can think of:

1. Move `_core` declaration to as late as possible.
1. Somehow get Bluebird registered earlier (I guess that would be more my problem and anyone else's).
1. Create a configuration option for `selfContained` to only alias certain features.
1. Start using Bluebird non-globally.

Thoughts?

**Comment by sebmck** [comment]
@KenPowers It'd probably be a better idea to just name your bluebird promise `Bluebird` instead of `Promise`. I've considered splitting up the `selfContained` transformers as there's 3 specific things it does but I really don't think it's necessary as so far all the issues that have been reported with the `selfContained` transformer have been related to weird environment issues which shouldn't really be present in the first place.

**Comment by zloirock** [comment]
Core-js use bluebird `Promise`, but bluebird should be required before core-js. I see other 2 way:
* require 6to5 with `selfContained` after bluebird
* dirty fix `require('6to5-runtime/core-js').Promise = require('bluebird');`

**Comment by Dashed** [comment]
Okay so I tried 6to5-loader with 6to5 v3 with webpack.

As suggested by @zloirock, the dirty fix as the very first line of JS code, seems to be the current feasible way: `require('6to5-runtime/core-js').Promise = require('bluebird');`

Previously I had to do this `require('6to5/polyfill');`

**Comment by Dashed** [comment]
I don't really mind doing the dirty fix. But I'm open to a way as to not use it.

**Comment by sebmck** [comment]
I'll leave this open for a bit until I work out if there's a way to support this. I'm more leaning on the not doing anything about it side because if you're overriding built-ins then you're already in for a world of hurt and I already don't want to be supporting those kinds of practices.

**Comment by Dashed** [comment]
I think we should document this in caveats (http://6to5.org/docs/usage/caveats/).

I think it's fair to say that users, like @KenPowers and I, may expect `Promise` reference to be "untransformed", and try to shim it with out favourite Promise library through something like `global.Promise` or webpack.

**Comment by sebmck** [comment]
@Dashed I'm open for a pull request adding it to the `core-js aliasing` section on the [optional transformer docs](http://6to5.org/docs/usage/transformers/#self-contained).

**Comment by guybedford** [comment]
What is the reason we need a reference to the core-js methods directly? Is it not enough to use global variables to refer to the ES5-polyfilled environment, allowing the user to polyfill as they wish?

**Comment by sebmck** [comment]
@guybedford The point of the `selfContained` transformer is so you don't need a globally polluting polyfill. It's main-use is for creating an ES6-like environment where you can use `Set`, `Promise`, `Symbol` etc.

**Comment by Dashed** [comment]
@sebmck Sure np. I'll PR.

**Comment by KenPowers** [comment]
@sebmck I see where you're coming from but in that case we definitely need arguments that control what `selfContained` does (or maybe split it up). I'm using it for the generator / async stuff but unfortunately it has the side effect of making using alternative implementations of other features more difficult.

**Comment by Dashed** [comment]
@KenPowers Are you shimming anything else other than Promises?

**Comment by KenPowers** [comment]
Nope. Bluebird is just awesome enough that I use it as a superset shim. I've never used regenerator on its own, so I'm fine with 6to5 doing whatever it needs to in that case.

**Comment by sebmck** [comment]
Superseded by #651. I'm adding back the runtime since it was a feature that people legitimately used.

**Comment by sebmck** [comment]
Added the optional runtime back in 3.3.0

**Comment by grrowl** [comment]
+1 to splitting up or enabling subsets of `selfContained`s functionality (@KenPowers). Enabling the whole thing adds 27k of minified code to my runtime, when really I only wanted ES6's new `Object` and `Array` methods. I'm already using bluebird and the additional features it provides.

**Comment by sebmck** [comment]
@grrowl There's no reason you can't selectively include your own polyfill. Splitting up the `selfContained` transformer wouldn't lead to you being able to split up the polyfill anyway since that's a non-trivial architectural change for core-js.

**Comment by grrowl** [comment]
You are correct. I guess I was hoping to deal with enabling ES6 features as required at the transpiler level, but you're right in that core-js is the problem here. I'd love to fall back on using [webpack's ProvidePlugin](http://webpack.github.io/docs/list-of-plugins.html#provideplugin) to cherry-pick/`require()` out of the core-js library as needed, but alas, it's not AMD compatible (nor may it be able to be). Thanks for your response anyway.

**Comment by zloirock** [comment]
@grrowl you can create [custom build](https://github.com/zloirock/core-js#custom-build) core-js and replace `6to5-runtime/core-js` file.

**Comment by Dashed** [comment]
@zloirock Is there an alternative way to this for current version of babel? https://github.com/babel/babel/issues/630#issuecomment-71980187

**Comment by zloirock** [comment]
@Dashed
```js
var Promise = require('bluebird');
new Promise(function(){});
```
will not be transformed. If you don't want require `'bluebird'` in each file possible
```js
require("babel-runtime/core-js/promise")["default"] = require('bluebird');
```
in entry point, but `Promise` should not be used in entry point.

**Comment by Dashed** [comment]
@zloirock Thanks for the suggestions. The latter suggestion seems more feasible; albeit with a catch. I elaborate on this here: https://github.com/babel/babel-loader#custom-polyfills-eg-promise-library

**Comment by grrowl** [comment]
@dashed It seems to me that your instructions are already out of date? I get: `Cannot resolve module 'babel-runtime/core-js/promise'`.

The actual shims are inside node_modules/core-js, which makes me worry it won't actually override the loading and inclusion of the alternate Promise library:
```
babel-core git:(master) ✗ find . |grep promise
./node_modules/core-js/es6/promise.js
./node_modules/core-js/fn/promise.js
./node_modules/core-js/library/es6/promise.js
./node_modules/core-js/library/fn/promise.js
./node_modules/core-js/library/modules/es6.promise.js
./node_modules/core-js/modules/es6.promise.js```

**Comment by Dashed** [comment]
@grrowl The module to be resolved is `babel-runtime` (i.e. `./node_modules/babel-runtime/core-js/`).

**Comment by grrowl** [comment]
Sorry! You're totally right, `babel-runtime` is optional and [detailed here](https://babeljs.io/docs/usage/runtime/).

**Comment by dmvjs** [comment]
Did this get resolved? I would also like to provide a fallback promise implementation for Webpack ala `selfContained` without global stomping but my quick take here is that this is maybe a hard problem and not currently possible.
