### ISSUE TITLE
console.clear() doesn’t work in the Playground (on Chrome)

### ISSUE THREAD

**Issue by rauschma** [6to5/6to5#632]
https://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=console.clear()

I’m getting:

    Uncaught TypeError: Illegal invocation

**Comment by sebmck** [comment]
This is better suited for the [6to5.github.io](https://github.com/6to5/6to5.github.io) repo. Mind opening it over there? Thanks!

**Comment by rauschma** [comment]
Done.

**Comment by sebmck** [comment]
Thanks again!
