### ISSUE TITLE
Aliasing / mapping

### ISSUE THREAD

**Issue by guybedford** [6to5/6to5#635]
I'd like to be able to have an option to specify a custom alias for the `6to5-runtime` package output in the dependencies.

As well as this, when doing self-executing bundles, we need to normalize all dependencies during the transpilation as well, so I was going to need to look at building a custom transformer just for "remapping" dependencies (like we have for Traceur - https://github.com/systemjs/builder/blob/master/compilers/es6.js#L6)

Both of the above could be solved really nicely with a custom option to remap dependencies.

With a mapping object, it can be easy to get into issues like how to deal with subpaths etc, so the simplest I've found is often just a synchronous function:

```javascript
{
  normalize: function(depName) {
    return 'newName';
  }
}
```

The added benefit is that it can also act as a dependency tracing tool.

Let me know your thoughts.

**Comment by guybedford** [comment]
Happy to do this with a custom transformer myself too, but thought I'd create the suggestion first.

**Comment by sebmck** [comment]
i'm a bit confused by what you mean by "remapping dependencies". Can you elaborate?

**Comment by guybedford** [comment]
_Normalizing_ is probably a better term. When building sfx-bundles in jspm, we normalize all dependencies into canonical form (`./lib` -> `/full/path/to/lib`, etc), which is done during the ES6 transformation phase.

**Comment by sebmck** [comment]
@guybedford Ah right, so just "transforming" module sources?

**Comment by guybedford** [comment]
Exactly.

**Comment by sebmck** [comment]
Same issue as #471 then

**Comment by guybedford** [comment]
Right, I thought that was discussing linking behaviours when I first read it. Sure, thanks have copied the proposal there.
