### ISSUE TITLE
Amd + selfContained not compatible

### ISSUE THREAD

**Issue by GianlucaGuarini** [6to5/6to5#638]
requirejs does not work using the option ``--modules amd --optional selfContained``. The `6to5-runtime/helpers` file does not export the helpers functions using the amd syntax, it can be used only in a nodejs/browserify environment.
There should be a way to avoid the following output using the amd modules option
```javascript
define("myModule", ["exports", "module", "6to5-runtime/helpers"],function(6to5Helpers){
  var _6to5helpers = 6to5Helpers;
});
```
The output should be similar to something like this:
```javascript
define("myModule", ["exports", "module"],function(){
  var _6to5helpers = global.6to5Helpers;
});
```

**Comment by sebmck** [comment]
AMD is generally a bitch to support, not sure if it's worth the effort.

**Comment by GianlucaGuarini** [comment]
I don't know why with the version 3.0.0 you should downgrade. Before (v2.0.0) with the `runtime` option  it was working without any problem. At this point it doesn't make sense to support the amd at all IMHO.

**Comment by Dashed** [comment]
@GianlucaGuarini Out of curiosity, have you tried webpack for AMD support instead of 6to5 directly? You can also try using 6to5-loader as well.

**Comment by sebmck** [comment]
@GianlucaGuarini Because there's a maintenance commitment associated with every single feature I add.

**Comment by Dashed** [comment]
I'm wondering if people actually still use AMD for new projects, and if it still has any benefits compared to what browserify/webpack provides. 

IMO, anyone actually using 6to5 is committed to writing code using new stuff. To me, it doesn't seem to make sense to be outputting AMD. browserify/webpack already does well to import AMD modules as CommonJS modules anyways.

So I propose dumping/deprecating AMD stuff beginning v4.x (or some future version).

**Comment by sebmck** [comment]
I think there's value in supporting AMD/UMD module formatters but not for supporting it for the `selfContained` transformer.

**Comment by GianlucaGuarini** [comment]
@Dashed it seems I have no choice.. so this means I must use either browserify or webpack

**Comment by sebmck** [comment]
@GianlucaGuarini I've added the optional runtime back with 3.0.0 #651. I believe the removal of the optional runtime in 3.x is the reason you had to use the selfContained transformer in the first place.

**Comment by GianlucaGuarini** [comment]
Awesome thanks
