### ISSUE TITLE
arguments not scoped correctly

### ISSUE THREAD

**Issue by bolinfest** [6to5/6to5#640]
As demonstrated by:

https://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=function%20foo()%20%7B%0A%20%20var%20f%20%3D%20()%20%3D%3E%20console.log(arguments)%0A%7D

```
function foo() {
  var f = () => console.log(arguments)
}
```

is transpiled to:

```
"use strict";

function foo() {
  var _arguments = arguments;
  var f = function () {
    return console.log(_arguments);
  };
}
```

but I believe it should be:

```
"use strict";

function foo() {
  var f = function () {
    return console.log(arguments);
  };
}
```

**Comment by sebmck** [comment]
Nope, `arguments` inside arrow functions are bound the same way as `this`.

**Comment by bolinfest** [comment]
Crazy! So there's no way to get the arguments from an arrow function?

Our engineer is using `(...args)` as a workaround. I guess that's best?

**Comment by Dashed** [comment]
@bolinfest Yeah spread operator is your best bet to 'rename' `arguments` to something else (e.g. `args`).

**Comment by sebmck** [comment]
@6to5/broccoli Unfortunately, yeah.

Here are some spec references for this curious:

[9.2.13](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-functiondeclarationinstantiation)

> 17.a NOTE Arrow functions never have an arguments objects.

[14.2.17](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrow-function-definitions-runtime-semantics-evaluation)

> Any reference to arguments, super, or this within an ArrowFunction are resolved to their bindings in the lexically enclosing function.
