### ISSUE TITLE
How is this different than Traceur?

### ISSUE THREAD

**Issue by christianbundy** [6to5/6to5#642]
Currently our codebase is dependent on Traceur, but I'm looking at other options. I saw that #598 mentioned there's no runtime – are there any other large differences? Thanks!

**Comment by sebmck** [comment]
See the [FAQ](http://6to5.org/docs/faq/#how-does-6to5-differ-from-other-transpilers-).

**Comment by sebmck** [comment]
Also see the [compare](http://6to5.org/docs/compare/) page on the 6to5 website and [compat-table](https://kangax.github.io/compat-table/es6/). Let me know if you have any additional questions, more than happy to help!

**Comment by christianbundy** [comment]
Thanks @sebmck!
