### ISSUE TITLE
Using a variable named 'module' interferes with module systems.

### ISSUE THREAD

**Issue by RoystonS** [6to5/6to5#645]
I wrote (a bigger version of) the following ES6 code earlier, and discovered it didn't work after 6to5 had transpiled it because I'd happened to use the variable name 'module':

```javascript
let module = {
  uhoh: true
};

export default module;
```

6to5 generates this code in response:
```javascript
"use strict";

var module = {
  uhoh: true
};

module.exports = module;
```
which obviously doesn't work correctly because there's a confusion about what `module` is.  Similar things happen when generating AMD code.

It would be nice if 6to5 issued an error/warning about the naming collision at compilation time, or (even better, but much more costly, obviously) generated working code for this scenario, maybe by renaming the module variable or other scoping magic.

**Comment by sebmck** [comment]
Hm, there's a few potential solutions that I can think of off the top of my head, not sure what one's the nicest.

 - Remap `let` variables at the top level (these are currently ignored)
 - Add an optional `duplicateDeclarationCheck` transformer. Similar to the `undeclaredVariableCheck` transformer. It wouldn't be enabled by default though so this wouldn't catch this issue.
 - Automatically remap variables that collide with potential globals. Not too sure about this one as it seems really finnicky.

**Comment by appden** [comment]
Your third option seems really general. It sounds like the `CommonJSFormatter` should just alias `module`, `exports`, and `require` if necessary (i.e. the ES6 module creates a variable of that name in the top-level scope).
