### ISSUE TITLE
Array.from needs to be polyfilled.

### ISSUE THREAD

**Issue by hemanth** [6to5/6to5#646]
```js
[ ... documnet.querySelectorAll('*') ];

```

Spat out:

```
"use strict";

var _toArray = function (arr) { return Array.isArray(arr) ? arr : Array.from(arr); };

[].concat(_toArray(documnet.querySelectorAll("*")));
```

`Array.from` needs a polyfill, cause it's from `ES6` 

//cc @sebmck  

P.S: Eger to fix, sleepy to search ;)

**Comment by zloirock** [comment]
[Hmm?](https://6to5.org/docs/usage/caveats/#polyfills)

**Comment by hemanth** [comment]
@zloirock What part in the code is converting splat within an array? We must use `Array.from` polyfill.

**Comment by hemanth** [comment]
`require("6to5/polyfill");` Ah, missed it.
