### ISSUE TITLE
FR: Add a comment for those which need polyfill.

### ISSUE THREAD

**Issue by hemanth** [6to5/6to5#648]
All of [these](https://6to5.org/docs/usage/caveats/#polyfills) features that need a ployfill, should have a comment once transpiled.

For example:

```js
[ ... documnet.querySelectorAll('*') ];
```

```js
"use strict";

// Requires Array.from ployfill, please require("6to5/polyfill");
var _toArray = function (arr) { return Array.isArray(arr) ? arr : Array.from(arr); };

[].concat(_toArray(documnet.querySelectorAll("*")));
```

Or something similar.

**Comment by sebmck** [comment]
[There already is.](http://6to5.org/docs/usage/caveats/)

**Comment by hemanth** [comment]
I think I didn't put it in a right way, I'm aware of the cavets link, bit wouldn't be easier if the transpiled code had a comment? At least in the REPL ?
