### ISSUE TITLE
Support for module in karma

### ISSUE THREAD

**Issue by janbaer** [6to5/6to5#650]
I'm trying to use the karma-6to6 preprocessor to export a module with the es6 syntax and the import it in a jasmine test, but it doesn't works.

This is my exported function.

````
export function bar() {
  return 'bar';
}
`````

I imported it in my test, but when I try to execute my test I get the following error on the console 

````
ReferenceError: Can't find variable: exports
at module1.es5.js:3
````
````
"use strict"
nexports.bar = bar;

function bar() {
  return "bar"
}

````

module1.js contains the exported function. Where is here the problem?

**Comment by douglasduteil** [comment]
> I'm trying to use the karma-6to6 preprocessor

the "karma-6to6 preprocessor" you mean "karma-6to5-preprocessor" right ?
You might consider open an issue here : https://github.com/6to5/karma-6to5-preprocessor

**Comment by janbaer** [comment]
Yes, of course 6to5.

**Comment by sebmck** [comment]
This isn't really a 6to5 issue and more with your karma setup because `exports` being undefined is an issue with your environment, not the transpilation.

**Comment by janbaer** [comment]
Is there a library available that brings this function in the global namespace? I tried **common.js** but it doesn't helped.

**Comment by sebmck** [comment]
@janbaer I'm unsure what you mean. I'm completely unfamiliar with how karma works. Where are you executing your tests, in node or the browser?

**Comment by janbaer** [comment]
The tests will be execute in a browser environment, not in node. Normally I'm using phantom.js but it's also possible to use Chrome or Firefox. What I mean is, if there's a pollyfill available. For phantom.js for example I need a pollyfill to supporting the **bind** function, that is in the other browsers natively supported.

**Comment by sebmck** [comment]
@janbaer Then you'd need a module bundler. 6to5 can't magically make modules work unfortunately. 6to5 will map ES6 modules to a module format, by default it's CommonJS, see the [module docs](http://6to5.org/docs/usage/modules) for more info. You'll likely have to do something like what's mentioned in [this](http://stackoverflow.com/questions/26192155/karma-cant-find-variable-exports) stackoverflow question.

**Comment by janbaer** [comment]
Is there a polyfill available that can do this in a brower session without creating and compiling it before? I need this feature just for educational purposes not for the production code.

**Comment by sebmck** [comment]
@janbaer No because you can't polyfill CommonJS.

**Comment by douglasduteil** [comment]
@janbaer Try out SystemJs (https://github.com/systemjs/systemjs/wiki/Module-Format-Support) or Browserify

**Comment by sebmck** [comment]
Closing this as it's not an issue related to 6to5. Thanks!

**Comment by cameronjroe** [comment]
For people running into this issue when testing in the browser. Use [karma-browserify](https://www.npmjs.com/package/karma-browserify). Works like a charm.

**Comment by janbaer** [comment]
Thanks for the hint! Will try it!
