### ISSUE TITLE
Support centralized runtime without selfContained

### ISSUE THREAD

**Issue by loganfsmyth** [6to5/6to5#651]
2.x -> 3.x removed 'runtime' and added 'selfContained', but this means that there is no longer an easy way to share the runtime helpers without also requiring the non-polyfill version of core-js, meaning that if you want both polyfilling behavior and shared runtime helpers, you have to use two separate copies of core-js.

Thanks!

**Comment by sebmck** [comment]
- [ ] Generator
 - [ ] API
 - [ ] CLI API
 - [ ] Docs

**Comment by sebmck** [comment]
Added the optional runtime back in 3.3.0. Ping @josh just FYI.

**Comment by josh** [comment]
@sebmck thanks for the heads up!
