### ISSUE TITLE
3.3.1 issue?

### ISSUE THREAD

**Issue by guybedford** [6to5/6to5#654]
I'm getting - 

```
Uncaught AssertionError: embedded: did not recognize object of type "File"browser.js:9 129.exports.parsebrowser.js:4 27.File.parsebrowser.js:6 transformbrowser.js:4 26.transform.runbrowser.js:4 26.execbrowser.js:4 26.runScripts
```

I also had a user independently verify this - https://github.com/systemjs/builder/issues/60#issuecomment-72364321.

If I clone from master and run a custom build for `browser.js` the issue goes away though.

Let me know if you have any ideas.

**Comment by sebmck** [comment]
This is likely being thrown by `regenerator-6to5`. I have an npm linked copy which may be the cause. I'll push out a new build/version to verify.

**Comment by sebmck** [comment]
Pushed out `3.3.2`, let me know if the `browser.js` build within works.

**Comment by guybedford** [comment]
Thanks, that's fixed it.

**Comment by sebmck** [comment]
Great, I'll do #655 ASAP to ensure this never happens again.
