### ISSUE TITLE
bug: `let` inside braceless block

### ISSUE THREAD

**Issue by aeosynth** [6to5/6to5#657]
```js
if (true)
  let foo
```
```
SyntaxError: foo.js: Unexpected token (2:2)
  1  | if (true)
> 2  |   let foo
     |   ^
  3  | 
```

works fine with `var`, or with braces added

**Comment by sebmck** [comment]
This is inline with the spec, see marijnh/acorn#202.

**Comment by Dashed** [comment]
Out of curiosity, why are variable declarations considered "statements"?

**Comment by eventualbuddha** [comment]
Variable declarations are considered statements because they cannot be used to generate a value. That is, this does not work:

```js
foo(var bar = 1);
```

Could the language have been written in a way to make them expressions? Sure, but that isn't the world we live in.

**Comment by fkling** [comment]
@eventualbuddha: I think @Dashed was rather thinking about why a `var` statement isn't a *declaration* (in the spec sense) instead of a statement.

**Comment by eventualbuddha** [comment]
Oh, sorry if I misunderstood. I don't have a very encyclopedic knowledge of the spec, so I'd be curious to know what the distinction is too, if there is one. I've always thought of them as declarations and of declarations as statements.

**Comment by Dashed** [comment]
Yep. Pretty much what @fkling said :) I only noticed it when I skimmed through the spec. Though, I'm suspecting it's just a grammar thing.

**Comment by fkling** [comment]
@eventualbuddha: Well, variable declarations are statements. However, *function declarations* are not (or have been not) statements. That's why the following is technically invalid according to the spec:

```
if (false) {
    function foo() {}
}
```

but browsers implement different behavior here.

I have thoughts about why a variable declaration (officially `VariableStatement`) was not considered a declaration, but to be really sure, I asked esdiscuss. Will update this post with the link once it's available.

**Comment by Dashed** [comment]
@fkling Thanks for bringing this up on esdiscuss. Looks like Brendan Eich addressed the question. I haven't looked at specs prior to ES5, but I'm surprised it goes all the way back to ES1.

**Comment by sebmck** [comment]
@fkling

```javascript
if (false) {
    function foo() {}
}
```

is actually block scoped according to the ES6 spec AFAIK.

**Comment by fkling** [comment]
@Dashed: No problem! Though I still don't know why `let` and `const` have not been made statements.

@sebmck: Yes, I was referring to ES5. Sorry that was not clear from my post.

**Comment by bucaran** [comment]
@eventualbuddha Thanks.
