### ISSUE TITLE
Error when using `selfContained` and `experimental`

### ISSUE THREAD

**Issue by FWeinb** [6to5/6to5#659]
We are currently in the process of upgrading to `6to5@3.X.X` in SassDoc/sassdoc#355, and want to use selfContained because using core-js in the global namespace doesn't play nice when using sassdoc as a library. 

If selfContained  is combined with experimental and async function are in use, we have the problem that runtime.js in `6to5-runtime/regenerator` will fail with `Uncaught ReferenceError: Promise is not defined` because it isn't polyfilled using a global instance of core-js. 

So what I would like is that `6to5-runtime` would include:
```js
var Promise = require("../core-js").Promise;
```
in `runtime.js` to get async functions working even when there is no global core-js polyfill.

**Comment by sebmck** [comment]
Ah, should be solved by running the `selfContained` transformer over the regenerator runtime. I'll push out a fix.

**Comment by FWeinb** [comment]
Awesome for this super fast response!

**Comment by FWeinb** [comment]
:+1: This was the fastest fix ever. :fireworks:

**Comment by sebmck** [comment]
Should be fixed as of 3.3.3, thanks!

**Comment by pascalduez** [comment]
Thanks a bunch @sebmck !! All tests are green now.

**Comment by sebmck** [comment]
@pascalduez Awesome! Let me know if you have any other issues, more than happy to help.
