### ISSUE TITLE
Nested arrow functions.

### ISSUE THREAD

**Issue by hemanth** [6to5/6to5#662]
Say I have:

```js
export default (fn) => () => {
  console.log(arguments);
};
```

Transpliation results in:

```js
"use strict";
var _arguments = arguments;
module.exports = function (fn) {
  return function () {
    console.log(_arguments);
  };
};
```

Now, the `arguments` would the global, rather than the inner function. 

//cc @sebmck

**Comment by sebmck** [comment]
This is spec behaviour. `arguments` is aliased the same way as `this` in arrow functions.

**Comment by hemanth** [comment]
@sebmck Yikes, I was under the notion, it's only related to lexical context and it's scope, interesting, now how could we even emulate this with fat arrows? (guess it's not possible)

Do you remember the spec section by chance?

**Comment by sebmck** [comment]
@hemanth 

[9.2.13](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-functiondeclarationinstantiation)

> 17.a NOTE Arrow functions never have an arguments objects.

[14.2.17](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrow-function-definitions-runtime-semantics-evaluation)

> Any reference to arguments, super, or this within an ArrowFunction are resolved to their bindings in the lexically enclosing function.

**Comment by sebmck** [comment]
Only way to get the `arguments` object inside an arrow function is with rest parameters. `var foo = (...args) => args;`

**Comment by hemanth** [comment]
Rest params++ true arrays ;) 

I also fooled around with:

```js
export default (fn) => function() {
  console.log(arguments);
};
```
Thanks for the spec links, that was fast.
