### ISSUE TITLE
Declaring variables in arrow function

### ISSUE THREAD

**Issue by barneycarroll** [6to5/6to5#663]
I would expect the following:

```javascript
( () => {
  var foo = 'bar';
} );
```

…to compile to:

```javascript
var foo;

( function(){
  foo = 'bar';
}() );
```

[But instead foo is instantiated as the equivalent of a `let`](https://6to5.org/repl/#?code=(%20()%20%3D%3E%20%7B%0A%20%20var%20foo%20%3D%20'bar'%3B%0A%7D%20)%3B):

```javascript
( function(){
  var foo = 'bar';
}() );
```

**Comment by sebmck** [comment]
The runtime semantics specified in [14.2.17](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrow-function-definitions-runtime-semantics-evaluation) make the function body of an arrow function behave the same as a regular function.
