### ISSUE TITLE
Using arrow functions in combination with JSX

### ISSUE THREAD

**Issue by helpermethod** [6to5/6to5#664]
While this code works fine:

    let products = this.props.products.map(function(product) {
      return (<ProductRow product={product} />);
    });

This one doesn't:

    let products = this.props.products.map(product => {
      (<ProductRow product={product} />);
    });  

(I'm not quite sure if the `()` surrounding the JSX expression are needed).

From my understanding this should work though I am pretty new to both JSX and ES6.

**Comment by sebmck** [comment]
There's only an implicit `return` when you pass an expression. So to get your arrow function example to work it'd be either:

```javascript
let products = this.props.products.map(product => {
  return <ProductRow product={product} />;
});
```

or

```javascript
let products = this.props.products.map(product => <ProductRow product={product} />);
```
