### ISSUE TITLE
6to5-node doesn't propagate signals

### ISSUE THREAD

**Issue by atombender** [6to5/6to5#669]
Consider the following naive script:

```javascriot
#!node_modules/.bin/6to5-node

setInterval(function() {
  console.log("output");
}, 500);
```

It results in the following process tree, seen with `pstree`:

```
 | |   \-+= 06922 alex node node_modules/.bin/6to5-node -c ./test.js
 | |     \--- 06923 alex node --harmony /tmp/test/node_modules/6to5/bin/_6to5-node -c ./test.js
```

If you send `SIGTERM` to the parent process (PID 6922), it will kill the parent, but the child continues to run.

One solution is to propagate `SIGTERM` but trapping it with `process.on('SIGTERM')` in the parent and then killing its child. This works for me, `6to5-node` line 59:

```javascript
  process.on('SIGTERM', function() {
    proc.kill('SIGTERM');
    process.exit(128 + 15);  // 128 + SIGTERM
  });
```

That said, I'm not going to claim extreme familiarity with how Node treats spawned processes.

**Comment by sebmck** [comment]
Should have been fixed by #281. Do you have kexec installed? Ping @monsanto

**Comment by atombender** [comment]
My apologies, seems like I wasn't running an ever so slightly old version, when I thought I was running the latest release. Confirmed that the latest release does use `kexec`.

**Comment by caseywebdev** [comment]
I think this problem is back.

Given **test.js**

```js
var id = setTimeout(function () {}, 30000);

process.on('SIGTERM', function () {
  console.log('SIGTERM received!');
  clearTimeout(id);
});
```

```bash
$ node test.js &
[1] (pid)
$ kill (pid)
SIGTERM received!
$ ps | grep [n]ode
$ babel-node test.js &
[1] (pid)
$ kill (pid)
$ ps | grep [n]ode
(babel-node has exited, but lib/_babel-node is still running)
```

**Comment by sebmck** [comment]
@caseywebdev It's not. `kexec` is just an optional node module now. Install it and this problem will go away.

**Comment by caseywebdev** [comment]
Alright, thanks.
