### ISSUE TITLE
[feature request] 6to5 options in inline comments?

### ISSUE THREAD

**Issue by UltCombo** [6to5/6to5#670]
I'd like to be able to specify compile options in comments, similar to JSHint, JSCS and the Traceur REPL. For example:

JSHint comments are in the format:

```js
/* exported Harmonic */
/* global __HARMONIC */
/* jshint mocha: true */
```

JSCS comment directive example:

```js
// jscs: disable disallowSpacesInFunctionExpression, disallowSpacesInAnonymousFunctionExpression
```

[Traceur REPL example](http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--async-functions%20%0A):

```js
// Options: --async-functions
```

Could 6to5 support a similar comment syntax to specify file-specific configs? For instance, it could be a comment that begins with `6to5:` followed by a JSON/JS object literal containing options that get merged into the current configs. Whitespace before/after the "6to5:" prefix could be disregarded for readability/user-friendliness. Example:

```js
// 6to5: { optional: null, experimental: true }
```

To avoid unnecessary complexity, those options could only be valid at the top of the file before any source code (other than comments and whitespace) are processed.

And if this sounds like a reasonable request, have no rush, this can be implemented and documented after the rebranding if you prefer. :stuck_out_tongue:

**Comment by sebmck** [comment]
In order to get the comments the file would need to be parsed first. This is difficult and would be extremely limiting since 6to5 (and acorn) can't selectively parse and transform a file. A possible, more easier, and arguably more powerful alternative is #351.

**Comment by UltCombo** [comment]
@sebmck ohh, rc files are better indeed!
