### ISSUE TITLE
repl gets angry if you throw in a finally block

### ISSUE THREAD

**Issue by bmeck** [6to5/6to5#671]
probably really low priority

```
function* f() {
  try {
  }
  finally {
    throw new Error('b');
  }
}
try {
  f().next();
}
catch (e) {
  console.error(e);
}
```

**Comment by sebmck** [comment]
Looks like this is actually due to the `console.error` call and unrelated to the generators/try-catch. Can you reopen this on the [6to5.github.io](https://github.com/6to5/6to5.github.io) repo? Thanks!

**Comment by sebmck** [comment]
Superseded by 6to5/6to5.github.io#115
