### ISSUE TITLE
By the spec, the default export object should be the `default` property of the namespace object.

### ISSUE THREAD

**Issue by ikarienator** [6to5/6to5#673]
In the 2.x and later versions of the CommonJS module renderer, the default exports are exported as the module object itself. 

For  example:

```es6
export default 0;
export var y = 1;
```
is transpiled to:

```js
exports["default"] = 0;
var y = exports.y = 1;
module.exports = _extends(exports["default"], exports);
```

This is a problem because:

* It violates the [spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-resolveexport);
* other exports contaminate the default exports object;
* primitive values cannot be default exports.

Some old versions of 6to5 do generate correct code for default export/import.

```js
exports["default"] = 0;
var y = exports.y = 1;
```

We should revert to this old behavior.

**Comment by sebmck** [comment]
Upgrade to 3.0.0, the behaviour has actually changed to what you've suggested.

**Comment by michaelficarra** [comment]
Awesome! @jsoverson.

**Comment by sebmck** [comment]
Pre-3.x CommonJS interop was atrocious and I regret it a lot. In 3.x there's an `_esModule` property that gets set on `exports`. `module.exports` is only set with the default export if it's the only export in the file. This isn't an issue and behaves perfectly since it doesn't have an `_esModule` property and so it's subject to the same interop so `export * from "foo";` and `import * as foo from "foo";` work properly.

**Comment by michaelficarra** [comment]
@sebmck Does this mean I can't export something called `__esModule`?

**Comment by sebmck** [comment]
@michaelficarra Yeah it does, no way around that. Worthy tradeoff IMO.

**Comment by sebmck** [comment]
Should actually make trying to export that throw an error.

**Comment by michaelficarra** [comment]
> `module.exports` is only set with the default export if it's the only export in the file

Wait, actually that's a huge issue. If I have a default export and then I add an additional named export, it will break my module's interface. The default will now be assigned to the `default` property. 6to5 should never assign the default to `module.exports` directly.

**Comment by sebmck** [comment]
@michaelficarra Use the `commonStrict` module formatter then if this worries you. This has been discussed **extensively** and it's been widely agreed to be a worthwhile tradeoff . See #95 #224 #493 #587.

**Comment by michaelficarra** [comment]
Sorry, I didn't know about `commonStrict`. It's not in [the documentation](http://6to5.org/docs/usage/modules/).

**Comment by sebmck** [comment]
@michaelficarra Huh, weird. Either I forgot to add it or it was lost in the website transition. Thanks for the heads up!

**Comment by timoxley** [comment]
Would it be more appropriate to use a `Symbol()` rather than magic `__esModule` String key? I don't see that discussed in any of the issues but it seems like a good usecase for a Symbol.

**Comment by sebmck** [comment]
@timoxley That would require a Symbol polyfill for everyone who used modules which is out of the question. `__esModule` is also used by [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler) and [Traceur](https://github.com/google/traceur-compiler) so there's already a community established standard and all modules generated will behave nicely together.

**Comment by timoxley** [comment]
I was thinking `coreAliasing` style

**Comment by sebmck** [comment]
@timoxley As in, importing `core-js/library` and using a symbol? You'd still need to store the symbol reference somewhere and it'd require every single user to bundle 30KB of `core-js` runtime code.

**Comment by timoxley** [comment]
> __esModule is also used by es6-module-transpiler and Traceur so there's already a community established standard and all modules generated will behave nicely together.

This is reason enough to not use a symbol. np.
