### ISSUE TITLE
Error when adding method to class

### ISSUE THREAD

**Issue by ismaelaarab** [6to5/6to5#680]
When i add method like this 

```javascript
    test() {
        console.log("test");
    }
```

i get a error 

`ERROR in ./client/authentication/authentication.controller.js
Module not found: Error: Cannot resolve module '6to5-runtime/helpers' in C:\wamp\www\app\client\authentication  @ ./client/authentication/authentication.controller.js 3:18-49`

i use webpack with 6to5-loader

**Comment by sebmck** [comment]
Remove `optional=selfContained` from your webpack config.
