### ISSUE TITLE
Spec compatibility: Empty object pattern and null/undefined

### ISSUE THREAD

**Issue by fkling** [6to5/6to5#681]
According to the [newest draft (rev32)](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts#february_2_2015_draft_rev_32), assigning `null`/`undefined` to an empty object pattern should throw:

```js
function foo({}) {
  console.log(42)
}
foo(); // expected error
```

**Comment by sebmck** [comment]
What do you propose as the solution? Easiest way is to probably just add another helper:

```javascript
var _ensureNotNull = function (obj) {
  if (obj == null) throw new ReferenceError("foobar");
  return obj;
};
```

and then wrapping all object destructuring in a cal.

**Comment by sebmck** [comment]
@fkling Unrelated question but jstransform ES6 transforms, the classes one in particular, have a lot of discrepancies compared to actual ES6 class semantics. Should I open an issue or is it a known issue? Happy to submit a PR.

**Comment by fkling** [comment]
Looks like "7.2.1 RequireObjectCoercible ( argument )" is what is used to check whether the value is an object, and it throws a type error for `undefined` and `null`. I think we could get away with only injecting the call if the pattern is empty. If it is not it will throw anyway when trying to access the properties.

> Should I open an issue or is it a known issue? Happy to submit a PR.

I saw you already did that :) :+1:

**Comment by sebmck** [comment]
@fkling Hm yeah, that sounds like a good compromise.

**Comment by danielgindi** [comment]
An empty destructuring is a valid one, currently the code looks for an empty one and not necessarily a `null`/`undefined`, which breaks valid JS code
