### ISSUE TITLE
Constructors don't inherit properly

### ISSUE THREAD

**Issue by thejameskyle** [6to5/6to5#684]
> Moving from https://github.com/6to5/6to5ify/issues/34, thanks @radiosilence 

Paste this into the REPL.

    class A {
      constructor(name) {
        this._name = name;
      }
      sayHi() {
        console.log(`Hi, I'm ${this._name}`);
      }
    }
    
    class B extends A {}
    
    var a = new A("foo");
    a.sayHi();
    
    var b = new B("foo");
    b.sayHi();

Expected output:

    Hi, I'm foo
    Hi, I'm bar

Output:

    Hi, I'm foo
    Hi, I'm [object Object]

**Comment by sebmck** [comment]
Fixed as of 3.3.9

**Comment by radiosilence** [comment]
You're the tits!
