### ISSUE TITLE
Named exports aren't working

### ISSUE THREAD

**Issue by JannesMeyer** [6to5/6to5#685]
#### main.js
```javascript
import test from './test';
test.hello();
```

#### test.js
```javascript
export function hello() {
	console.log('Hello World');
}
```

After transpiling these files with 6to5 (v3.3.7) and executing main.js it results in this error:
```
test.hello();
    ^
TypeError: Cannot read property 'hello' of undefined
```

Am I misunderstanding ES6 modules or should this work?

The problem seems to be in `_interopRequire` in the transpiled version of `main.js`:
```javascript
var _interopRequire = function (obj) { return obj && obj.__esModule ? obj["default"] : obj; };
```
There is no `default` attribute on the exported object of `test.js`

**Comment by appden** [comment]
If you want to import the whole module as `test`, then you want to do `import * as test from './test'`. Alternatively, if you just want to import `hello`, then you could do `import { hello } from './test'`.

**Comment by JannesMeyer** [comment]
Yes, basically I want to import the whole module as test. `import * as test from './test'` does what I want. Thank you!

Now I'm just a little bit confused if `import test from './test';` is supposed to be `undefined` when there is no default export or if it's a deficiency of 6to5. I'm asking because I remember `import test from './test';` working in Traceur perfectly fine a while ago.

**Comment by sebmck** [comment]
@JannesMeyer If it worked perfectly in Traceur then it shouldn't have. With the example `import foo from "foo";` you're explicitly asking for the default export. As @appden said to get the behaviour you expect you'd have to use `import * as test from './main';`

**Comment by JannesMeyer** [comment]
Ok, thanks! My bad.

**Comment by sebmck** [comment]
@JannesMeyer No problem! Feel free to open another issue if you run into any more problems or check out our [gitter](https://gitter.im/6to5/6to5).
