### ISSUE TITLE
Support browerslist

### ISSUE THREAD

**Issue by wrumsby** [6to5/6to5#686]
[browserslist](https://github.com/ai/browserslist) provides a way for projects to describe the browsers they need to support which is then used by tools like Autoprefixer to generate the appropriate CSS for that set of browsers.

6to5 could use this metadata + [caniusedb](https://www.npmjs.com/package/caniuse-db) to selectively transpile features based on browser support.

**Comment by sebmck** [comment]
Duplicate of #631
