### ISSUE TITLE
Ability to transpile in node using require()

### ISSUE THREAD

**Issue by aexmachina** [6to5/6to5#687]
traceur has the ability to transpile modules when they're loaded using `require()` - so you can start your program with `node` and then every file that's loaded after the `index.js` is transpiled when it's loaded. This is pretty convenient, but traceur sucks a bit so I'm wondering if this is possible using 6to5?

Our usage of this traceur feature is as follows:

```js
var traceur = require('traceur');
traceur.require.makeDefault(shouldTranspile);
require('traceur-source-maps').install(traceur);
function shouldTranspile(file) {
  // transpile only files in the project but not in node_modules
}
```

**Comment by fkling** [comment]
https://6to5.org/docs/usage/require/

**Comment by aexmachina** [comment]
Awesomez. Thanks.

**Comment by sebmck** [comment]
There's also [6to5-node](https://6to5.org/docs/usage/cli/#6to5-node) which makes it even easier.
