### ISSUE TITLE
Cannot Inherit From Class Whose Module Has A Named and Default Export (CommonJS)

### ISSUE THREAD

**Issue by minznerjosh** [6to5/6to5#692]
```javascript
// View.js
export const views = new WeakMap();

export default class View {}
```
```javascript
// ButtonView.js
import View from 'View.js';

export class ButtonView extends View {}
```

When doing
```javascript
import ButtonView from 'ButtonView.js';
```
```ButtonView``` is actually a reference to ```View``` because of this:
```javascript
exports['default'] = View;
var views = exports.views = new WeakMap();
module.exports = _extends(exports["default"], exports);
```
Now ```View.default === View```. When ```ButtonView``` inherits from ```View```, it gets ```View```'s static ```default``` property. Finally, when importing ```ButtonView```, it is run through this function:
```javascript
var _interopRequire = function (obj) {
  return obj && (obj["default"] || obj);
};
```
Which, of course, returns ```View```, not ```ButtonView```.

**Comment by minznerjosh** [comment]
I was able to avoid this issue by using ```commonStrict```, but I feel like I shouldn't need to do that. Why do I remember seeing checks for ```__es6Module``` in the compiled source previously (not any more?) Or am I thinking of something else?

**Comment by sebmck** [comment]
Upgrade to 3.x which has the `__esModule` checks.
