### ISSUE TITLE
Destructured assignment in Lambdas (Arrow Functions) not working for objects

### ISSUE THREAD

**Issue by blesh** [6to5/6to5#693]
The following will not transpile:

```js
var myThing = ({ foo, bar }) => foo + bar;

myThing({ foo: 1, bar: 2 });  // 3
```

I noticed this in an Ember-CLI build using modules `ember-cli-6to5 3.0.0 -> broccoli-6to5-transpiler 3.0.0 -> 6to5-core ^3.0.0`

**Comment by blesh** [comment]
When I was digging into this (just browsing source, not stepping through), I couldn't find where `isObjectPattern` is defined. [found here](https://github.com/6to5/6to5/blob/ea2ad960897bed599b3f4648f42900c2f346433a/lib/6to5/transformation/transformers/es6/destructuring.js#L44)

**Comment by blesh** [comment]
Actually, it appears this doesn't work from Arrays in arrow functions either. Is this by design? Perhaps I'm just not familiar enough with the spec.

**Comment by jridgewell** [comment]
Seems to be working fine on the [website's repl](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=var%20myThing%20%3D%20(%7B%20foo%2C%20bar%20%7D)%20%3D%3E%20foo%20%2B%20bar%3B%0A%0AmyThing(%7B%20foo%3A%201%2C%20bar%3A%202%20%7D)%3B%20%20%2F%2F%203)

Maybe you're using an outdated version?

**Comment by blesh** [comment]
@jridgewell  ... yeah, it's starting to look that way. I double checked, and I could have sworn it was the latest version. Thanks.

**Comment by sebmck** [comment]
@blesh `t.is*` methods are dynamically created based on [this](https://github.com/6to5/6to5/blob/ea2ad960897bed599b3f4648f42900c2f346433a/lib/6to5/types/visitor-keys.json) file.

**Comment by blesh** [comment]
Interesting. Thanks for pointing that out. I'm interested at stepping through this code a bit when I get the chance. It's cool stuff.
