### ISSUE TITLE
CLI: module options collision

### ISSUE THREAD

**Issue by ooflorent** [6to5/6to5#696]
The short option names of the following options are the same:

```
    -m, --modules [modules]      Module formatter type to use [common]
    -m, --module-ids             Insert module id in modules
```

Moreover `--module-ids` description is unclear. Could you enrich its documentation?

**Comment by sebmck** [comment]
Good catch, thanks! The module ids are for enabling ids for SystemJS/UMD/AMD. Odds are if you don't know what they are then you probably don't need them.
