### ISSUE TITLE
Problematic "core-js/shim" dependency in polyfill.js

### ISSUE THREAD

**Issue by mpal9000** [6to5/6to5#698]
Hi, there is a problem with https://github.com/6to5/6to5/blob/master/lib/6to5/polyfill.js#L8
It could be `require("6to5-runtime/core-js");` with a note in https://6to5.org/docs/usage/require/ and https://6to5.org/docs/using-6to5/#mocha or be a dependency of 6to5 https://github.com/6to5/6to5/blob/master/package.json#L36

**Comment by sebmck** [comment]
`6to5-runtime` is built on each new version release so you can't really depend on it internally. The `core-js` dependency is also using a caret so @zloirock can push changes/fixes/patches/whatever and it'll be automatically fixed for all 6to5 users instead of having to bump the version.

**Comment by mpal9000** [comment]
ok thanks
