### ISSUE TITLE
_classCallCheck broke my code

### ISSUE THREAD

**Issue by lukescott** [6to5/6to5#700]
I have something like this:

```javascript
export function mixin(base, ...traits) {
	let ctor = function() {
		base.apply(this, arguments);
		for (let trait of traits) {
			trait.apply(this, arguments);
		}
	};
	...
}
```

Which allows me to do this:

```javascript
class Trait {
...
}
class Base {
...
}
class Person extends mixin(Base, Trait) {
...
}
```

And now I'm getting "Cannot call a class as a function". I suspect that this is because my traits are classes.

How do I turn this off? Is this something new in the ES6 spec?

**Comment by AluisioASG** [comment]
Yes for spec, see #682.

**Comment by lukescott** [comment]
@AluisioASG What am I supposed to do here? This change makes it impossible to do things like traits.

**Comment by AluisioASG** [comment]
If you're ok with it, you could use objects as traits, then `extend Base` and mixin the traits later.  @sebmck any other ideas?

**Comment by lukescott** [comment]
I just discovered that my whole implementation is broken because of _classCallCheck and methods enumerable changing to false. My traits were classes so they could inherit from other traits. I was using for in to copy all properties to ctor.

Looks like my only option is to use objects as traits. `trait.apply(this, arguments);` fails because of `_classCallCheck`, but `base.apply(this, arguments);` doesn't, which is a good thing, but is this also illegal according to the spec? I don't want this new implementation to break in node --harmony later.

**Comment by sebmck** [comment]
@lukescott Yeah, class methods were made enumerable at the last TC39 meeting. I've submitted a pull request to make methods enumerable in jstransform that has now been merged too (facebook/jstransform#60).

It's illegal to call class constructors as normal functions which is why you see the following (contrived example):

```javascript
function Foo() {
  if (!(this instanceof Foo)) throw new Error("Not calling via `new`!");
}
```
From checking the spec `Function.prototype.apply` and `Function.prototype.call` all use the internal slot `[[Call]]` which in [9.2.2 2](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ecmascript-function-objects-call-thisargument-argumentslist) makes it illegal to call at all:

> If F’s [[FunctionKind]] internal slot is "classConstructor", throw a TypeError exception.

So you can rely on this behaviour being spec compliant.

**Comment by lukescott** [comment]
So are you saying even this is illegal:

```javascript
class Foo {
constructor() {}
}

function ctor() {
    Foo.call(this);
}
ctor.prototype = Object.create(Foo.prototype);
ctor.prototype.constructor = Foo;

new ctor();
```

???

**Comment by sebmck** [comment]
@lukescott It seems so, yes.

**Comment by lukescott** [comment]
@sebmck is this legal:

```javascript
class Foo {
    constructor() {}
}

function extend(constructor) {
    var ctor = class extends constructor {}
    ....
}
```

?

**Comment by sebmck** [comment]
@lukescott I don't understand your example.

**Comment by lukescott** [comment]
@sebmck I'm trying to accomplish the same thing as before, just in a spec compliant way. Essentially I need a copy of the class to add methods to without changing the base class.

**Comment by sebmck** [comment]
@lukescott Do you need to inherit the constructors?

**Comment by lukescott** [comment]
@sebmck I need a new class that looks exactly like Foo, but isn't Foo. A copy basically, which is what the code with `Object.create(Foo.prototype)` was doing. On the copy I need to copy methods from traits. Some of my traits did have constructors called by super(), but I'll just change those to something like `initTraitName` and call them in the constructor consuming the trait.

If `function extend(constructor) { var ctor = class extends constructor {} }` is spec complaint I can avoid the `Foo.call(this);` call.

**Comment by sebmck** [comment]
@lukescott Yep, that should work then.

**Comment by lukescott** [comment]
@sebmck Awesome! Hopefully this implementation will be future proof until ES7 has traits :).

**Comment by sebmck** [comment]
@lukescott Yeah, ES6 classes are extremely weak compared to what they've could've been.

For those of you just finding this issue, @lukescott started a thread on [esdiscuss](https://esdiscuss.org/topic/traits-are-now-impossible-in-es6-until-es7-since-rev32) that goes into more detail.

**Comment by k1r0s** [comment]
not sure about this. Basically the specs doesn't complain about overriding a constructor. Its only about creating instances without using `new` keyword

**Comment by nicolo-ribaudo** [comment]
`Class.apply()` should thow, so Babel is correct in this case.

**Comment by k1r0s** [comment]
agree @nicolo-ribaudo
