### ISSUE TITLE
Class inheritance broken in IE 8 w/ es5-shim

### ISSUE THREAD

**Issue by lukescott** [6to5/6to5#703]
Class inheritance is broken in IE 8, even with es5-shim. Specifically `this.constructor` is wrong in an inherited class.

The following fixes that:
```javascript
var _inherits = function(subClass, superClass) {
    if (typeof superClass !== "function" && superClass !== null) {
        throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
    }
    subClass.prototype = Object.create(superClass && superClass.prototype, {
        constructor: {
            value: subClass,
            enumerable: false,
            writable: true,
            configurable: true
        }
    });
    if (subClass.prototype.constructor !== subClass) {
    	subClass.prototype.constructor = subClass; // <-- corrects constructor
    }
    if (superClass) _defaults(subClass, superClass);
};
```

The reason it is broken is because the following doesn't work in IE8:

```javascript
var properties = {
    constructor: {}
};
for (var name in properties) {
    console.log(name); // <-- constructor is never iterated even though it is user defined
}
```

**Comment by sebmck** [comment]
While your suggested fixed will indeed fix this specific issue, it's a slippery slope to start implementing hacks to support IE8 and it's not worth the maintenance burden. Vendors have already jumped ship on maintaining IE8 and even Microsoft wont support it in a ~years time.

IE8 doesn't support `Object.defineProperty` (and many other things) so if you want to use 6to5 and ES6 features then you have to limit yourself to a subset as there are just some things that can't be done in ES3 without runtime interaction. This is documented in the [FAQ](http://6to5.org/docs/faq/#what-is-the-browser-compatibility-) and [caveats](http://6to5.org/docs/usage/caveats/).

**Comment by lukescott** [comment]
@sebmck Yep, I know. I am restricting myself to a subset, believe me (I don't use getters/setters, etc.). Also don't have a choice when 11% of our traffic comes from IE 8 :). Anyway, the problem is with es5-shim, not 6to5. When I use core-js it works fine. core-js probably checks for the constructor property. For some reason I thought it didn't work with core-js either, but I had it specified in the wrong karma config and I was still including es5-shim.

Anyway, I'm not sure it's really a hack. It's just a compatibility issue with other es5 shims. And many of the other ones I've tried get it wrong. Doing a Object.defineProperty after Object.create would also work on most shims since it avoids the for in loop.

**Comment by sebmck** [comment]
@lukescott Ah right. I'm just hesitant to add a lot of weight to the existing helpers to support legacy stuff. @zloirock has done an amazing job on making core-js work consistently well across a myriad of browsers and environments.

**Comment by piotr-cz** [comment]
In the Babel docs should be stated that the transpiler requires min. IE9+ to work (because at least `Object.defineProperty` is not supported in there)

**Comment by zloirock** [comment]
@piotr-cz should not. `babel` uses `Object.setPrototypeOf` / `__proto__` for subclassing, but it does ot mean it's not support IE10- - available alternative transformers. `babel` actively uses `Symbol.iterator`, `Object.assign`, `Array.from`, which missing in all versions IE, but it does not mean it's not supports IE - just use [polyfill](https://babeljs.io/docs/usage/polyfill/). The same situation with `Object.defineProperty` in IE8- - use polyfill and remember you can't use getters / setters.

**Comment by piotr-cz** [comment]
ATM Documentation says that polyfill should be used for Iterators, Generators, Maps and Sets, Symbols, Promises and Reflect API, but it's required for at least Classes in order to use in IE8.

**Comment by zloirock** [comment]
> For documentation and website issues please visit the [babel.github.io](https://github.com/babel/babel.github.io) repo.

If you think it will be more clearly - you can add PR :)
