### ISSUE TITLE
In commonStandard mode, export default x should work exactly like export { x as default }.

### ISSUE THREAD

**Issue by ikarienator** [6to5/6to5#706]
According to [15.2.3.4](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports-static-semantics-exportednames), `[[ExportName]]` for `export default` should be exactly `"default"`. There shall be no way in ES6 to replace the entire module object (in commonJS, `module.exports`).

The current (3.4.0) behavior:

```es6
export default 0
```

generates:
```js
"use strict";

module.exports = 0;
```

whereas it should be:

```js
"use strict";

module.exports.default = 0;
```

**Comment by sebmck** [comment]
Gah, tests should have caught this. Fixed as of 3.4.1, thanks!
