### ISSUE TITLE
Scope of parameter default values

### ISSUE THREAD

**Issue by rauschma** [6to5/6to5#710]
Parameter default values live in a scope that surrounds the scope of the body. For example:

```js
let foo = 'outer';
function bar(func = x => foo) {
    let foo = 'inner';
    console.log(func()); // (A)
}
bar();
```

Line (A) logs “inner”, but should log “outer” (if I am reading the spec correctly – let me know if I am).

**Comment by sebmck** [comment]
It does, yeah. I was looking into this today actually, the IIFE invocation just needs to be made smarter.

**Comment by rauschma** [comment]
Only necessary if there are any function expressions, arrow functions or method definitions “inside” the default values.

**Comment by sebmck** [comment]
I'd go a step further and check to see if the functions even contained any references that would necessitate the scope separation.

**Comment by rauschma** [comment]
Very cool!

**Comment by sebmck** [comment]
Actually this is an unrelated bug and completely separate to the scope separation issue I was investigating today.

```javascript
let foo = 'outer';
function bar(func = x => foo) {
    var foo = 'inner';
    console.log(func()); // (A)
}
bar();
```

`var` triggers the IIFE but not `let`. I smell smoke, hopefully there's no fire. I'll investigate in the morning.

**Comment by rauschma** [comment]
In principle you could also rename the local variables to avoid shadowing (vs. using an IIFE to create a new scope).

**Comment by hax** [comment]
FF 40 still output `inner`.

**Comment by hax** [comment]
Broken again! (tested under babel-preset-latest or babel-preset-2015)

This issue need to reopen...
