### ISSUE TITLE
For loop not working in firefox

### ISSUE THREAD

**Issue by Mech7** [6to5/6to5#711]
I have some code like:

```
for (var n of geoHashes) {
  console.log(n);
}
```
Only in firefox it throws an error: ReferenceError: Symbol is not defined

**Comment by zloirock** [comment]
https://6to5.org/docs/usage/caveats/#polyfills

**Comment by Mech7** [comment]
Ah missed that thanks :+1:

**Comment by edravis** [comment]
Also in Safari #1574

**Comment by blomdahldaniel** [comment]
Sorry but I understand that I am a noob here.. I am facing the same issue of *for of* in safari. Am following the link to https://6to5.org/docs/usage/caveats/#polyfills but when I am there i do not understand what i should do. How do I include it? Where does it go? Can i just copy-paste something into my js?
@Mech7 how did you solve it?

**Comment by zloirock** [comment]
@blomdahldaniel actual link http://babeljs.io/docs/usage/polyfill/

**Comment by blomdahldaniel** [comment]
Okey I have spent way too many hours to understand what I should do but I dont get it. Could you explain what I should do, and where i should do it.

I am, as of now, using Laravel elixir that wraps my gulp stuff. I am familiar with gulp otherways. Where should i put the `require("babel/polyfill");` and how do i download that package? npm? What is the package name?

**Comment by loganfsmyth** [comment]
@blomdahldaniel This issue tracker isn't really meant as a support channel. Feel free to join the [Slack community](https://babel-slack.herokuapp.com/) if you'd like a bit more real-time support.
