### ISSUE TITLE
Using 6to5-node from within node_modules causes parsing error

### ISSUE THREAD

**Issue by jameslk** [6to5/6to5#715]
I recently separated my codebase into modules and [put them directly under the node_modules directory](https://github.com/substack/browserify-handbook#node_modules). Unfortunately, I found that running 6to5-node under this directory causes it to no longer function correctly.

To verify that this was indeed the case and not other side effects of my project or the loss of my sanity, I've created a very simple test script and placed it into an empty `node_modules` directory under another empty directory called `test`:

```javascript
// test/node_modules/test.js

let test = 'what is going on';
```

When I run said script like so: `$ 6to5-node node_modules/test.js`, I get the following error:

```bash
test/node_modules/test.js:1
(function (exports, require, module, __filename, __dirname) { let test = 'what
                                                                  ^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/6to5/lib/6to5/register.js:111:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/6to5/bin/_6to5-node:93:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Which is actually strangely similar to just running vanilla node on the script itself (i.e. `$ node node_modules/test.js`):

```bash
test/node_modules/test.js:1
(function (exports, require, module, __filename, __dirname) { let test = 'what
                                                                  ^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

So for whatever reason, it seems to me 6to5-node isn't compiling the code down to ES5 before passing it off to NodeJS.

Now if I simply run `6to5` instead of `6to5-node`, it seems to compile the code just fine:

```bash
$ 6to5 node_modules/test.js 
"use strict";

var test = "what is going on";
```

**Comment by sebmck** [comment]
Yeah so `6to5-node` and `6to5/register` all ignore `node_modules` because all the files inside are considered to be already compiled and it's bad for performance since you're transforming files that don't need to be and sometimes making unsafe transformations that will break the code (such as implicit strict mode).

`6to5-node` has an `--ignore` arg that you can set that will override the default regex of `/node_modules/`. My regex-fu is weak but the following *should* work:

```sh
$ 6to5-node --ignore (?!your_application_root)/node_modules script.js
```

You're going to have to put this in a helper script until #351 is implemented unfortunately.

**Comment by jameslk** [comment]
Ah okay, got it.

This worked for me:
```bash
$ 6to5-node --ignore '/node_modules/(?!my_module1|my_module2)' script.js
```

Thanks!

**Comment by sebmck** [comment]
Great, no problem!
