### ISSUE TITLE
@a[b] throws error: Got a MemberExpression for MemberExpression property

### ISSUE THREAD

**Issue by achicu** [6to5/6to5#717]
The code I used to reproduce:

    function x() {
        @a[b];
    }

The tree has nested MemberExpressions. That's most probably generated by this code in acorn.

    case _at:
      var start = storeCurrentPos();
      var node = startNode();
      var thisNode = startNode();
      next();
      node.object = finishNode(thisNode, "ThisExpression");
      node.property = parseSubscripts(parseIdent(), start);
      node.computed = false;
      return finishNode(node, "MemberExpression");

**Comment by sebmck** [comment]
This should have been removed in v3, it's even included in the changelog, odd.

**Comment by sebmck** [comment]
This was due for removal in 3.x because it's never going to become a part of mainstream ECMAScript and it frees up the use of `@` for annotations/declarators which are eventually going to be implemented.
