### ISSUE TITLE
Some code patterns run 50x slower with 3.5.3 TCO

### ISSUE THREAD

**Issue by peferron** [6to5/6to5#722]
The performance drop happens in a smaller range of situations than the 3.5.1/3.5.2 TCO issues discussed in #721, but it's still there. This pure ES5 snippet:

```javascript
function add(a, b) {
  if (b === 0) {
    return a;
  }
  return add(a + 1, b - 1);
}

var i = 0;
while (i < 1e8) {
  i = add(i, 1);
}
```

runs 50x slower piped through 6to5:

```
$ 6to5-node --version
3.5.3
$ cat bench.js | time node
node  0.58s user 0.02s system 100% cpu 0.593 total
$  6to5 bench.js | time node
node  44.42s user 0.45s system 99% cpu 44.892 total
```

Of course, nobody in their right mind would write an `add` function like this. In most real-world cases, this TCO implementation might be a net benefit.

However, my personal feeling is that it's much easier to not use TCO at all (because you know it's not supported) than to know which part of your code could suffer from TCO implementation details. If it's not possible to have a TCO implementation that keeps any ES5 code running at at least 90% of its previous speed, then I wouldn't do it at all and would just wait for JS engines to implement it. Or at the very least I wouldn't enable it by default.

That's just my own, and probably very conservative, viewpoint though.

**Comment by sebmck** [comment]
Yep, I've discussed with @RReverser about possible optimisations and we have a pretty good idea on how to actually go about doing this and how to even beat the performance of all existing TCO in [this jsperf suite](http://jsperf.com/tco/10). Just need to work out implementation details.

I don't think this is an issue currently because:

1. This code is very unlikely to appear.
2. If it does then TCO is likely necessary to avoid exceeding the call stack.

Also it's worth nothing that **all** 6to5 transformers can be disabled like so:

```sh
$ 6to5 --blacklist es6.tailCall
```

**Comment by peferron** [comment]
I understand keeping this feature enabled. However, regarding your second point - this performance issue doesn't arise with stack-popping deep recursion, it happens with ES5-friendly shallow recursion inside a tight loop.

Implementing TCO via code generation is essentially optimizing deep recursion at the expense of shallow recursion. (Which is a slight issue because shallow recursion works just fine in today's ES5, so probably quite a few people use it. I don't know how many though, so if you tell me that's not relevant I won't disagree.) The jsPerf suite benchmarks deep recursion only (1000 levels deep) so TCO is likely to perform well, but it doesn't tell how it performs with shallow recursion. I would bet that no matter how hard you optimize things, you won't be able to prevent shallow recursion from getting slower. I would love to be proven wrong though, and hope you will be successful. It'd be awesome to have a fully working, zero-drawbacks TCO.

Anyway, as long as you're aware of the issue, my job here is done. Good luck to you and @RReverser!

**Comment by sebmck** [comment]
Once #736 is merged performance will actually be better than the native implementation with the TCO transformation:

http://jsperf.com/6to5-factorial-tco/2

![jsperf](https://cloud.githubusercontent.com/assets/722544/6120076/bf43b236-b0af-11e4-9997-9bb0ea9475b2.png)

**Comment by peferron** [comment]
Looks great! Performance is good even with n = 1. I'll try some other cases after #736 is merged.
