### ISSUE TITLE
Error: URI Malformed error over HTTPS on Try Out Page

### ISSUE THREAD

**Issue by nhunzaker** [6to5/6to5#727]
Check this page out over HTTPs

https://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=

![screen shot 2015-02-08 at 5 27 27 pm](https://cloud.githubusercontent.com/assets/590904/6098825/c77cc85a-afb7-11e4-88f9-50b4539422ce.png)

**Comment by sebmck** [comment]
What browser? Works fine for me in Chrome.

**Comment by nhunzaker** [comment]
Ah yes. What a terrible bug description to give. This is in Chrome. I'll continue to poke around.

**Comment by nhunzaker** [comment]
It looks like, for whatever reason, I had a bad `replState` value in `localStorage`. When I cleared it, the problem went away. Do you think it's worth handling instances where this value is corrupt in `repl.js`?

**Comment by sebmck** [comment]
Yeah it definently is. Can you reopen this issue on the [6to5.github.io](https://github.com/6to5/6to5.github.io) repo? Thanks!

**Comment by nhunzaker** [comment]
Done, https://github.com/6to5/6to5.github.io/issues/129
