### ISSUE TITLE
break 

### ISSUE THREAD

**Issue by alejonext** [6to5/6to5#728]
Well, i read the [break statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/break), bat is dont sopport

**Comment by sebmck** [comment]
Can you elaborate?

**Comment by alejonext** [comment]
No, because they do not know if it's a standard or mozilla

**Comment by sebmck** [comment]
`break` is most definently a standard?

**Comment by alejonext** [comment]
I don't know.

**Comment by sebmck** [comment]
Happy to answer any other questions.

**Comment by alejonext** [comment]
ok!!! Hahaha, I knew it was not a standard! XD

**Comment by sebmck** [comment]
No it is a standard. I'm not completely sure by what you mean. Do you mean if `break` is actually in the spec and implemented across all browsers and environments? Because if so, it is.

**Comment by alejonext** [comment]
ok.....
