### ISSUE TITLE
Polyfill example with browserify

### ISSUE THREAD

**Issue by trusktr** [6to5/6to5#729]
Can you provide a quick example of how I would use polyfills with browserify? I'm interested in the WeakMap.

**Comment by sebmck** [comment]
Just add 6to5 to your dependencies and add:

```javascript
require("6to5/polyfill");
```

See the [docs](http://6to5.org/docs/usage/polyfill/) for more info.

**Comment by sebmck** [comment]
Also the `WeakMap` polyfill **does not** have weak references as that's something that's impossible to shim as it's an implementation detail.

**Comment by trusktr** [comment]
True. I settled with writing a TODO comment to just use them when they are out in the wild.
