### ISSUE TITLE
arrow function brokes this keyword

### ISSUE THREAD

**Issue by 007lva** [6to5/6to5#730]
this works:

![work](https://cloud.githubusercontent.com/assets/1860816/6106870/8642dede-b065-11e4-8ab6-fc00b8419bf1.png)

This does not work:
![notwork](https://cloud.githubusercontent.com/assets/1860816/6106879/9fad72da-b065-11e4-8bf6-f597636160eb.png)

why?

**Comment by sebmck** [comment]
Top level `this` is `undefined` ES6 modules as they're implicitly strict mode. Arrow functions inherit the outer `this`. Expect behaviour.

**Comment by fkling** [comment]
Put differently: If you want a function with its own `this` value, you cannot use an arrow function.

**Comment by sebmck** [comment]
Yeah, I phrased that terribly. Arrow functions aren't synonymous with normal functions. You can check out more about their usage [here](http://6to5.org/docs/learn-es6/#arrows).

**Comment by developit** [comment]
Summary: arrows are awesome

**Comment by 007lva** [comment]
Oh, thank you very much, this is very instructive :smiley:

**Comment by Dashed** [comment]
@sebmck I'm wondering if babel can "warn" the user if `this` is transformed to `undefined` as s/he may unintentionally misused the arrow function? Which is likely the case...

**Comment by sebmck** [comment]
@Dashed I wish, #562.

**Comment by Dashed** [comment]
@sebmck Hmm. What about warning of the misuse of `this` within just arrow functions?

**Comment by sebmck** [comment]
@Dashed It would only catch the top level case and adding warning messages is a slippery slope.

**Comment by bucaran** [comment]
@007lva The value of `this` outside your arrow function is the top level which is `undefined` as ES6 is `'strict mode'` by default.

Look at what the transpiled output becomes if you do this instead:

```js
function it () {
  $('#link').click(() => {
    let x = this.pathname;
  });
}
```

--->

```js
"use strict";

function it() {
  var _this = this;

  $("#link").click(function () {
    var x = _this.pathname;
  });
}
```
