### ISSUE TITLE
Odd issue with arrow functions and this scope

### ISSUE THREAD

**Issue by chrisabrams** [6to5/6to5#733]
When using the npm library [thinky](https://github.com/neumino/thinky), I have the following snippet of code:

    User.pre('save', (next) => {

        console.log("pre save event\n", this)
        next()
 
    })

Where `this` will be undefined. However, if I change the arrow function to an ES5 function:

    User.pre('save', function(next) {

        console.log("pre save event\n", this)
        next()
 
    })

`this` is defined as expected. What would cause `this` to be undefined with an arrow function?

**Comment by developit** [comment]
`this` is lexically scoped in arrow functions. See #730.

**Comment by stebru** [comment]
https://github.com/nzakas/understandinges6/blob/master/manuscript/02-Functions.md#arrow-functions

**Comment by chrisabrams** [comment]
Ah ok...learned something new today :) Thanks @developit and @stebru

**Comment by eventualbuddha** [comment]
@sebmck, this is the third or fourth example of this sort of question being raised. Do you think we should put it on the website or docs somewhere?

**Comment by Dashed** [comment]
Yes please. 
https://6to5.org/docs/learn-es6/#arrows

First sentence is already misleading:
> Arrows are a function shorthand using the `=>` syntax.

**Comment by chrisabrams** [comment]
That is exactly how I was mislead. I did not realize that the `=>` behaves similarly to the `=>` in CoffeeScript.

**Comment by thejameskyle** [comment]
Open an issue in https://github.com/6to5/6to5.github.io please

**Comment by sebmck** [comment]
@eventualbuddha Not sure if there's anything else that can be done since in all the examples where arrow functions are shown they're always presented with an automatic lexical scope binding.
