### ISSUE TITLE
minification.removeConsoleCalls doesn't remove console calls

### ISSUE THREAD

**Issue by silentroach** [6to5/6to5#740]
All console calls remains in the code after processing with minification.removeConsoleCalls turned on.

**Comment by sebmck** [comment]
The `minification` transformers are undocumented and unfinished.

**Comment by silentroach** [comment]
O.o but why it is visible in --help?

**Comment by sebmck** [comment]
Just haven't gotten around to fleshing them out because I've been busy with higher priority bugs and features. I just pushed a patch that fixes it. Probably necessary to add a flag to make transformers hidden too to avoid issues like this in the future.

**Comment by silentroach** [comment]
Be carefull, your commit will break some react tests. Tried to fix it the same way before reporting :)

**Comment by sebmck** [comment]
I know :) Haven't pushed a new release yet because I'm still doing some work.
