### ISSUE TITLE
Tail recursion optimization breaks some (tortuous) uses of bind()

### ISSUE THREAD

**Issue by peferron** [6to5/6to5#744]
```javascript
'use strict';

function test(exit) {
  if (exit) {
    return this.x;
  }
  return test(true);
}

test = test.bind({x: 'yay'});

console.log(test());
```

```
$ node test.js
yay

$ 6to5-node test.js
/Users/peferron/tco/test.js:5
    return this.x;
           ^
TypeError: Cannot read property 'x' of undefined
```

Happens in both 3.5.3 release and current `HEAD` (904a72fb3a25409e1dec46a90829afcf8a5cfde8). 

It's a very tortuous pattern unlikely to be seen in production, but I figured you might want to know anyway. All other weird patterns I tried worked just fine with the current `HEAD` tail recursion optimization.

Here's the generated code for reference. In both cases, `_this` is set to undefined after the first iteration.

3.5.3 release:
```javascript
"use strict";

function test(exit) {
  var _arguments = arguments,
      _this = this,
      _shouldContinue,
      _result;
  do {
    _shouldContinue = false;
    _result = (function (exit) {
      if (exit) {
        return this.x;
      }
      _arguments = [true];
      _this = undefined;
      return _shouldContinue = true;
    }).apply(_this, _arguments);
  } while (_shouldContinue);
  return _result;
}

test = test.bind({ x: "yay" });

console.log(test());
```

`HEAD` (904a72fb3a25409e1dec46a90829afcf8a5cfde8):
```javascript
"use strict";

function test(_x) {
  var _this = this;
  _function: while (true) {
    var exit = _x;
    if (exit) {
      return _this.x;
    }
    _this = undefined;
    _x = true;
    continue _function;
  }
}

test = test.bind({ x: "yay" });

console.log(test());
```

**Comment by sebmck** [comment]
Ping @RReverser, issue still present with the recent rewrite, any suggestions?

**Comment by sebmck** [comment]
@RReverser A good solution (and possibly only) is to opt out of tail recursion optimisation when the `FunctionDeclaration` we're in has been reassigned (will need to add something to the scope tracking possibly). Inside `FunctionExpression` we're fine due to the local id binding.

**Comment by RReverser** [comment]
@sebmck Yeah... Am I the only one who didn't know that it's not safe to rely on function name from inside `FunctionDeclaration` but only from inside `FunctionExpression`?

I guess the same problem might be with `spec.blockScopedFunctions` transformer as it also transforms declaration into variable + function expression (any others doing so?) which are not the same, and so references to function name from inside the function will get broken.

**Comment by sebmck** [comment]
@RReverser The scope tree is built on first traversal so it wont make a difference if the `FunctionDeclaration` is mutated. I'll just add a `reassigned` property to binding info (that refactor last night came in handy :stuck_out_tongue_winking_eye:).

**Comment by sebmck** [comment]
Too easy, that scope internal data structure refactor that I did made it trivial. Thanks for looking into this @peferron and trying to break it, really appreciated!
