### ISSUE TITLE
6to5-node breaks Node uncaughtException handler

### ISSUE THREAD

**Issue by atombender** [6to5/6to5#746]
Test case:

```javascript
process.on('uncaughtException', function(error) {
  console.log("uncaught");
});                       
throw new Error("Argh");
```

With Node:

```
# node test.js                            
uncaught
```

With 6to5-node:

```
# 6to5-node test.js
/tmp/test.js:6
throw new Error("Argh");
      ^
Error: Argh
[...]
```

**Comment by sebmck** [comment]
6to5 doesn't intercept `uncaughtException` anywhere. It's likely a problem with [source-map-support](https://github.com/evanw/node-source-map-support/blob/3b154ff43eddcaf4efffc456641c92b87788bffb/source-map-support.js#L332). Can you report it upstream?
