### ISSUE TITLE
Generated `let` for function inside of `if`

### ISSUE THREAD

**Issue by gilbox** [6to5/6to5#748]
I noticed that something like:

```
if (a) {
  function ack() { /* ... */ }
}
```

generates:

```
if (a) {
   let ack = function() { /* ... */ }
}
```

I know that declaring functions this way is code smell, but isn't this a bug?

**Comment by sebmck** [comment]
Nope, function declarations inside blocks are block scoped in ES6.

**Comment by gilbox** [comment]
Right, I get that. But the generated output was ES6 code. Isn't this project called 6to5 for a reason?

**Comment by sebmck** [comment]
@gilbox You shouldn't be getting that in your output. What version are you on? Can't replicate it in 3.5.3 which is the latest.

**Comment by gilbox** [comment]
6to5-loader which loads 6to5-core but i don't have the latest version. will try upgrading.

**Comment by gilbox** [comment]
√ upgrade fixed it

**Comment by sebmck** [comment]
Great! More than happy to help, feel free to open another issue if you run into anymore problems.
