### ISSUE TITLE
CLI mallet operator

### ISSUE THREAD

**Issue by pascalduez** [6to5/6to5#752]
```
6to5 --optional playground.malletOperator src --out-dir dist
```
```
SyntaxError: src/[...].js: Unexpected token (5:8)
```
While
```
6to5 --playground src --out-dir dist
```
All fine

**Comment by sebmck** [comment]
Yep, this is expected behaviour. `playground.malletOperator` isn't an optional transformer. Not sure what you're asking?

**Comment by pascalduez** [comment]
Oh okay, so I guess the docs and `--help` is a bit confusing:

```
-i, --optional [list]        List of optional transformers to enable
```
```
Transformers:

   [...]
    - playground.malletOperator
    [...]
```

**Comment by sebmck** [comment]
All the optional transformers are wrapped in `[` and `]` in `6to5 --help`. I'll look into automatically enabling the playground/experimental mode when you specify one of its transformer in optional though.

**Comment by pascalduez** [comment]
> All the optional transformers are wrapped in [ and ] in 6to5 --help

All right, make sense. But not really straightforward for non CLI experts :-)
Thanks for the quick answer.

Feel free to close.

**Comment by sebmck** [comment]
Great, feel free to open a new issue if you run into anymore issues or check out our [gitter room](http://gitter.im/6to5/6to5). Thanks!
