### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by carlskii** [6to5/6to5#753]
Hi,

I've been using Bluebird in some of my other ECMA5 projects to provide support for promises. I'm looking to build a new project using ECMA6 and will need support for Promises. Since the whole ECMA6 and 6to5 thing is still so new, I'm struggling to understand the best way to add this to my project. 

Do I just use Bluebird as per my ECMA5 code or is there a good way to do this using 6to5 ?

This is an example of my working my ECMA5 code:

```javascript
var Promise = require("bluebird");
var Request = Promise.promisify(require('request'));

function callhttp(host) {

    var cert = " ";

    var options = {
        url: 'https://' + host,
        method: "GET",
        headers: {
            'User-Agent': 'request'
        }
    };

    return Request(options).spread(function (response, body) {
        if (response.statusCode == 200) {
           // console.log(body)
            console.log(response.connection.getPeerCertificate().subject.CN)
            return {
                CN: response.connection.getPeerCertificate().subject.CN,
            };
        } else {
            // Just an example, 200 is not the only successful code
            throw new Error("HTTP Error: " + response.statusCode);
        }
    });
}


var join = Promise.join;
join(
    callhttp("www.google.com"),
    callhttp("www.microsoft.com"),
    callhttp("www.adobe.com"),
    function (first, second, third) {
        console.log([first, second, third]);
    });
```

**Comment by sebmck** [comment]
If you're using bluebird then there's no real reason to stop. It provides a superset of the features and methods available in ES6 Promises so you're likely going to be relying on some of those already.

**Comment by stefanpenner** [comment]
> It provides a superset of the features

/pedantic statement

actually it is an improper superset, more like c <-> c++. As it diverges in some scenarios, like subclassing. But don't let this scare you, bluebird is a rock solid promise implementation.

/#pedantic statement

**Comment by sebmck** [comment]
@stefanpenner Ah great, thanks for the clarification. I'm not as familiar with the Promise ecosystem as much as I'd like.

**Comment by stefanpenner** [comment]
If people don't utilize the a good proportion of the feature set, it may be slightly byte size heavy. But the 2-4 extra TCP packets it costs you I doubt hurt anyone.

**Comment by carlskii** [comment]
Thanks for the input here guys. Very helpful.
