### ISSUE TITLE
Array and spread operator

### ISSUE THREAD

**Issue by bendc** [6to5/6to5#754]
`[...Array(10)]` is compiled to this:
```javascript
var _toArray = function (arr) { return Array.isArray(arr) ? arr : Array.from(arr); };
[].concat(_toArray(Array(10)));
```
… which produces an array with "holes" instead of an iterable array with `undefined` elements. It should do something like this instead:
```javascript
Array.apply(0, Array(10));
```
Example of use:
https://gist.github.com/bendc/1e6af8f2d8027f2965da

**Comment by sebmck** [comment]
Do you have a reference for why `[...Array(10)]` should turn a holed array into one with all the values `undefined`?

**Comment by sebmck** [comment]
Actually no, I understand. Not sure how to support this without forcing the polyfill on people who just want to spread/destructure arrays. I'll have to think about it.

**Comment by sebmck** [comment]
Will be available in the next path, thanks!

**Comment by monsanto** [comment]
@sebmck Is the copy necessary for `func(...args)`  and `let [...bar] = foo`? They got affected by the change to `_toArray`. In either case, perhaps a loose mode that ignores sparse arrays is warranted.
