### ISSUE TITLE
Unnecessary extra `_toArray` call for array rest destructuring

### ISSUE THREAD

**Issue by monsanto** [6to5/6to5#757]
```
let [x, ...y] = z
```
--->
```
"use strict";

var _toArray = function (arr) { if (Array.isArray(arr)) { var arr2 = []; for (var i = 0; i < arr.length; i++) arr2.push(arr[i]); return arr2; } else { return Array.from(arr); } };

var _z = _toArray(z);

var x = _z[0];
var y = _toArray(_z).slice(1);
```

Calling `_toArray` again on `_z` is unnecessary, it's already guaranteed to be an array.

**Comment by lukescott** [comment]
Another thing I noticed:

- Wouldn't Array.from([]) work? Is _toArray necessary?
- If _toArray is necessary, couldn't the inner condition simply be `return arr.slice(0)`?

**Comment by jridgewell** [comment]
The for-loop is due to https://github.com/6to5/6to5/issues/754.

**Comment by lukescott** [comment]
@jridgewell The for loop makes a copy. Array.slice and Array.from do that as well. Before #754 the array was being returned directly. Since a copy is always returned, using just Array.from should work since an Array is also an iterator.

**Comment by sebmck** [comment]
@lukescott The point of special casing if it's an array is so the polyfill isn't required for array spread and destructuring, it also puts it in a hot path so it'll be faster for arrays which will be the main consumer of `toArray`.

**Comment by lukescott** [comment]
@sebmck Would the performance issue also apply to slice?

**Comment by sebmck** [comment]
@lukescott `Array(20).slice(0)` wont do anything to turn a sparse array into a consumable array with all the fields populated with `undefined`.

**Comment by lukescott** [comment]
@sebmck Got it, thanks!

**Comment by sebmck** [comment]
Actually that doesn't solve this issue, I'll possibly have to do some scope tracking.

**Comment by sebmck** [comment]
Once I implemented the type tracking instead of the following:

```javascirpt
function foo(...bar) {
  return [...bar];
}
```

Turning into:

```javascript
"use strict";

var _toConsumableArray = function (arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) arr2.push(arr[i]); return arr2; } else { return Array.from(arr); } };

function foo() {
  for (var _len = arguments.length, bar = Array(_len), _key = 0; _key < _len; _key++) {
    bar[_key] = arguments[_key];
  }

  return [].concat(_toConsumableArray(bar));
}
```

it'll turn into

```javascript
"use strict";

function foo() {
  for (var _len = arguments.length, bar = Array(_len), _key = 0; _key < _len; _key++) {
    bar[_key] = arguments[_key];
  }

  return [].concat(bar);
}
```

etc

**Comment by sebmck** [comment]
Reminder to self: On hitting `RestElement` or declaring a `File::toArray` node, register in the current scope that it's a `UnionType` and add logic in `File::toArray` to skip the helper injection if the input node is of the `UnionType` type.

**Comment by sebmck** [comment]
Much easier than I expected and works fantastically.

**Comment by monsanto** [comment]
Excellent. Thanks!
