### ISSUE TITLE
Comment gets thrown out of empty block

### ISSUE THREAD

**Issue by gaearon** [6to5/6to5#758]
```js
try {
  // yo
} catch (err) {
  // lol
}
```

becomes

```js
"use strict";

try {} catch (err) {}
// yo
// lol
```

**Comment by gaearon** [comment]
It isn't specific to try/catch, seems like an empty block behavior. It's just that most empty blocks don't make sense, but empty `catch` usually has a comment indicating why it's empty :-)

**Comment by sebmck** [comment]
Yeah, it's due to the current comment attachment algorithm. Planning on rolling our own that has an `insideComments` array or something. Delegating to #672.
