### ISSUE TITLE
class that extends itself doesn't compile correctly

### ISSUE THREAD

**Issue by simonzack** [6to5/6to5#759]
A class which extends itself isn't compiled correctly:

    class A {
        ...
    }

    class A extends A {
        ...
    }

I think the error comes from:

    inherits(A, A);

A workaround is to do:

    var A_ = A;
    class A extends A_ {

    }

**Comment by sebmck** [comment]
How are you expecting this to work?

**Comment by sebmck** [comment]
FYI

```javascript
class A {}
class A extends A {}
```

Wont even compile at all.

```
TypeError: stdin: Line 5: Duplicate declaration "A"
  3  | }
  4  |
> 5  | class A extends A {
     |       ^
  6  |
  7  | }
  8  |
```

**Comment by simonzack** [comment]
They're from different files. I'm expecting it to work like the original A was named something else.

**Comment by sebmck** [comment]
@simonzack I still don't understand what you mean.

**Comment by simonzack** [comment]
I'm expecting the first one to behave like the second:

    class A {}
    class A extends A {}

    class A {}
    var A_ = A;
    class A extends A_ {}

**Comment by sebmck** [comment]
Can you provide the actual file or a more elaborate example? That shouldn't even be allowed. You shouldn't be able to do that in the first place.

**Comment by monsanto** [comment]
I don't think  `class A extends A` is legal in any context, as the `A` will be in a temporal dead zone

**Comment by sebmck** [comment]
@monsanto That's already supported by the `es6.blockScopingTDZ` optional transformer that will probably be made default in the next major. I don't know how he's even getting that code to compile in the first place without it throwing an error since you can't redeclare a new class binding.

**Comment by simonzack** [comment]
@sebmck The first definition is in another file, and the second file imports it and redeclares. It's hard to give a concrete example since my setup 

The first file defines A in es5:

    function A(){
    }
    exports.A = A;

But I don't think that matters, I changed it to class and it still works.

The second file imports it like so:

    import {A} from 'A';

    class A extends A {
    ...
    }

This gets compiled, but the behavior isn't quite right. My actual setup involves gulp files and browserify, which is rather complicated to show here.

**Comment by sebmck** [comment]
Yeah, that's illegal. (At least it is in master, duplication error is mixed up but that's a completely unrelated issue that I'll fix now)

```
TypeError: test.js: Line 1: Duplicate declaration "A"
> 1  | import {A} from 'file';
     |         ^
  2  |
  3  | class A extends A {}
  4  |
```

**Comment by simonzack** [comment]
I'm on the latest version v3.5.3, btw, was that a recent commit?

**Comment by sebmck** [comment]
Last version was released 4 days ago. A lot of work has been done since then on the internals.
