### ISSUE TITLE
'let' loses its block scope when using same argument name in self-invoking function inside for-loop

### ISSUE THREAD

**Issue by dashukin** [6to5/6to5#763]
Invalid behavior:
```
for (let i = 1; i < 3; i += 1) {
  (function (i) {
    console.log(i);
  }(i))
}
console.log(i);
 // 1,2,3
```

Valid behavior:
```
for (let i = 1; i < 3; i += 1) {
  (function (a) {
    console.log(a);
  }(i))
}
console.log(i); 
 // 1, 2, i is not defined
```

**Comment by eventualbuddha** [comment]
Which one are you saying is the correct behavior? I would think it's the one you've labeled "Invalid behavior". Can you provide a link to the [REPL](http://6to5.org/repl) that illustrates the wrong behavior? I tried the examples you have and both seemed to work as I'd expect (log 1, then 2).

**Comment by LeonFedotov** [comment]
@eventualbuddha how about this example:
```javascript
try {
  for(let x = 0; x < 10;x++) {
    var a = () => x;
  }
  console.log(x, 'bad!'); 
} catch(e) {
  console.log('good');
}
```

**Comment by dashukin** [comment]
'i' is in the block scope and cannot be accessed out of it when using different local variable name (i.e. 'a') inside of self invoking function:
http://goo.gl/Pa1yeO

'i' can be accessed out of the block scope when using same variable name inside another function - so it not becomes local for this function and overwrites 'let i'
http://goo.gl/Ul0EuC

**Comment by eventualbuddha** [comment]
Ah, now I understand. That's what I get for reading code on my phone. Something about the presence of it inside the inner function is screwing it up. Thanks!

**Comment by appden** [comment]
This regressed on commit 3d9d842a0d4fbb6bd97b7cf353f73b714046eec1.

**Comment by sebmck** [comment]
@appden It probably would've been done before that. *Should* be an easy fix.

**Comment by appden** [comment]
@sebmck I ran `git bisect` and confirmed it works as expected in the commit before that: cfd028288f8820135651288d66602fc8ada88507

**Comment by sebmck** [comment]
I'll get around to this when I can:

Note to self: `remap` loop parent variables on `needsClosure`.
