### ISSUE TITLE
Cannot use variable name "KEY" inside exported class

### ISSUE THREAD

**Issue by markmicchelli** [6to5/6to5#765]
Here's a minimal example:

ES6:
```
class Test1 {
  constructor() {
    let KEY = "this works fine";
    console.log(KEY);
  }
}

export class Test2 {
  constructor() {
    let KEY = "this doesn't";
    console.log(KEY);
  }
}
```

6to5 output (using `--modules common`):
```
"use strict";

var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };

var Test1 = function Test1() {
  _classCallCheck(this, Test1);

  var KEY = "this works fine";
  console.log(KEY);
};

var Test2 = exports.Test2 = function Test2() {
  _classCallCheck(this, Test2);

  var Test2 = "this doesn't";
  console.log(Test2);
};

Object.defineProperty(exports, "__esModule", {
  value: true
});
```

Note how `KEY` has been replaced with the name of the class (in this case, `Test2`). I experience the same bug using `--modules amd` and `--modules umd`, but *not* `--modules system`.

**Comment by sebmck** [comment]
This is weird as hell. Might be something to do with templating possibly leaking out but beyond this I have no idea. I'll have to investigate.

**Comment by eventualbuddha** [comment]
@sebmck I figured it out. It is as you suspected. Templates are unintentionally recursing into the replacement values. I'll have a fix shortly.

**Comment by sebmck** [comment]
@eventualbuddha Oh yeah, replacements node will need to have a `this.skip();` in `util.template`. Huh, never took that into consideration.

**Comment by eventualbuddha** [comment]
@sebmck Yep. Took me a while to figure out how all the pieces fit together, but it definitely taught me more about the codebase which'll pay off later.

`this.skip()` inside the `enter` callback was much simpler than my first thought of collecting all the nodes to be replaced and checking that the nodes to be replaced were in that list.

**Comment by sebmck** [comment]
@eventualbuddha Yeah I'm planning on writing up some internal documentation on how everything is structured and works. Thanks for looking into this!
