### ISSUE TITLE
Array Destructuring an object throws ambiguous error.

### ISSUE THREAD

**Issue by YourDeveloperFriend** [6to5/6to5#766]
[Example](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=try%20%7B%0A%20%20var%20%5Bb%2C%20c%5D%20%3D%20%7Ba%3A%205%7D%3B%0A%7D%20catch(e)%20%7B%0A%20%20console.log(e.constructor.name%20%2B%20%22%3A%20%22%20%2B%20e.message)%3B%0A%7D)

```Javascript
var [b, c] = {a: 5};
// throws "TypeError: undefined is not a function"
```

I spent a long time trying to figure out what was happening, only to discover that a function was returning an object, not an array.

I'm not sure what kind of error the native version will eventually throw, but I'd appreciate something along the lines of `Invalid attempt to destructure non-iterable object [object Object]` or something.

**Comment by YourDeveloperFriend** [comment]
It looks like the change needs to take place [here](https://github.com/6to5/6to5/blob/c8cf7ff286879bff7c4bac51e702a3416bba8b43/lib/6to5/transformation/templates/sliced-to-array.js#L4)

Something like this:

```Javascript
(function (arr, i) {
  if(!arr || !arr[Symbol.iterator]) {
    throw new Error('Invalid attempt to destructure non-iterable instance "' + arr + '"');
  } else if (Array.isArray(arr)) {
    return arr;
  } else {
    var _arr = [];
    for (var _iterator = arr[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {
      _arr.push(_step.value);
      if (i && _arr.length === i) break;
    }
    return _arr;
  }
});
```

**Comment by monsanto** [comment]
+1 but specifically throw `TypeError`

**Comment by sebmck** [comment]
Good call, thanks! The spec doesn't actually specify error messages, only error types which means we can make up our own. There's currently no native implementation of this stuff so there are no references.

**Comment by zloirock** [comment]
@sebmck will be better:
```javascript
if (Array.isArray(arr)) {
  // ...
} else if(Symbol.iterator in arr) { // core.$for.isIterable() in selfContained
  // ...
} else throw TypeError(/* ... */);
```

**Comment by sebmck** [comment]
@zloirock Good idea, done.

**Comment by sebmck** [comment]
@zloirock Actually that'd be way slower.

**Comment by sebmck** [comment]
Fixed as of 3.6.1, thanks!

**Comment by zloirock** [comment]
@sebmck maybe. But it's work with array w/o polyfill, don't cause side effect with `get [Symbol.iterator]()` and `TypeError` more suitable than `Error` :)

**Comment by sebmck** [comment]
@zloirock Hmm, I'll see.

**Comment by YourDeveloperFriend** [comment]
Thanks guys, impressed with your promptness!

**Comment by monsanto** [comment]
Perhaps move the "get Symbol.iterator or throw TypeError" bit to a helper, and use in `for-of` loops as well?
