### ISSUE TITLE
System output - runtime deps to use .default access

### ISSUE THREAD

**Issue by guybedford** [6to5/6to5#774]
When using the System output, loading runtime or regenerator etc, it should do an access to the `.default` property of the module. That is - we should use `_regenerator.default.mark` instead of `_regenerator.mark` in the generated output.

**Comment by sebmck** [comment]
Does the same think need to be done for `6to5-runtime/helpers` and `6to5-runtime/core-js`?

**Comment by guybedford** [comment]
Yes, that would help. We wouldn't need to do this if we implemented the same treatment of copying the exports from default to the base-level like 6to5 does, but I'm hanging back on that until there's some pressure, perhaps unnecessarily.

Do let me know if you think I should just implement https://github.com/systemjs/systemjs/issues/304 rather. Would value your opinion.

**Comment by guybedford** [comment]
Sorry I meant to reference https://github.com/systemjs/systemjs/issues/334.

**Comment by sebmck** [comment]
Had to refactor a bunch of stuff but it should be solid.

**Comment by guybedford** [comment]
Wow, just wow. This was amazing quick, thanks!
