### ISSUE TITLE
Relative Source URLs in Source Maps

### ISSUE THREAD

**Issue by dburrows** [6to5/6to5#775]
I have a ES6 Module (test-es6-module/) for Node that I want to pre-compile.

I run the command `6to5 src --out-dir lib --source-maps` in the root of the to compile the src directory into lib

In the .map file the `sources` url is relative to the base module directory `

    "sources":["src/ExampleClass.js"]`

If we then install and require this module in a node project with source maps enabled, when we run it and one of the compiled files in the module throws an error we get a the wrong source url

    Error at new ExampleClass 
    (/SourceMapIssueTestCase/node_modules/test-es6-module/lib/src/ExampleClass.js:3:11)

Is there a way to get 6to5 to generate relative source map urls? 

(apologies if I've not RTFMd sufficiently)

**Comment by sebmck** [comment]
`cd` into `src` and run `$ 6to5` there?

**Comment by sebmck** [comment]
Actually nevermind, that wont work. `sourceMapName` should be resolved relative to the source location.

**Comment by dburrows** [comment]
man, that's some good support response times! Yep, can confirm that `cd src` and run doesn't work

**Comment by sebmck** [comment]
Should be fixed, I'll push out a new release once I've done a couple other things.

**Comment by dburrows** [comment]
I don't think this has fixed the issue, it generates the correct path for the src now but this doesn't seem to affect the sources url in the generated map

**Comment by sebmck** [comment]
That should do the trick. Sorry, doing multiple things at once.

**Comment by dburrows** [comment]
No need to apologise, you are doing an amazing job on 6to5 and your level of support is better than pretty much any other project on Github. Tested this and all good now, Cheers!
