### ISSUE TITLE
unable to deploy a Node app to Azure website due to a native depenency

### ISSUE THREAD

**Issue by bennage** [6to5/6to5#776]
I've built [an app](https://github.com/bennage/pundit) using `6to5` that I am deploying to an Azure website. When I attempt to use the _push to deploy_ model (as opposed to just uploading the build app), Azure runs `npm install` and the deployment fails. The problem is discussed here:
http://stackoverflow.com/questions/19039842/node-js-app-with-node-gyp-fails-to-deploy-on-azure-website

I narrowed the depedency down to `Chokidar` which in turn relies on `FSEvents`.

__My question is: is there away to make this depedency optional?__

I can workaround this, but I'd love get back to a push-to-deploy world. :wink: 

thanks.

**Comment by AluisioASG** [comment]
IIRC you can use the `6to5-core` package if you're using the API for the build process.

**Comment by bennage** [comment]
Thanks, I'll give that a shot and report back.

**Comment by sebmck** [comment]
Yeah, you're only using the `6to5` for `6to5/register` so installing `6to5-core` and using `6to5-core/register` will work since `6to5-core` doesn't include `chokidar` as it's only needed for the CLI.

**Comment by bennage** [comment]
Everything is working. Many thanks!
